import { Course } from "../courses";
export const BIO_COURSES: Course[] = [
  {
    id: "bio-1",
    title: "[G30]農学部応用生命科学実験(2022年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    teacher: "Full-year course(Sp-Fa) Fri 5 邊見 久 / HEMMI Hisashi",
  },
  {
    id: "bio-2",
    title: "生物情報計測学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "土川 覚 稲垣 哲也 / TSUCHIKAWA Satoru INAGAKI Tetsuya",
  },
  {
    id: "bio-3",
    title: "木質環境学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "bio-4",
    title: "栄養科学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "中島 健一朗 / NAKAJIMA Ken-ichiro",
  },
  {
    id: "bio-5",
    title: "木質環境学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "bio-6",
    title: "栄養科学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "中島 健一朗 / NAKAJIMA Ken-ichiro",
  },
  {
    id: "bio-7",
    title: "有機化学1(生命)(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "北 将樹 横島 聡 / KITA Masaki YOKOSHIMA Satoshi",
  },
  {
    id: "bio-8",
    title: "森林保護学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "梶村 恒 / KAJIMURA Hisashi",
  },
  {
    id: "bio-9",
    title: "生産土壌学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "浅川 晋 村瀬 潤 近藤 始彦 / ASAKAWA Susumu MURASE Jun KONDO Motohiko",
  },
  {
    id: "bio-10",
    title: "食品機能化学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "柴田 貴広 / SHIBATA Takahiro",
  },
  {
    id: "bio-11",
    title: "[G30]生物有機化学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "西川 俊夫 北 将樹 青井 啓悟 中川 優 / NISHIKAWA Toshio KITA Masaki AOI Keigo NAKAGAWA Yu",
  },
  {
    id: "bio-12",
    title: "森林保護学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "梶村 恒 / KAJIMURA Hisashi",
  },
  {
    id: "bio-13",
    title: "生産土壌学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "浅川 晋 村瀬 潤 近藤 始彦 / ASAKAWA Susumu MURASE Jun KONDO Motohiko",
  },
  {
    id: "bio-14",
    title: "食品機能化学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "柴田 貴広 / SHIBATA Takahiro",
  },
  {
    id: "bio-15",
    title: "バイオマス科学1(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "福島 和彦 今井 貴規 / FUKUSHIMA Kazuhiko IMAI Takanori",
  },
  {
    id: "bio-16",
    title: "生物環境科学実験実習(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "谷川 東子 / TANIKAWA Toko",
  },
  {
    id: "bio-17",
    title: "応用生命科学実験実習1(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "bio-18",
    title: "特別実験(卒業研究)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-3",
    teacher:
      "中道 範人 各研究室担当教員 / NAKAMICHI Norihito Faculty in charge of each laboratory",
  },
  {
    id: "bio-19",
    title: "[G30]農学部応用生命科学実験1",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "bio-20",
    title: "生物環境科学実験実習1",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "谷川 東子 / TANIKAWA Toko",
  },
  {
    id: "bio-21",
    title: "資源生物科学基盤実験実習",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "石川 明 / ISHIKAWA Akira",
  },
  {
    id: "bio-22",
    title: "応用生命科学実験実習1",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "bio-23",
    title: "生物材料組織学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "吉田 正人 山本 浩之 / YOSHIDA Masato YAMAMOTO Hiroyuki",
  },
  {
    id: "bio-24",
    title: "生物化学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-1",
    teacher:
      "西島 謙一 村井 篤嗣 新美 友章 / NISHIJIMA Kenichi MURAI Atsushi NIIMI Tomoaki",
  },
  {
    id: "bio-25",
    title: "生物有機化学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "西川 俊夫 / NISHIKAWA Toshio",
  },
  {
    id: "bio-26",
    title: "[G30]先端有機・高分子化学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "村井 征史 / MURAI Masahito",
  },
  {
    id: "bio-27",
    title: "有機化学4",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "西川 俊夫 / NISHIKAWA Toshio",
  },
  {
    id: "bio-28",
    title: "有機化学1(環境・資生)(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "今井 貴規 水口 智江可 / IMAI Takanori MINAKUCHI Chieka",
  },
  {
    id: "bio-29",
    title: "生体分子化学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "青井 啓悟 北 将樹 / AOI Keigo KITA Masaki",
  },
  {
    id: "bio-30",
    title: "生態遺伝学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "戸丸 信弘 / TOMARU Nobuhiro",
  },
  {
    id: "bio-31",
    title: "[G30]微生物学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "木村 眞 邊見 久 COROVIC Jasmina / KIMURA Makoto HEMMI Hisashi COROVIC Jasmina",
  },
  {
    id: "bio-32",
    title: "保全遺伝学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "戸丸 信弘 / TOMARU Nobuhiro",
  },
  {
    id: "bio-33",
    title: "生命分子化学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "青井 啓悟 北 将樹 / AOI Keigo KITA Masaki",
  },
  {
    id: "bio-34",
    title: "生態学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "土岐 和多瑠 / TOKI Wataru",
  },
  {
    id: "bio-35",
    title: "資源生物科学実験実習(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "石川 明 / ISHIKAWA Akira",
  },
  {
    id: "bio-36",
    title: "資源生物科学実験実習1",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "石川 明 / ISHIKAWA Akira",
  },
  {
    id: "bio-37",
    title: "生命物理化学1(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "bio-38",
    title: "生物環境計測学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "山本 一清 / YAMAMOTO Kazukiyo",
  },
  {
    id: "bio-39",
    title: "高分子化学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "青井 啓悟 野村 信嘉 / AOI Keigo NOMURA Nobuyoshi",
  },
  {
    id: "bio-40",
    title: "遺伝学2",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "bio-41",
    title: "生物物理学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "Florence Tama",
  },
  {
    id: "bio-42",
    title: "生物環境計測学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "山本 一清 / YAMAMOTO Kazukiyo",
  },
  {
    id: "bio-43",
    title: "高分子化学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "青井 啓悟 野村 信嘉 / AOI Keigo NOMURA Nobuyoshi",
  },
  {
    id: "bio-44",
    title: "食品衛生学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "柴田 貴広 大島 健司 / SHIBATA Takahiro OSHIMA Kenji",
  },
  {
    id: "bio-45",
    title: "食と農の経済学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "徳田 博美 / TOKUDA Hiromi",
  },
  {
    id: "bio-46",
    title: "森林生態学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "中川 弥智子 / NAKAGAWA Michiko",
  },
  {
    id: "bio-47",
    title: "生物反応工学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "中野 秀雄 加藤 晃代 / NAKANO Hideo KATO Teruyo",
  },
  {
    id: "bio-48",
    title: "[G30]植物生理学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-2",
    teacher:
      "中道 範人 村中 智明 BELLEGARDE Fanny 前田 真一 / NAKAMICHI Norihito MURANAKA Tomoaki BELLEGARDE Fanny MAEDA Shin ichi",
  },
  {
    id: "bio-49",
    title: "[G30]有機化学2",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "bio-50",
    title: "森林生態学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "中川 弥智子 / NAKAGAWA Michiko",
  },
  {
    id: "bio-51",
    title: "生物反応工学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "中野 秀雄 加藤 晃代 / NAKANO Hideo KATO Teruyo",
  },
  {
    id: "bio-52",
    title: "食品衛生学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "柴田 貴広 大島 健司 / SHIBATA Takahiro OSHIMA Kenji",
  },
  {
    id: "bio-53",
    title: "動物生理学1(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-3",
    teacher:
      "吉村 崇 阿部 秀樹 大川 妙子 中山 友哉 / YOSHIMURA Takashi ABE Hideki OHKAWA Taeko NAKAYAMA Tomoya",
  },
  {
    id: "bio-54",
    title: "資源生物科学セミナー(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "山縣 高宏 / YAMAGATA Takahiro",
  },
  {
    id: "bio-55",
    title: "農学セミナー1(環境)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "今井 貴規 小谷 亜由美 / IMAI Takanori KOTANI Ayumi",
  },
  {
    id: "bio-56",
    title: "農学セミナー1(資生)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "山縣 高宏 / YAMAGATA Takahiro",
  },
  {
    id: "bio-57",
    title: "農学セミナー1(生命)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "中道 範人 / NAKAMICHI Norihito",
  },
  {
    id: "bio-58",
    title: "生物圏環境学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Thu-1",
    teacher:
      "渡邉 彰 谷川 東子 三屋 史朗 / WATANABE Akira TANIKAWA Toko MITSUYA Shiro",
  },
  {
    id: "bio-59",
    title: "微生物学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "木村 眞 渡邉 健史 / KIMURA Makoto WATANABE Takeshi",
  },
  {
    id: "bio-60",
    title: "生理・発生生物学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "bio-61",
    title: "生物圏環境学2",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Thu-1",
    teacher:
      "渡邉 彰 谷川 東子 三屋 史朗 / WATANABE Akira TANIKAWA Toko MITSUYA Shiro",
  },
  {
    id: "bio-62",
    title: "微生物学2",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "木村 眞 渡邉 健史 / KIMURA Makoto WATANABE Takeshi",
  },
  {
    id: "bio-63",
    title: "食糧生産管理学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "徳田 博美 / TOKUDA Hiromi",
  },
  {
    id: "bio-64",
    title: "分子生物学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "石黒 澄衞 山篠 貴史 / ISHIGURO Sumie YAMASHINO Takafumi",
  },
  {
    id: "bio-65",
    title: "[G30]生化学4",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Thu-2",
    teacher:
      "灘野 大太 石黒 澄衞 山篠 貴史 / NADANO Daita ISHIGURO Sumie YAMASHINO Takafumi",
  },
  {
    id: "bio-66",
    title: "農業・資源経済学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "徳田 博美 / TOKUDA Hiromi",
  },
  {
    id: "bio-67",
    title: "分子細胞生物学2",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "石黒 澄衞 山篠 貴史 / ISHIGURO Sumie YAMASHINO Takafumi",
  },
  {
    id: "bio-68",
    title: "樹木生化学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "今井 貴規 福島 和彦 / IMAI Takanori FUKUSHIMA Kazuhiko",
  },
  {
    id: "bio-69",
    title: "有機構造解析学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "北 将樹 恒松 雄太 / KITA Masaki TSUNEMATSU Yuta",
  },
  {
    id: "bio-70",
    title: "樹木生化学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "今井 貴規 福島 和彦 / IMAI Takanori FUKUSHIMA Kazuhiko",
  },
  {
    id: "bio-71",
    title: "有機構造解析学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "北 将樹 恒松 雄太 / KITA Masaki TSUNEMATSU Yuta",
  },
  {
    id: "bio-72",
    title: "植物機能学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "藤田 祐一 / FUJITA Yuichi",
  },
  {
    id: "bio-73",
    title: "[G30]細胞学4",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "柴田 秀樹 MATURANA Andres Daniel 小田 裕昭 / SHIBATA Hideki MATURANA Andres Daniel ODA Hiroaki",
  },
  {
    id: "bio-74",
    title: "木質材料物理学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "土川 覚 山本 浩之 稲垣 哲也 / TSUCHIKAWA Satoru YAMAMOTO Hiroyuki INAGAKI Tetsuya",
  },
  {
    id: "bio-75",
    title: "植物機能学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "藤田 祐一 / FUJITA Yuichi",
  },
  {
    id: "bio-76",
    title: "動物生理学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-1",
    teacher:
      "山本 直之 萩尾 華子 中山 友哉 吉村 崇 村井 篤嗣 塚田 光 / YAMAMOTO Naoyuki HAGIO Hanako NAKAYAMA Tomoya YOSHIMURA Takashi MURAI Atsushi TSUKADA Akira",
  },
  {
    id: "bio-77",
    title: "動物生理学2",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-1",
    teacher:
      "山本 直之 萩尾 華子 中山 友哉 吉村 崇 村井 篤嗣 塚田 光 / YAMAMOTO Naoyuki HAGIO Hanako NAKAYAMA Tomoya YOSHIMURA Takashi MURAI Atsushi TSUKADA Akira",
  },
  {
    id: "bio-78",
    title: "植物育種学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-3",
    teacher:
      "中園 幹生 永井 啓祐 佐塚 隆志 髙橋 宏和 / NAKAZONO Mikio NAGAI Keisuke SAZUKA Takashi TAKAHASHI Hirokazu",
  },
  {
    id: "bio-79",
    title: "植物育種学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-3",
    teacher:
      "中園 幹生 永井 啓祐 佐塚 隆志 髙橋 宏和 / NAKAZONO Mikio NAGAI Keisuke SAZUKA Takashi TAKAHASHI Hirokazu",
  },
  {
    id: "bio-80",
    title: "生体防御学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-4",
    teacher:
      "竹本 大吾 佐藤 育男 吉岡 博文 千葉 壮太郎 / TAKEMOTO Daigo SATO Ikuo YOSHIOKA Hirofumi CHIBA Sotaro",
  },
  {
    id: "bio-81",
    title: "植物病理学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-4",
    teacher:
      "竹本 大吾 佐藤 育男 吉岡 博文 千葉 壮太郎 / TAKEMOTO Daigo SATO Ikuo YOSHIOKA Hirofumi CHIBA Sotaro",
  },
  {
    id: "bio-82",
    title: "フードシステム論",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "三浦 聡 / MIURA Satoshi",
  },
  {
    id: "bio-83",
    title: "動物育種学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "隅山 健太 田邉 彰 石川 明 山縣 高宏 / SUMIYAMA Kenta TANABE Akira ISHIKAWA Akira YAMAGATA Takahiro",
  },
  {
    id: "bio-84",
    title: "動物育種学",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "隅山 健太 田邉 彰 石川 明 山縣 高宏 / SUMIYAMA Kenta TANABE Akira ISHIKAWA Akira YAMAGATA Takahiro",
  },
  {
    id: "bio-85",
    title: "動物生産科学1(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春2",
    cellKey: "Mon-1",
    teacher:
      "上野山 賀久 松山 秀一 中村 翔 井上 直子 / UENOYAMA Yoshihisa MATSUYAMA Shuichi NAKAMURA Sho INOUE Naoko",
  },
  {
    id: "bio-86",
    title: "動物繁殖学",
    section: "専門",
    department: "農",
    semester: "春2",
    cellKey: "Mon-1",
    teacher:
      "上野山 賀久 松山 秀一 中村 翔 井上 直子 / UENOYAMA Yoshihisa MATSUYAMA Shuichi NAKAMURA Sho INOUE Naoko",
  },
  {
    id: "bio-87",
    title: "植物生産科学1(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春2",
    cellKey: "Mon-3",
    teacher:
      "近藤 始彦 杉浦 大輔 矢野 勝也 / KONDO Motohiko SUGIURA Daisuke YANO Katsuya",
  },
  {
    id: "bio-88",
    title: "作物科学",
    section: "専門",
    department: "農",
    semester: "春2",
    cellKey: "Mon-3",
    teacher:
      "近藤 始彦 杉浦 大輔 矢野 勝也 / KONDO Motohiko SUGIURA Daisuke YANO Katsuya",
  },
  {
    id: "bio-89",
    title: "環境倫理学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春2",
    cellKey: "Tue-1",
    teacher: "中川 弥智子 / NAKAGAWA Michiko",
  },
  {
    id: "bio-90",
    title: "国際森林資源論",
    section: "専門",
    department: "農",
    semester: "春2",
    cellKey: "Tue-1",
    teacher: "中川 弥智子 / NAKAGAWA Michiko",
  },
  {
    id: "bio-91",
    title: "細胞工学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春2",
    cellKey: "Tue-2",
    teacher:
      "西島 謙一 隅山 健太 山内 卓樹 大川 妙子 池田 素子 佐塚 隆志 / NISHIJIMA Kenichi SUMIYAMA Kenta YAMAUCHI Takaki OHKAWA Taeko IKEDA Motoko SAZUKA Takashi",
  },
  {
    id: "bio-92",
    title: "細胞工学",
    section: "専門",
    department: "農",
    semester: "春2",
    cellKey: "Tue-2",
    teacher:
      "西島 謙一 隅山 健太 山内 卓樹 大川 妙子 池田 素子 佐塚 隆志 / NISHIJIMA Kenichi SUMIYAMA Kenta YAMAUCHI Takaki OHKAWA Taeko IKEDA Motoko SAZUKA Takashi",
  },
  {
    id: "bio-93",
    title: "細胞生物学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "柴田 秀樹 灘野 大太 / SHIBATA Hideki NADANO Daita",
  },
  {
    id: "bio-94",
    title: "流域保全学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "五味 高志 / GOMI Takashi",
  },
  {
    id: "bio-95",
    title: "微生物学3(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "饗場 浩文 / AIBA Hirofumi",
  },
  {
    id: "bio-96",
    title: "流域保全学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "五味 高志 / GOMI Takashi",
  },
  {
    id: "bio-97",
    title: "分子微生物学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "饗場 浩文 / AIBA Hirofumi",
  },
  {
    id: "bio-98",
    title: "生物化学3(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "榊原 均 石黒 澄衞 / SAKAKIBARA Hitoshi ISHIGURO Sumie",
  },
  {
    id: "bio-99",
    title: "遺伝子工学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "武田 真 髙原 照直 / TAKEDA Shin TAKAHARA Terunao",
  },
  {
    id: "bio-100",
    title: "[G30]生理・解剖学1",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "bio-101",
    title: "遺伝子工学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "武田 真 髙原 照直 / TAKEDA Shin TAKAHARA Terunao",
  },
  {
    id: "bio-102",
    title: "植物生理学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher:
      "辻 寛之 山内 卓樹 西内 俊策 / TSUJI Hiroyuki YAMAUCHI Takaki NISHIUCHI Shunsaku",
  },
  {
    id: "bio-103",
    title: "応用生命科学実験実習2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "bio-104",
    title: "[G30]農学部応用生命科学実験2",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "bio-105",
    title: "生物環境科学実験実習2",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "谷川 東子 / TANIKAWA Toko",
  },
  {
    id: "bio-106",
    title: "応用生命科学実験実習2",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "bio-107",
    title: "昆虫科学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher:
      "水口 智江可 池田 素子 三高 雄希 浜島 りな / MINAKUCHI Chieka IKEDA Motoko MITAKA Yuki HAMAJIMA Rina",
  },
  {
    id: "bio-108",
    title: "生物材料力学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "bio-109",
    title: "バイオマス科学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "山本 浩之 吉田 正人 / YAMAMOTO Hiroyuki YOSHIDA Masato",
  },
  {
    id: "bio-110",
    title: "農業政策学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "徳田 博美 / TOKUDA Hiromi",
  },
  {
    id: "bio-111",
    title: "バイオマス科学2",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "山本 浩之 吉田 正人 / YAMAMOTO Hiroyuki YOSHIDA Masato",
  },
  {
    id: "bio-112",
    title: "農業・農村制度論",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "徳田 博美 / TOKUDA Hiromi",
  },
  {
    id: "bio-113",
    title: "分子細胞生物学3",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher:
      "人見 清隆 MATURANA Andres Daniel 柴田 秀樹 / HITOMI Kiyotaka MATURANA Andres Daniel SHIBATA Hideki",
  },
  {
    id: "bio-114",
    title: "植物生理学1(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "谷口 光隆 三屋 史朗 / TANIGUCHI Mitsutaka MITSUYA Shiro",
  },
  {
    id: "bio-115",
    title: "植物機能学1(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "藤田 祐一 上口 智治 中道 範人 / FUJITA Yuichi UEGUCHI Chiharu NAKAMICHI Norihito",
  },
  {
    id: "bio-116",
    title: "応用数学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "稲垣 哲也 山本 浩之 / INAGAKI Tetsuya YAMAMOTO Hiroyuki",
  },
  {
    id: "bio-117",
    title: "生命物理化学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "邊見 久 伊藤 智和 / HEMMI Hisashi ITO Tomokazu",
  },
  {
    id: "bio-118",
    title: "[G30]生理・解剖学2",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "日比 正彦 / HIBI Masahiko",
  },
  {
    id: "bio-119",
    title: "応用数学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "稲垣 哲也 山本 浩之 / INAGAKI Tetsuya YAMAMOTO Hiroyuki",
  },
  {
    id: "bio-120",
    title: "生命物理化学2",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "邊見 久 伊藤 智和 / HEMMI Hisashi ITO Tomokazu",
  },
  {
    id: "bio-121",
    title: "資源生物科学実験実習2",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "石川 明 / ISHIKAWA Akira",
  },
  {
    id: "bio-122",
    title: "分子生物学1(環境・資生)(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "一柳 健司 吉岡 博文 / ICHIYANAGI Kenji YOSHIOKA Hirofumi",
  },
  {
    id: "bio-123",
    title: "分子生物学1(生命)(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "山篠 貴史 中道 範人 / YAMASHINO Takafumi NAKAMICHI Norihito",
  },
  {
    id: "bio-124",
    title: "環境政策学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "岩永 青史 / IWANAGA Seiji",
  },
  {
    id: "bio-125",
    title: "生理活性物質化学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "中川 優 恒松 雄太 / NAKAGAWA Yu TSUNEMATSU Yuta",
  },
  {
    id: "bio-126",
    title: "[G30]化学物理学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "内橋 貴之 / UCHIHASHI Takayuki",
  },
  {
    id: "bio-127",
    title: "森林社会共生学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "岩永 青史 / IWANAGA Seiji",
  },
  {
    id: "bio-128",
    title: "生理活性物質化学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "中川 優 恒松 雄太 / NAKAGAWA Yu TSUNEMATSU Yuta",
  },
  {
    id: "bio-129",
    title: "有機化学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "西川 俊夫 横島 聡 / NISHIKAWA Toshio YOKOSHIMA Satoshi",
  },
  {
    id: "bio-130",
    title: "地形情報学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "山本 一清 五味 高志 戸丸 信弘 / YAMAMOTO Kazukiyo GOMI Takashi TOMARU Nobuhiro",
  },
  {
    id: "bio-131",
    title: "応用植物分子科学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "藤田 祐一 上口 智治 / FUJITA Yuichi UEGUCHI Chiharu",
  },
  {
    id: "bio-132",
    title: "[G30]遺伝学3",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "杉山 伸 / SUGIYAMA Shin",
  },
  {
    id: "bio-133",
    title: "森林資源管理学1",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "山本 一清 五味 高志 戸丸 信弘 / YAMAMOTO Kazukiyo GOMI Takashi TOMARU Nobuhiro",
  },
  {
    id: "bio-134",
    title: "応用植物分子科学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "藤田 祐一 上口 智治 / FUJITA Yuichi UEGUCHI Chiharu",
  },
  {
    id: "bio-135",
    title: "生命と技術の倫理(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher:
      "大蔵 聡 石黒 澄衞 河野 廉 原田 一宏 石川 明 三浦 聡 梶村 恒 / OHKURA Satoshi ISHIGURO Sumie KAWANO Yasushi HARADA Kazuhiro ISHIKAWA Akira MIURA Satoshi KAJIMURA Hisashi",
  },
  {
    id: "bio-136",
    title: "生物統計学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher:
      "山本 一清 一柳 健司 阿部 秀樹 梶村 恒 中川 弥智子 土井 一行 岩永 青史 / YAMAMOTO Kazukiyo ICHIYANAGI Kenji ABE Hideki KAJIMURA Hisashi NAKAGAWA Michiko DOI Kazuyuki IWANAGA Seiji",
  },
  {
    id: "bio-137",
    title: "生物情報処理演習(環境・資生)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher:
      "山本 一清 一柳 健司 阿部 秀樹 梶村 恒 中川 弥智子 土井 一行 岩永 青史 / YAMAMOTO Kazukiyo ICHIYANAGI Kenji ABE Hideki KAJIMURA Hisashi NAKAGAWA Michiko DOI Kazuyuki IWANAGA Seiji",
  },
  {
    id: "bio-138",
    title: "農学セミナー2(生命)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "中道 範人 / NAKAMICHI Norihito",
  },
  {
    id: "bio-139",
    title: "Agricultural Science(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher:
      "井上 直子 青木 弾 山内 章 谷口 光隆 束村 博子 村瀬 潤 小谷 亜由美 水口 智江可 伊藤 香純 北浦 靖之 / INOUE Naoko AOKI Dan YAMAUCHI Akira TANIGUCHI Mitsutaka TSUKAMURA Hiroko MURASE Jun KOTANI Ayumi MINAKUCHI Chieka ITO Kasumi KITAURA Yasuyuki",
  },
  {
    id: "bio-140",
    title: "[G30]Agricultural Science",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher: "井上 直子 / INOUE Naoko",
  },
  {
    id: "bio-141",
    title: "Agricultural Sciences",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher:
      "井上 直子 五味 高志 青木 弾 COROVIC Jasmina 谷口 光隆 村瀬 潤 水口 智江可 伊藤 香純 土井 一行 / INOUE Naoko GOMI Takashi AOKI Dan COROVIC Jasmina TANIGUCHI Mitsutaka MURASE Jun MINAKUCHI Chieka ITO Kasumi DOI Kazuyuki",
  },
  {
    id: "bio-142",
    title: "農学セミナー2(環境)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher: "今井 貴規 小谷 亜由美 / IMAI Takanori KOTANI Ayumi",
  },
  {
    id: "bio-143",
    title: "農学セミナー2(資生)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher: "山縣 高宏 / YAMAGATA Takahiro",
  },
  {
    id: "bio-144",
    title: "土壌学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher:
      "渡邉 彰 村瀬 潤 浅川 晋 / WATANABE Akira MURASE Jun ASAKAWA Susumu",
  },
  {
    id: "bio-145",
    title: "Academic Presentation Skills",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "MATURANA Andres Daniel",
  },
  {
    id: "bio-146",
    title: "[G30][遠隔]計算化学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "柳井 毅 / YANAI Takeshi",
  },
  {
    id: "bio-147",
    title: "農学セミナー3",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "MATURANA Andres Daniel",
  },
  {
    id: "bio-148",
    title: "資源微生物学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "池田 素子 竹本 大吾 / IKEDA Motoko TAKEMOTO Daigo",
  },
  {
    id: "bio-149",
    title: "微生物学1(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "木村 眞 / KIMURA Makoto",
  },
  {
    id: "bio-150",
    title: "設計製図(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "安藤 幸世 / ANDO Kosei",
  },
  {
    id: "bio-151",
    title: "微生物生態学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "渡邉 健史 浅川 晋 / WATANABE Takeshi ASAKAWA Susumu",
  },
  {
    id: "bio-152",
    title: "[G30]遺伝学1",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "bio-153",
    title: "[G30]細胞学3",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "木下 専 / KINOSHITA Makoto",
  },
  {
    id: "bio-154",
    title: "設計製図",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "安藤 幸世 / ANDO Kosei",
  },
  {
    id: "bio-155",
    title: "微生物生態学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "渡邉 健史 浅川 晋 / WATANABE Takeshi ASAKAWA Susumu",
  },
  {
    id: "bio-156",
    title: "生物圏環境学1(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher:
      "五味 高志 渡邉 彰 小谷 亜由美 / GOMI Takashi WATANABE Akira KOTANI Ayumi",
  },
  {
    id: "bio-157",
    title: "バイオマス変換化学1(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher:
      "青木 弾 福島 和彦 今井 貴規 / AOKI Dan FUKUSHIMA Kazuhiko IMAI Takanori",
  },
  {
    id: "bio-158",
    title: "資源生物科学基盤実験実習(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "石川 明 / ISHIKAWA Akira",
  },
  {
    id: "bio-159",
    title: "バイオマス変換化学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher:
      "青木 弾 福島 和彦 今井 貴規 / AOKI Dan FUKUSHIMA Kazuhiko IMAI Takanori",
  },
  {
    id: "bio-160",
    title: "生物統計学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher:
      "新美 友章 橋本(杉本) 美海 山本 治樹 / NIIMI Tomoaki HASHIMOTO(SUGIMOTO) Mimi YAMAMOTO Haruki",
  },
  {
    id: "bio-161",
    title: "住宅科学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "bio-162",
    title: "生物情報処理演習(生命)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher:
      "新美 友章 橋本(杉本) 美海 山本 治樹 / NIIMI Tomoaki HASHIMOTO(SUGIMOTO) Mimi YAMAMOTO Haruki",
  },
  {
    id: "bio-163",
    title: "住宅科学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "bio-164",
    title: "高分子設計学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "野村 信嘉 青井 啓悟 / NOMURA Nobuyoshi AOI Keigo",
  },
  {
    id: "bio-165",
    title: "高分子設計学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "野村 信嘉 青井 啓悟 / NOMURA Nobuyoshi AOI Keigo",
  },
  {
    id: "bio-166",
    title: "細胞生物学4(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "新美 友章 大島 健司 / NIIMI Tomoaki OSHIMA Kenji",
  },
  {
    id: "bio-167",
    title: "[G30]生化学3",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher:
      "小嶋 誠司 打田 直行 廣田 毅 吉成 晃 / KOJIMA Seiji UCHIDA Naoyuki HIROTA Tsuyoshi YOSHINARI Akira",
  },
  {
    id: "bio-168",
    title: "分子細胞生物学4",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "新美 友章 大島 健司 / NIIMI Tomoaki OSHIMA Kenji",
  },
  {
    id: "bio-169",
    title: "動物生産科学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "村井 篤嗣 / MURAI Atsushi",
  },
  {
    id: "bio-170",
    title: "動物栄養学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "村井 篤嗣 / MURAI Atsushi",
  },
  {
    id: "bio-171",
    title: "植物生産科学2(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "白武 勝裕 / SHIRATAKE Katsuhiro",
  },
  {
    id: "bio-172",
    title: "園芸科学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "白武 勝裕 / SHIRATAKE Katsuhiro",
  },
  {
    id: "bio-173",
    title: "昆虫生産科学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher:
      "池田 素子 水口 智江可 三高 雄希 浜島 りな / IKEDA Motoko MINAKUCHI Chieka MITAKA Yuki HAMAJIMA Rina",
  },
  {
    id: "bio-174",
    title: "昆虫科学2",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher:
      "池田 素子 水口 智江可 三高 雄希 浜島 りな / IKEDA Motoko MINAKUCHI Chieka MITAKA Yuki HAMAJIMA Rina",
  },
  {
    id: "bio-175",
    title: "動物生産科学3(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher:
      "大蔵 聡 松山 秀一 中村 翔 上野山 賀久 井上 直子 / OHKURA Satoshi MATSUYAMA Shuichi NAKAMURA Sho UENOYAMA Yoshihisa INOUE Naoko",
  },
  {
    id: "bio-176",
    title: "動物管理衛生学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher:
      "大蔵 聡 松山 秀一 中村 翔 上野山 賀久 井上 直子 / OHKURA Satoshi MATSUYAMA Shuichi NAKAMURA Sho UENOYAMA Yoshihisa INOUE Naoko",
  },
  {
    id: "bio-177",
    title: "植物保護学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "竹本 大吾 佐藤 育男 吉岡 博文 水口 智江可 三高 雄希 千葉 壮太郎 / TAKEMOTO Daigo SATO Ikuo YOSHIOKA Hirofumi MINAKUCHI Chieka MITAKA Yuki CHIBA Sotaro",
  },
  {
    id: "bio-178",
    title: "植物保護学",
    section: "専門",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "竹本 大吾 佐藤 育男 吉岡 博文 水口 智江可 三高 雄希 千葉 壮太郎 / TAKEMOTO Daigo SATO Ikuo YOSHIOKA Hirofumi MINAKUCHI Chieka MITAKA Yuki CHIBA Sotaro",
  },
  {
    id: "bio-179",
    title: "持続的生物生産学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋2",
    cellKey: "Mon-1",
    teacher:
      "大蔵 聡 三浦 聡 近藤 始彦 / OHKURA Satoshi MIURA Satoshi KONDO Motohiko",
  },
  {
    id: "bio-180",
    title: "持続的生物生産学",
    section: "専門",
    department: "農",
    semester: "秋2",
    cellKey: "Mon-1",
    teacher:
      "大蔵 聡 三浦 聡 近藤 始彦 / OHKURA Satoshi MIURA Satoshi KONDO Motohiko",
  },
  {
    id: "bio-181",
    title: "植物分類・植生学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "戸丸 信弘 中川 弥智子 / TOMARU Nobuhiro NAKAGAWA Michiko",
  },
  {
    id: "bio-182",
    title: "特許法(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "鬼頭 雅弘 / KITO Masahiro",
  },
  {
    id: "bio-183",
    title: "食品工学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher:
      "井上 孝司 森 大輔 石川 篤志 小関 誠 / INOUE Takashi MORI Daisuke ISHIKAWA Atsushi OZEKI Makoto",
  },
  {
    id: "bio-184",
    title: "農学部特別講義 バイオベンチャーとイノ (2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher:
      "河野 廉 矢野 貴大 上原 雅行 / KAWANO Yasushi YANO Takahiro UEHARA Masayuki",
  },
  {
    id: "bio-185",
    title: "農学部特別講義 農林行政論1 (2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "小林 勝利 / KOBAYASHI Katsutoshi",
  },
  {
    id: "bio-186",
    title: "農学部特別講義 農林行政論2 (2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "小林 勝利 / KOBAYASHI Katsutoshi",
  },
  {
    id: "bio-187",
    title: "農学部特別講義 農業農村工学(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "西村 伸一 / NISHIMURA Shinichi",
  },
  {
    id: "bio-188",
    title: "木質保存環境学(隔年奇数年開講 2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "大村 和香子 / OHMURA Wakako",
  },
  {
    id: "bio-189",
    title: "専門セミナー(環境)(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "梶村 恒 / KAJIMURA Hisashi",
  },
  {
    id: "bio-190",
    title: "資源生物科学専門講義 アイソトープ実験法(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "上野山 賀久 / UENOYAMA Yoshihisa",
  },
  {
    id: "bio-191",
    title: "資源生物科学専門講義 植物ゲノム利用学 (2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "佐塚 隆志 / SAZUKA Takashi",
  },
  {
    id: "bio-192",
    title: "資源生物科学専門講義生物データベース利用演習(2016以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher:
      "隅山 健太 白武 勝裕 佐藤 豊 / SUMIYAMA Kenta SHIRATAKE Katsuhiro SATO Yutaka",
  },
  {
    id: "bio-193",
    title: "専門セミナー(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "中道 範人 / NAKAMICHI Norihito",
  },
  {
    id: "bio-194",
    title: "[G30]アドバンス応用生命科学実験法及び実験",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "bio-195",
    title: "[G30]特別実験(卒業研究)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "各研究室担当教員 / Faculty in charge of each laboratory",
  },
  {
    id: "bio-196",
    title: "農林行政論1",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "小林 勝利 / KOBAYASHI Katsutoshi",
  },
  {
    id: "bio-197",
    title: "農林行政論2",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "小林 勝利 / KOBAYASHI Katsutoshi",
  },
  {
    id: "bio-198",
    title: "特許法",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "鬼頭 雅弘 / KITO Masahiro",
  },
  {
    id: "bio-199",
    title: "食品工学",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher:
      "井上 孝司 森 大輔 石川 篤志 小関 誠 / INOUE Takashi MORI Daisuke ISHIKAWA Atsushi OZEKI Makoto",
  },
  {
    id: "bio-200",
    title: "農学部特別講義 バイオベンチャーとイノベーション",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher:
      "河野 廉 矢野 貴大 上原 雅行 / KAWANO Yasushi YANO Takahiro UEHARA Masayuki",
  },
  {
    id: "bio-201",
    title: "農学部特別講義 農業農村工学",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "西村 伸一 / NISHIMURA Shinichi",
  },
  {
    id: "bio-202",
    title: "森林資源管理学2",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "松本 武 / MATSUMOTO Takeshi",
  },
  {
    id: "bio-203",
    title: "木質保存環境学",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "大村 和香子 / OHMURA Wakako",
  },
  {
    id: "bio-204",
    title: "専門セミナー(環境)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "梶村 恒 / KAJIMURA Hisashi",
  },
  {
    id: "bio-205",
    title: "海外学生受入研修",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "三屋 史朗 / MITSUYA Shiro",
  },
  {
    id: "bio-206",
    title: "資源生物科学専門講義 植物ゲノム利用学",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "佐塚 隆志 / SAZUKA Takashi",
  },
  {
    id: "bio-207",
    title: "資源生物科学専門講義 アイソトープ実験法",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "上野山 賀久 / UENOYAMA Yoshihisa",
  },
  {
    id: "bio-208",
    title: "専門セミナー(資生)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "一柳 健司 / ICHIYANAGI Kenji",
  },
  {
    id: "bio-209",
    title: "専門セミナー(生命)",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "中道 範人 / NAKAMICHI Norihito",
  },
  {
    id: "bio-210",
    title: "職業指導",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "小谷 亜由美 / KOTANI Ayumi",
  },
  {
    id: "bio-211",
    title: "農学部特別講義 食文化論 奇数年開講(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋集中",
    teacher: "Peter Matthews 上野山 賀久 / Peter Matthews UENOYAMA Yoshihisa",
  },
  {
    id: "bio-212",
    title: "卒業論文(環境)(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋集中",
    teacher: "梶村 恒 / KAJIMURA Hisashi",
  },
  {
    id: "bio-213",
    title: "海外実地研修(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋集中",
    teacher: "三屋 史朗 / MITSUYA Shiro",
  },
  {
    id: "bio-214",
    title: "資源生物科学専門講義 国際農学演習 (2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋集中",
    teacher: "三屋 史朗 / MITSUYA Shiro",
  },
  {
    id: "bio-215",
    title: "卒業論文(生命)(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "秋集中",
    teacher: "中道 範人 / NAKAMICHI Norihito",
  },
  {
    id: "bio-216",
    title: "[G30]専門セミナー",
    section: "専門",
    department: "農",
    semester: "秋集中",
    teacher: "中道 範人 / NAKAMICHI Norihito",
  },
  {
    id: "bio-217",
    title: "農学部特別講義 食文化論",
    section: "専門",
    department: "農",
    semester: "秋集中",
    teacher: "Peter Matthews 上野山 賀久 / Peter Matthews UENOYAMA Yoshihisa",
  },
  {
    id: "bio-218",
    title: "卒業論文研究(環境)",
    section: "専門",
    department: "農",
    semester: "秋集中",
    teacher: "各研究室担当教員 / Faculty in charge of each laboratory",
  },
  {
    id: "bio-219",
    title: "海外実地研修",
    section: "専門",
    department: "農",
    semester: "秋集中",
    teacher: "三屋 史朗 / MITSUYA Shiro",
  },
  {
    id: "bio-220",
    title: "資源生物科学専門講義 国際農学演習",
    section: "専門",
    department: "農",
    semester: "秋集中",
    teacher: "三屋 史朗 / MITSUYA Shiro",
  },
  {
    id: "bio-221",
    title: "卒業論文研究(資生)",
    section: "専門",
    department: "農",
    semester: "秋集中",
    teacher:
      "一柳 健司 各研究室担当教員 / ICHIYANAGI Kenji Faculty in charge of each laboratory",
  },
  {
    id: "bio-222",
    title: "卒業論文研究(生命)",
    section: "専門",
    department: "農",
    semester: "秋集中",
    teacher:
      "中道 範人 各研究室担当教員 / NAKAMICHI Norihito Faculty in charge of each laboratory",
  },
  {
    id: "bio-223",
    title: "[G30]海外専門セミナー",
    section: "専門",
    department: "農",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 石黒 澄衞 井上 直子 / ISHIGURO Sumie INOUE Naoko",
  },
  {
    id: "bio-224",
    title: "海外専門セミナー",
    section: "専門",
    department: "農",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 石黒 澄衞 井上 直子 / ISHIGURO Sumie INOUE Naoko",
  },
  {
    id: "bio-225",
    title: "国内実地研修",
    section: "専門",
    department: "農",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 一柳 健司 伊藤 智和 / ICHIYANAGI Kenji ITO Tomokazu",
  },
  {
    id: "bio-226",
    title: "資源生物科学基盤実験実習(3年生用)",
    section: "専門",
    department: "農",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 石川 明 / ISHIKAWA Akira",
  },
  {
    id: "bio-227",
    title: "生物環境科学基盤実験実習(2016年度以前入学)",
    section: "専門",
    department: "農",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "bio-228",
    title: "農学部特別講義 国際開発論",
    section: "専門",
    department: "農",
    semester: "春集中",
    teacher: "伊藤 香純 / ITO Kasumi",
  },
];
