import { Course } from "../courses";
export const BIO_B_COURSES: Course[] = [
  {
    id: "bio_b-1",
    title: "[遠隔]生命系物理工学",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "土川 覚 稲垣 哲也 / TSUCHIKAWA Satoru INAGAKI Tetsuya",
  },
  {
    id: "bio_b-2",
    title: "遺伝学(環境・資生)(2016年度以前入学)",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "一柳 健司 隅山 健太 石川 明 髙橋 宏和 / ICHIYANAGI Kenji SUMIYAMA Kenta ISHIKAWA Akira TAKAHASHI Hirokazu",
  },
  {
    id: "bio_b-3",
    title: "[G30]生化学2",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "bio_b-4",
    title: "遺伝学(環境・資生)",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "一柳 健司 隅山 健太 石川 明 髙橋 宏和 / ICHIYANAGI Kenji SUMIYAMA Kenta ISHIKAWA Akira TAKAHASHI Hirokazu",
  },
  {
    id: "bio_b-5",
    title: "有機化学2(生命)",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "北 将樹 横島 聡 / KITA Masaki YOKOSHIMA Satoshi",
  },
  {
    id: "bio_b-6",
    title: "バイオマス科学1",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "福島 和彦 今井 貴規 / FUKUSHIMA Kazuhiko IMAI Takanori",
  },
  {
    id: "bio_b-7",
    title: "生物材料組織学",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "吉田 正人 山本 浩之 / YOSHIDA Masato YAMAMOTO Hiroyuki",
  },
  {
    id: "bio_b-8",
    title: "無機化学1",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "bio_b-9",
    title: "生物化学2",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Tue-1",
    teacher:
      "西島 謙一 村井 篤嗣 新美 友章 / NISHIJIMA Kenichi MURAI Atsushi NIIMI Tomoaki",
  },
  {
    id: "bio_b-10",
    title: "遺伝学(生命)(2016年度以前入学)",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "武田 真 芦苅 基行 土井 一行 / TAKEDA Shin ASHIKARI Motoyuki DOI Kazuyuki",
  },
  {
    id: "bio_b-11",
    title: "電磁気学",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "bio_b-12",
    title: "遺伝学(生命)",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "武田 真 芦苅 基行 土井 一行 / TAKEDA Shin ASHIKARI Motoyuki DOI Kazuyuki",
  },
  {
    id: "bio_b-13",
    title: "有機化学2(環境・資生)",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "今井 貴規 水口 智江可 / IMAI Takanori MINAKUCHI Chieka",
  },
  {
    id: "bio_b-14",
    title: "生態学",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "土岐 和多瑠 / TOKI Wataru",
  },
  {
    id: "bio_b-15",
    title: "分類・形態学(2016年度以前入学)",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "山本 直之 本道 栄一 矢野 勝也 竹本 大吾 / YAMAMOTO Naoyuki HONDO Eiichi YANO Katsuya TAKEMOTO Daigo",
  },
  {
    id: "bio_b-16",
    title: "分類・形態学",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "山本 直之 本道 栄一 矢野 勝也 竹本 大吾 / YAMAMOTO Naoyuki HONDO Eiichi YANO Katsuya TAKEMOTO Daigo",
  },
  {
    id: "bio_b-17",
    title: "生命物理化学1",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "bio_b-18",
    title: "現代社会の食と農",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "徳田 博美 / TOKUDA Hiromi",
  },
  {
    id: "bio_b-19",
    title: "動物生理学1",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Wed-3",
    teacher:
      "吉村 崇 阿部 秀樹 大川 妙子 中山 友哉 / YOSHIMURA Takashi ABE Hideki OHKAWA Taeko NAKAYAMA Tomoya",
  },
  {
    id: "bio_b-20",
    title: "量子力学1",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "重森 正樹 / SHIGEMORI Masaki",
  },
  {
    id: "bio_b-21",
    title: "[G30]数学演習2a",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "BOURNE Christopher jack",
  },
  {
    id: "bio_b-22",
    title: "[G30]数学演習2b",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "BACHMANN Henrik lennart",
  },
  {
    id: "bio_b-23",
    title: "[G30]物理学基礎演習1b",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Thu-5",
    teacher: "梅畑 豪紀 / UMEHATA Hideki",
  },
  {
    id: "bio_b-24",
    title: "地球環境科学",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "HUMBLET Marc Andre",
  },
  {
    id: "bio_b-25",
    title: "生命農学序説(2016年度以前入学)",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "石黒 澄衞 / ISHIGURO Sumie",
  },
  {
    id: "bio_b-26",
    title: "生命農学序説",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "石黒 澄衞 / ISHIGURO Sumie",
  },
  {
    id: "bio_b-27",
    title: "[G30]物理学基礎演習2",
    section: "専門基礎",
    department: "農",
    semester: "春1",
    cellKey: "Fri-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "bio_b-28",
    title: "細胞生物学1(2016年度以前入学)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher:
      "谷口 光隆 一柳 健司 白武 勝裕 / TANIGUCHI Mitsutaka ICHIYANAGI Kenji SHIRATAKE Katsuhiro",
  },
  {
    id: "bio_b-29",
    title: "[G30]生化学1",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "bio_b-30",
    title: "分子細胞生物学1(環境・資生)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher:
      "谷口 光隆 一柳 健司 白武 勝裕 / TANIGUCHI Mitsutaka ICHIYANAGI Kenji SHIRATAKE Katsuhiro",
  },
  {
    id: "bio_b-31",
    title: "分子細胞生物学1(生命)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "柴田 秀樹 灘野 大太 / SHIBATA Hideki NADANO Daita",
  },
  {
    id: "bio_b-32",
    title: "生物化学3",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "榊原 均 石黒 澄衞 / SAKAKIBARA Hitoshi ISHIGURO Sumie",
  },
  {
    id: "bio_b-33",
    title: "[G30]細胞学2",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "野間 健太郎 / NOMA Kentaro",
  },
  {
    id: "bio_b-34",
    title: "植物生理学2",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher:
      "辻 寛之 山内 卓樹 西内 俊策 / TSUJI Hiroyuki YAMAUCHI Takaki NISHIUCHI Shunsaku",
  },
  {
    id: "bio_b-35",
    title: "[G30]統計物理学1",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "bio_b-36",
    title: "昆虫科学1",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher:
      "水口 智江可 池田 素子 三高 雄希 浜島 りな / MINAKUCHI Chieka IKEDA Motoko MITAKA Yuki HAMAJIMA Rina",
  },
  {
    id: "bio_b-37",
    title: "[G30]分析化学",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "bio_b-38",
    title: "生物材料力学",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "bio_b-39",
    title: "植物生理学1(環境・資生)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "谷口 光隆 三屋 史朗 / TANIGUCHI Mitsutaka MITSUYA Shiro",
  },
  {
    id: "bio_b-40",
    title: "植物生理学1(生命)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "藤田 祐一 上口 智治 中道 範人 / FUJITA Yuichi UEGUCHI Chiharu NAKAMICHI Norihito",
  },
  {
    id: "bio_b-41",
    title: "[G30]数学演習1a",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "RICHARD Serge charles",
  },
  {
    id: "bio_b-42",
    title: "[G30]数学演習1b",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "BACHMANN Henrik lennart",
  },
  {
    id: "bio_b-43",
    title: "動物形態学",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "本道 栄一 山本 直之 / HONDO Eiichi YAMAMOTO Naoyuki",
  },
  {
    id: "bio_b-44",
    title: "[G30]数理物理学演習1",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "WOJDYLO John Andrew 井黒 就平 / WOJDYLO John Andrew IGURO Shuhei",
  },
  {
    id: "bio_b-45",
    title: "[G30]数理物理学1",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Tue-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "bio_b-46",
    title: "基礎有機化学(環境・資生)(2016年度以前入学)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "青木 弾 今井 貴規 / AOKI Dan IMAI Takanori",
  },
  {
    id: "bio_b-47",
    title: "基礎有機化学(生命)(2016年度以前入学)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "野村 信嘉 西川 俊夫 / NOMURA Nobuyoshi NISHIKAWA Toshio",
  },
  {
    id: "bio_b-48",
    title: "有機化学1(環境・資生)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "青木 弾 今井 貴規 / AOKI Dan IMAI Takanori",
  },
  {
    id: "bio_b-49",
    title: "有機化学1(生命)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "野村 信嘉 西川 俊夫 / NOMURA Nobuyoshi NISHIKAWA Toshio",
  },
  {
    id: "bio_b-50",
    title: "有機化学3",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "西川 俊夫 横島 聡 / NISHIKAWA Toshio YOKOSHIMA Satoshi",
  },
  {
    id: "bio_b-51",
    title: "生命と技術の倫理",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher:
      "大蔵 聡 石黒 澄衞 河野 廉 原田 一宏 石川 明 三浦 聡 梶村 恒 / OHKURA Satoshi ISHIGURO Sumie KAWANO Yasushi HARADA Kazuhiro ISHIKAWA Akira MIURA Satoshi KAJIMURA Hisashi",
  },
  {
    id: "bio_b-52",
    title: "[G30]物理化学1",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "PHUNG Quan manh",
  },
  {
    id: "bio_b-53",
    title: "土壌学",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher:
      "渡邉 彰 村瀬 潤 浅川 晋 / WATANABE Akira MURASE Jun ASAKAWA Susumu",
  },
  {
    id: "bio_b-54",
    title: "微生物学1(環境・資生)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "池田 素子 竹本 大吾 / IKEDA Motoko TAKEMOTO Daigo",
  },
  {
    id: "bio_b-55",
    title: "微生物学1(生命)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "木村 眞 / KIMURA Makoto",
  },
  {
    id: "bio_b-56",
    title: "細胞学1",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "野間 健太郎 / NOMA Kentaro",
  },
  {
    id: "bio_b-57",
    title: "[G30]物理学基礎演習1a",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "ESCRIVA MANAS Alberto",
  },
  {
    id: "bio_b-58",
    title: "生物圏環境学1",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher:
      "五味 高志 渡邉 彰 小谷 亜由美 / GOMI Takashi WATANABE Akira KOTANI Ayumi",
  },
  {
    id: "bio_b-59",
    title: "[G30]有機化学1",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "bio_b-60",
    title: "[G30]解析力学1",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Thu-5",
    teacher: "重森 正樹 / SHIGEMORI Masaki",
  },
  {
    id: "bio_b-61",
    title: "無機化学(2016年度以前入学)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "渡邉 彰 中西 洋一 / WATANABE Akira NAKANISHI Yoichi",
  },
  {
    id: "bio_b-62",
    title: "[G30]地球惑星科学",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "HUMBLET Marc Andre",
  },
  {
    id: "bio_b-63",
    title: "無機化学",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "渡邉 彰 中西 洋一 / WATANABE Akira NAKANISHI Yoichi",
  },
  {
    id: "bio_b-64",
    title: "生物化学1(環境・資生)(2016年度以前入学)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "西島 謙一 佐藤 育男 / NISHIJIMA Kenichi SATO Ikuo",
  },
  {
    id: "bio_b-65",
    title: "生物化学1(生命)(2016年度以前入学)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "佐藤 ちひろ 灘野 大太 / SATO Chihiro NADANO Daita",
  },
  {
    id: "bio_b-66",
    title: "生物化学1(環境・資生)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "西島 謙一 佐藤 育男 / NISHIJIMA Kenichi SATO Ikuo",
  },
  {
    id: "bio_b-67",
    title: "生物化学1(生命)",
    section: "専門基礎",
    department: "農",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "佐藤 ちひろ 灘野 大太 / SATO Chihiro NADANO Daita",
  },
];
