import { Course } from "../courses";
export const BIO_B_COURSES: Course[] = [
  {
    id: "info-1",
    title: "[遠隔]生命系物理工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "土川 覚 稲垣 哲也 / TSUCHIKAWA Satoru INAGAKI Tetsuya",
  },
  {
    id: "info-2",
    title: "遺伝学(環境・資生)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "一柳 健司 隅山 健太 石川 明 髙橋 宏和 / ICHIYANAGI Kenji SUMIYAMA Kenta ISHIKAWA Akira TAKAHASHI Hirokazu",
  },
  {
    id: "info-3",
    title: "[G30]生化学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "info-4",
    title: "遺伝学(環境・資生)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "一柳 健司 隅山 健太 石川 明 髙橋 宏和 / ICHIYANAGI Kenji SUMIYAMA Kenta ISHIKAWA Akira TAKAHASHI Hirokazu",
  },
  {
    id: "info-5",
    title: "有機化学2(生命)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "北 将樹 横島 聡 / KITA Masaki YOKOSHIMA Satoshi",
  },
  {
    id: "info-6",
    title: "バイオマス科学1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "福島 和彦 今井 貴規 / FUKUSHIMA Kazuhiko IMAI Takanori",
  },
  {
    id: "info-7",
    title: "生物材料組織学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "吉田 正人 山本 浩之 / YOSHIDA Masato YAMAMOTO Hiroyuki",
  },
  {
    id: "info-8",
    title: "無機化学1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "info-9",
    title: "生物化学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher:
      "西島 謙一 村井 篤嗣 新美 友章 / NISHIJIMA Kenichi MURAI Atsushi NIIMI Tomoaki",
  },
  {
    id: "info-10",
    title: "遺伝学(生命)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "武田 真 芦苅 基行 土井 一行 / TAKEDA Shin ASHIKARI Motoyuki DOI Kazuyuki",
  },
  {
    id: "info-11",
    title: "電磁気学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "info-12",
    title: "遺伝学(生命)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "武田 真 芦苅 基行 土井 一行 / TAKEDA Shin ASHIKARI Motoyuki DOI Kazuyuki",
  },
  {
    id: "info-13",
    title: "有機化学2(環境・資生)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "今井 貴規 水口 智江可 / IMAI Takanori MINAKUCHI Chieka",
  },
  {
    id: "info-14",
    title: "生態学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "土岐 和多瑠 / TOKI Wataru",
  },
  {
    id: "info-15",
    title: "分類・形態学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "山本 直之 本道 栄一 矢野 勝也 竹本 大吾 / YAMAMOTO Naoyuki HONDO Eiichi YANO Katsuya TAKEMOTO Daigo",
  },
  {
    id: "info-16",
    title: "分類・形態学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "山本 直之 本道 栄一 矢野 勝也 竹本 大吾 / YAMAMOTO Naoyuki HONDO Eiichi YANO Katsuya TAKEMOTO Daigo",
  },
  {
    id: "info-17",
    title: "生命物理化学1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "info-18",
    title: "現代社会の食と農",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "徳田 博美 / TOKUDA Hiromi",
  },
  {
    id: "info-19",
    title: "動物生理学1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-3",
    teacher:
      "吉村 崇 阿部 秀樹 大川 妙子 中山 友哉 / YOSHIMURA Takashi ABE Hideki OHKAWA Taeko NAKAYAMA Tomoya",
  },
  {
    id: "info-20",
    title: "量子力学1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "重森 正樹 / SHIGEMORI Masaki",
  },
  {
    id: "info-21",
    title: "[G30]数学演習2a",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "BOURNE Christopher jack",
  },
  {
    id: "info-22",
    title: "[G30]数学演習2b",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "BACHMANN Henrik lennart",
  },
  {
    id: "info-23",
    title: "[G30]物理学基礎演習1b",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-5",
    teacher: "梅畑 豪紀 / UMEHATA Hideki",
  },
  {
    id: "info-24",
    title: "地球環境科学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "HUMBLET Marc Andre",
  },
  {
    id: "info-25",
    title: "生命農学序説(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "石黒 澄衞 / ISHIGURO Sumie",
  },
  {
    id: "info-26",
    title: "生命農学序説",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "石黒 澄衞 / ISHIGURO Sumie",
  },
  {
    id: "info-27",
    title: "[G30]物理学基礎演習2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "info-28",
    title: "細胞生物学1(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher:
      "谷口 光隆 一柳 健司 白武 勝裕 / TANIGUCHI Mitsutaka ICHIYANAGI Kenji SHIRATAKE Katsuhiro",
  },
  {
    id: "info-29",
    title: "[G30]生化学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "info-30",
    title: "分子細胞生物学1(環境・資生)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher:
      "谷口 光隆 一柳 健司 白武 勝裕 / TANIGUCHI Mitsutaka ICHIYANAGI Kenji SHIRATAKE Katsuhiro",
  },
  {
    id: "info-31",
    title: "分子細胞生物学1(生命)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "柴田 秀樹 灘野 大太 / SHIBATA Hideki NADANO Daita",
  },
  {
    id: "info-32",
    title: "生物化学3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "榊原 均 石黒 澄衞 / SAKAKIBARA Hitoshi ISHIGURO Sumie",
  },
  {
    id: "info-33",
    title: "[G30]細胞学2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "野間 健太郎 / NOMA Kentaro",
  },
  {
    id: "info-34",
    title: "植物生理学2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher:
      "辻 寛之 山内 卓樹 西内 俊策 / TSUJI Hiroyuki YAMAUCHI Takaki NISHIUCHI Shunsaku",
  },
  {
    id: "info-35",
    title: "[G30]統計物理学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "info-36",
    title: "昆虫科学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher:
      "水口 智江可 池田 素子 三高 雄希 浜島 りな / MINAKUCHI Chieka IKEDA Motoko MITAKA Yuki HAMAJIMA Rina",
  },
  {
    id: "info-37",
    title: "[G30]分析化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "info-38",
    title: "生物材料力学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "info-39",
    title: "植物生理学1(環境・資生)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "谷口 光隆 三屋 史朗 / TANIGUCHI Mitsutaka MITSUYA Shiro",
  },
  {
    id: "info-40",
    title: "植物生理学1(生命)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "藤田 祐一 上口 智治 中道 範人 / FUJITA Yuichi UEGUCHI Chiharu NAKAMICHI Norihito",
  },
  {
    id: "info-41",
    title: "[G30]数学演習1a",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "RICHARD Serge charles",
  },
  {
    id: "info-42",
    title: "[G30]数学演習1b",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "BACHMANN Henrik lennart",
  },
  {
    id: "info-43",
    title: "動物形態学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "本道 栄一 山本 直之 / HONDO Eiichi YAMAMOTO Naoyuki",
  },
  {
    id: "info-44",
    title: "[G30]数理物理学演習1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "WOJDYLO John Andrew 井黒 就平 / WOJDYLO John Andrew IGURO Shuhei",
  },
  {
    id: "info-45",
    title: "[G30]数理物理学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "info-46",
    title: "基礎有機化学(環境・資生)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "青木 弾 今井 貴規 / AOKI Dan IMAI Takanori",
  },
  {
    id: "info-47",
    title: "基礎有機化学(生命)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "野村 信嘉 西川 俊夫 / NOMURA Nobuyoshi NISHIKAWA Toshio",
  },
  {
    id: "info-48",
    title: "有機化学1(環境・資生)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "青木 弾 今井 貴規 / AOKI Dan IMAI Takanori",
  },
  {
    id: "info-49",
    title: "有機化学1(生命)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "野村 信嘉 西川 俊夫 / NOMURA Nobuyoshi NISHIKAWA Toshio",
  },
  {
    id: "info-50",
    title: "有機化学3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "西川 俊夫 横島 聡 / NISHIKAWA Toshio YOKOSHIMA Satoshi",
  },
  {
    id: "info-51",
    title: "生命と技術の倫理",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher:
      "大蔵 聡 石黒 澄衞 河野 廉 原田 一宏 石川 明 三浦 聡 梶村 恒 / OHKURA Satoshi ISHIGURO Sumie KAWANO Yasushi HARADA Kazuhiro ISHIKAWA Akira MIURA Satoshi KAJIMURA Hisashi",
  },
  {
    id: "info-52",
    title: "[G30]物理化学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "PHUNG Quan manh",
  },
  {
    id: "info-53",
    title: "土壌学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher:
      "渡邉 彰 村瀬 潤 浅川 晋 / WATANABE Akira MURASE Jun ASAKAWA Susumu",
  },
  {
    id: "info-54",
    title: "微生物学1(環境・資生)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "池田 素子 竹本 大吾 / IKEDA Motoko TAKEMOTO Daigo",
  },
  {
    id: "info-55",
    title: "微生物学1(生命)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "木村 眞 / KIMURA Makoto",
  },
  {
    id: "info-56",
    title: "細胞学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "野間 健太郎 / NOMA Kentaro",
  },
  {
    id: "info-57",
    title: "[G30]物理学基礎演習1a",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "ESCRIVA MANAS Alberto",
  },
  {
    id: "info-58",
    title: "生物圏環境学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher:
      "五味 高志 渡邉 彰 小谷 亜由美 / GOMI Takashi WATANABE Akira KOTANI Ayumi",
  },
  {
    id: "info-59",
    title: "[G30]有機化学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "info-60",
    title: "[G30]解析力学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-5",
    teacher: "重森 正樹 / SHIGEMORI Masaki",
  },
  {
    id: "info-61",
    title: "無機化学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "渡邉 彰 中西 洋一 / WATANABE Akira NAKANISHI Yoichi",
  },
  {
    id: "info-62",
    title: "[G30]地球惑星科学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "HUMBLET Marc Andre",
  },
  {
    id: "info-63",
    title: "無機化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "渡邉 彰 中西 洋一 / WATANABE Akira NAKANISHI Yoichi",
  },
  {
    id: "info-64",
    title: "生物化学1(環境・資生)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "西島 謙一 佐藤 育男 / NISHIJIMA Kenichi SATO Ikuo",
  },
  {
    id: "info-65",
    title: "生物化学1(生命)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "佐藤 ちひろ 灘野 大太 / SATO Chihiro NADANO Daita",
  },
  {
    id: "info-66",
    title: "生物化学1(環境・資生)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "西島 謙一 佐藤 育男 / NISHIJIMA Kenichi SATO Ikuo",
  },
  {
    id: "info-67",
    title: "生物化学1(生命)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "佐藤 ちひろ 灘野 大太 / SATO Chihiro NADANO Daita",
  },
];
