import { Course } from "../courses";
export const BIO_COURSES: Course[] = [
  {
    id: "info-2",
    title: "生物情報計測学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "土川 覚 稲垣 哲也 / TSUCHIKAWA Satoru INAGAKI Tetsuya",
  },
  {
    id: "info-3",
    title: "木質環境学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "info-4",
    title: "栄養科学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "中島 健一朗 / NAKAJIMA Ken-ichiro",
  },
  {
    id: "info-5",
    title: "木質環境学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "info-6",
    title: "栄養科学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "中島 健一朗 / NAKAJIMA Ken-ichiro",
  },
  {
    id: "info-7",
    title: "有機化学1(生命)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "北 将樹 横島 聡 / KITA Masaki YOKOSHIMA Satoshi",
  },
  {
    id: "info-8",
    title: "森林保護学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "梶村 恒 / KAJIMURA Hisashi",
  },
  {
    id: "info-9",
    title: "生産土壌学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "浅川 晋 村瀬 潤 近藤 始彦 / ASAKAWA Susumu MURASE Jun KONDO Motohiko",
  },
  {
    id: "info-10",
    title: "食品機能化学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "柴田 貴広 / SHIBATA Takahiro",
  },
  {
    id: "info-11",
    title: "[G30]生物有機化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "西川 俊夫 北 将樹 青井 啓悟 中川 優 / NISHIKAWA Toshio KITA Masaki AOI Keigo NAKAGAWA Yu",
  },
  {
    id: "info-12",
    title: "森林保護学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "梶村 恒 / KAJIMURA Hisashi",
  },
  {
    id: "info-13",
    title: "生産土壌学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "浅川 晋 村瀬 潤 近藤 始彦 / ASAKAWA Susumu MURASE Jun KONDO Motohiko",
  },
  {
    id: "info-14",
    title: "食品機能化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "柴田 貴広 / SHIBATA Takahiro",
  },
  {
    id: "info-15",
    title: "バイオマス科学1(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "福島 和彦 今井 貴規 / FUKUSHIMA Kazuhiko IMAI Takanori",
  },
  {
    id: "info-16",
    title: "生物環境科学実験実習(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "谷川 東子 / TANIKAWA Toko",
  },
  {
    id: "info-17",
    title: "応用生命科学実験実習1(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "info-18",
    title: "特別実験(卒業研究)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher:
      "中道 範人 各研究室担当教員 / NAKAMICHI Norihito Faculty in charge of each laboratory",
  },
  {
    id: "info-19",
    title: "[G30]農学部応用生命科学実験1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "info-20",
    title: "生物環境科学実験実習1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "谷川 東子 / TANIKAWA Toko",
  },
  {
    id: "info-21",
    title: "資源生物科学基盤実験実習",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "石川 明 / ISHIKAWA Akira",
  },
  {
    id: "info-22",
    title: "応用生命科学実験実習1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "info-23",
    title: "生物材料組織学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "吉田 正人 山本 浩之 / YOSHIDA Masato YAMAMOTO Hiroyuki",
  },
  {
    id: "info-24",
    title: "生物化学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher:
      "西島 謙一 村井 篤嗣 新美 友章 / NISHIJIMA Kenichi MURAI Atsushi NIIMI Tomoaki",
  },
  {
    id: "info-25",
    title: "生物有機化学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "西川 俊夫 / NISHIKAWA Toshio",
  },
  {
    id: "info-26",
    title: "[G30]先端有機・高分子化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "村井 征史 / MURAI Masahito",
  },
  {
    id: "info-27",
    title: "有機化学4",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "西川 俊夫 / NISHIKAWA Toshio",
  },
  {
    id: "info-28",
    title: "有機化学1(環境・資生)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "今井 貴規 水口 智江可 / IMAI Takanori MINAKUCHI Chieka",
  },
  {
    id: "info-29",
    title: "生体分子化学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "青井 啓悟 北 将樹 / AOI Keigo KITA Masaki",
  },
  {
    id: "info-30",
    title: "生態遺伝学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "戸丸 信弘 / TOMARU Nobuhiro",
  },
  {
    id: "info-31",
    title: "[G30]微生物学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "木村 眞 邊見 久 COROVIC Jasmina / KIMURA Makoto HEMMI Hisashi COROVIC Jasmina",
  },
  {
    id: "info-32",
    title: "保全遺伝学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "戸丸 信弘 / TOMARU Nobuhiro",
  },
  {
    id: "info-33",
    title: "生命分子化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "青井 啓悟 北 将樹 / AOI Keigo KITA Masaki",
  },
  {
    id: "info-34",
    title: "生態学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "土岐 和多瑠 / TOKI Wataru",
  },
  {
    id: "info-35",
    title: "資源生物科学実験実習(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "石川 明 / ISHIKAWA Akira",
  },
  {
    id: "info-36",
    title: "資源生物科学実験実習1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "石川 明 / ISHIKAWA Akira",
  },
  {
    id: "info-37",
    title: "生命物理化学1(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "info-38",
    title: "生物環境計測学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "山本 一清 / YAMAMOTO Kazukiyo",
  },
  {
    id: "info-39",
    title: "高分子化学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "青井 啓悟 野村 信嘉 / AOI Keigo NOMURA Nobuyoshi",
  },
  {
    id: "info-40",
    title: "遺伝学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "info-41",
    title: "生物物理学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "Florence Tama",
  },
  {
    id: "info-42",
    title: "生物環境計測学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "山本 一清 / YAMAMOTO Kazukiyo",
  },
  {
    id: "info-43",
    title: "高分子化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "青井 啓悟 野村 信嘉 / AOI Keigo NOMURA Nobuyoshi",
  },
  {
    id: "info-44",
    title: "食品衛生学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "柴田 貴広 大島 健司 / SHIBATA Takahiro OSHIMA Kenji",
  },
  {
    id: "info-45",
    title: "食と農の経済学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "徳田 博美 / TOKUDA Hiromi",
  },
  {
    id: "info-46",
    title: "森林生態学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "中川 弥智子 / NAKAGAWA Michiko",
  },
  {
    id: "info-47",
    title: "生物反応工学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "中野 秀雄 加藤 晃代 / NAKANO Hideo KATO Teruyo",
  },
  {
    id: "info-48",
    title: "[G30]植物生理学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher:
      "中道 範人 村中 智明 BELLEGARDE Fanny 前田 真一 / NAKAMICHI Norihito MURANAKA Tomoaki BELLEGARDE Fanny MAEDA Shin ichi",
  },
  {
    id: "info-49",
    title: "[G30]有機化学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "info-50",
    title: "森林生態学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "中川 弥智子 / NAKAGAWA Michiko",
  },
  {
    id: "info-51",
    title: "生物反応工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "中野 秀雄 加藤 晃代 / NAKANO Hideo KATO Teruyo",
  },
  {
    id: "info-52",
    title: "食品衛生学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "柴田 貴広 大島 健司 / SHIBATA Takahiro OSHIMA Kenji",
  },
  {
    id: "info-53",
    title: "動物生理学1(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-3",
    teacher:
      "吉村 崇 阿部 秀樹 大川 妙子 中山 友哉 / YOSHIMURA Takashi ABE Hideki OHKAWA Taeko NAKAYAMA Tomoya",
  },
  {
    id: "info-54",
    title: "資源生物科学セミナー(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher: "山縣 高宏 / YAMAGATA Takahiro",
  },
  {
    id: "info-55",
    title: "農学セミナー1(環境)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "今井 貴規 小谷 亜由美 / IMAI Takanori KOTANI Ayumi",
  },
  {
    id: "info-56",
    title: "農学セミナー1(資生)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "山縣 高宏 / YAMAGATA Takahiro",
  },
  {
    id: "info-57",
    title: "農学セミナー1(生命)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "中道 範人 / NAKAMICHI Norihito",
  },
  {
    id: "info-58",
    title: "生物圏環境学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-1",
    teacher:
      "渡邉 彰 谷川 東子 三屋 史朗 / WATANABE Akira TANIKAWA Toko MITSUYA Shiro",
  },
  {
    id: "info-59",
    title: "微生物学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "木村 眞 渡邉 健史 / KIMURA Makoto WATANABE Takeshi",
  },
  {
    id: "info-60",
    title: "生理・発生生物学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "info-61",
    title: "生物圏環境学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-1",
    teacher:
      "渡邉 彰 谷川 東子 三屋 史朗 / WATANABE Akira TANIKAWA Toko MITSUYA Shiro",
  },
  {
    id: "info-62",
    title: "微生物学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "木村 眞 渡邉 健史 / KIMURA Makoto WATANABE Takeshi",
  },
  {
    id: "info-63",
    title: "食糧生産管理学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "徳田 博美 / TOKUDA Hiromi",
  },
  {
    id: "info-64",
    title: "分子生物学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "石黒 澄衞 山篠 貴史 / ISHIGURO Sumie YAMASHINO Takafumi",
  },
  {
    id: "info-65",
    title: "[G30]生化学4",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher:
      "灘野 大太 石黒 澄衞 山篠 貴史 / NADANO Daita ISHIGURO Sumie YAMASHINO Takafumi",
  },
  {
    id: "info-66",
    title: "農業・資源経済学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "徳田 博美 / TOKUDA Hiromi",
  },
  {
    id: "info-67",
    title: "分子細胞生物学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "石黒 澄衞 山篠 貴史 / ISHIGURO Sumie YAMASHINO Takafumi",
  },
  {
    id: "info-68",
    title: "樹木生化学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "今井 貴規 福島 和彦 / IMAI Takanori FUKUSHIMA Kazuhiko",
  },
  {
    id: "info-69",
    title: "有機構造解析学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "北 将樹 恒松 雄太 / KITA Masaki TSUNEMATSU Yuta",
  },
  {
    id: "info-70",
    title: "樹木生化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "今井 貴規 福島 和彦 / IMAI Takanori FUKUSHIMA Kazuhiko",
  },
  {
    id: "info-71",
    title: "有機構造解析学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "北 将樹 恒松 雄太 / KITA Masaki TSUNEMATSU Yuta",
  },
  {
    id: "info-72",
    title: "植物機能学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "藤田 祐一 / FUJITA Yuichi",
  },
  {
    id: "info-73",
    title: "[G30]細胞学4",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "柴田 秀樹 MATURANA Andres Daniel 小田 裕昭 / SHIBATA Hideki MATURANA Andres Daniel ODA Hiroaki",
  },
  {
    id: "info-74",
    title: "木質材料物理学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "土川 覚 山本 浩之 稲垣 哲也 / TSUCHIKAWA Satoru YAMAMOTO Hiroyuki INAGAKI Tetsuya",
  },
  {
    id: "info-75",
    title: "植物機能学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "藤田 祐一 / FUJITA Yuichi",
  },
  {
    id: "info-76",
    title: "動物生理学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher:
      "山本 直之 萩尾 華子 中山 友哉 吉村 崇 村井 篤嗣 塚田 光 / YAMAMOTO Naoyuki HAGIO Hanako NAKAYAMA Tomoya YOSHIMURA Takashi MURAI Atsushi TSUKADA Akira",
  },
  {
    id: "info-77",
    title: "動物生理学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher:
      "山本 直之 萩尾 華子 中山 友哉 吉村 崇 村井 篤嗣 塚田 光 / YAMAMOTO Naoyuki HAGIO Hanako NAKAYAMA Tomoya YOSHIMURA Takashi MURAI Atsushi TSUKADA Akira",
  },
  {
    id: "info-78",
    title: "植物育種学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher:
      "中園 幹生 永井 啓祐 佐塚 隆志 髙橋 宏和 / NAKAZONO Mikio NAGAI Keisuke SAZUKA Takashi TAKAHASHI Hirokazu",
  },
  {
    id: "info-79",
    title: "植物育種学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher:
      "中園 幹生 永井 啓祐 佐塚 隆志 髙橋 宏和 / NAKAZONO Mikio NAGAI Keisuke SAZUKA Takashi TAKAHASHI Hirokazu",
  },
  {
    id: "info-80",
    title: "生体防御学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher:
      "竹本 大吾 佐藤 育男 吉岡 博文 千葉 壮太郎 / TAKEMOTO Daigo SATO Ikuo YOSHIOKA Hirofumi CHIBA Sotaro",
  },
  {
    id: "info-81",
    title: "植物病理学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher:
      "竹本 大吾 佐藤 育男 吉岡 博文 千葉 壮太郎 / TAKEMOTO Daigo SATO Ikuo YOSHIOKA Hirofumi CHIBA Sotaro",
  },
  {
    id: "info-82",
    title: "フードシステム論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "三浦 聡 / MIURA Satoshi",
  },
  {
    id: "info-83",
    title: "動物育種学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "隅山 健太 田邉 彰 石川 明 山縣 高宏 / SUMIYAMA Kenta TANABE Akira ISHIKAWA Akira YAMAGATA Takahiro",
  },
  {
    id: "info-84",
    title: "動物育種学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "隅山 健太 田邉 彰 石川 明 山縣 高宏 / SUMIYAMA Kenta TANABE Akira ISHIKAWA Akira YAMAGATA Takahiro",
  },
  {
    id: "info-85",
    title: "動物生産科学1(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Mon-1",
    teacher:
      "上野山 賀久 松山 秀一 中村 翔 井上 直子 / UENOYAMA Yoshihisa MATSUYAMA Shuichi NAKAMURA Sho INOUE Naoko",
  },
  {
    id: "info-86",
    title: "動物繁殖学",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Mon-1",
    teacher:
      "上野山 賀久 松山 秀一 中村 翔 井上 直子 / UENOYAMA Yoshihisa MATSUYAMA Shuichi NAKAMURA Sho INOUE Naoko",
  },
  {
    id: "info-87",
    title: "植物生産科学1(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Mon-3",
    teacher:
      "近藤 始彦 杉浦 大輔 矢野 勝也 / KONDO Motohiko SUGIURA Daisuke YANO Katsuya",
  },
  {
    id: "info-88",
    title: "作物科学",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Mon-3",
    teacher:
      "近藤 始彦 杉浦 大輔 矢野 勝也 / KONDO Motohiko SUGIURA Daisuke YANO Katsuya",
  },
  {
    id: "info-89",
    title: "環境倫理学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Tue-1",
    teacher: "中川 弥智子 / NAKAGAWA Michiko",
  },
  {
    id: "info-90",
    title: "国際森林資源論",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Tue-1",
    teacher: "中川 弥智子 / NAKAGAWA Michiko",
  },
  {
    id: "info-91",
    title: "細胞工学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Tue-2",
    teacher:
      "西島 謙一 隅山 健太 山内 卓樹 大川 妙子 池田 素子 佐塚 隆志 / NISHIJIMA Kenichi SUMIYAMA Kenta YAMAUCHI Takaki OHKAWA Taeko IKEDA Motoko SAZUKA Takashi",
  },
  {
    id: "info-92",
    title: "細胞工学",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Tue-2",
    teacher:
      "西島 謙一 隅山 健太 山内 卓樹 大川 妙子 池田 素子 佐塚 隆志 / NISHIJIMA Kenichi SUMIYAMA Kenta YAMAUCHI Takaki OHKAWA Taeko IKEDA Motoko SAZUKA Takashi",
  },
  {
    id: "info-93",
    title: "細胞生物学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "柴田 秀樹 灘野 大太 / SHIBATA Hideki NADANO Daita",
  },
  {
    id: "info-94",
    title: "流域保全学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "五味 高志 / GOMI Takashi",
  },
  {
    id: "info-95",
    title: "微生物学3(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "饗場 浩文 / AIBA Hirofumi",
  },
  {
    id: "info-96",
    title: "流域保全学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "五味 高志 / GOMI Takashi",
  },
  {
    id: "info-97",
    title: "分子微生物学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "饗場 浩文 / AIBA Hirofumi",
  },
  {
    id: "info-98",
    title: "生物化学3(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "榊原 均 石黒 澄衞 / SAKAKIBARA Hitoshi ISHIGURO Sumie",
  },
  {
    id: "info-99",
    title: "遺伝子工学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "武田 真 髙原 照直 / TAKEDA Shin TAKAHARA Terunao",
  },
  {
    id: "info-100",
    title: "[G30]生理・解剖学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "info-101",
    title: "遺伝子工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "武田 真 髙原 照直 / TAKEDA Shin TAKAHARA Terunao",
  },
  {
    id: "info-102",
    title: "植物生理学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher:
      "辻 寛之 山内 卓樹 西内 俊策 / TSUJI Hiroyuki YAMAUCHI Takaki NISHIUCHI Shunsaku",
  },
  {
    id: "info-103",
    title: "応用生命科学実験実習2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "info-104",
    title: "[G30]農学部応用生命科学実験2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "info-105",
    title: "生物環境科学実験実習2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "谷川 東子 / TANIKAWA Toko",
  },
  {
    id: "info-106",
    title: "応用生命科学実験実習2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "邊見 久 / HEMMI Hisashi",
  },
  {
    id: "info-107",
    title: "昆虫科学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher:
      "水口 智江可 池田 素子 三高 雄希 浜島 りな / MINAKUCHI Chieka IKEDA Motoko MITAKA Yuki HAMAJIMA Rina",
  },
  {
    id: "info-108",
    title: "生物材料力学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "info-109",
    title: "バイオマス科学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "山本 浩之 吉田 正人 / YAMAMOTO Hiroyuki YOSHIDA Masato",
  },
  {
    id: "info-110",
    title: "農業政策学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "徳田 博美 / TOKUDA Hiromi",
  },
  {
    id: "info-111",
    title: "バイオマス科学2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "山本 浩之 吉田 正人 / YAMAMOTO Hiroyuki YOSHIDA Masato",
  },
  {
    id: "info-112",
    title: "農業・農村制度論",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "徳田 博美 / TOKUDA Hiromi",
  },
  {
    id: "info-113",
    title: "分子細胞生物学3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher:
      "人見 清隆 MATURANA Andres Daniel 柴田 秀樹 / HITOMI Kiyotaka MATURANA Andres Daniel SHIBATA Hideki",
  },
  {
    id: "info-114",
    title: "植物生理学1(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "谷口 光隆 三屋 史朗 / TANIGUCHI Mitsutaka MITSUYA Shiro",
  },
  {
    id: "info-115",
    title: "植物機能学1(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "藤田 祐一 上口 智治 中道 範人 / FUJITA Yuichi UEGUCHI Chiharu NAKAMICHI Norihito",
  },
  {
    id: "info-116",
    title: "応用数学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "稲垣 哲也 山本 浩之 / INAGAKI Tetsuya YAMAMOTO Hiroyuki",
  },
  {
    id: "info-117",
    title: "生命物理化学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "邊見 久 伊藤 智和 / HEMMI Hisashi ITO Tomokazu",
  },
  {
    id: "info-118",
    title: "[G30]生理・解剖学2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "日比 正彦 / HIBI Masahiko",
  },
  {
    id: "info-119",
    title: "応用数学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "稲垣 哲也 山本 浩之 / INAGAKI Tetsuya YAMAMOTO Hiroyuki",
  },
  {
    id: "info-120",
    title: "生命物理化学2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "邊見 久 伊藤 智和 / HEMMI Hisashi ITO Tomokazu",
  },
  {
    id: "info-121",
    title: "資源生物科学実験実習2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "石川 明 / ISHIKAWA Akira",
  },
  {
    id: "info-122",
    title: "分子生物学1(環境・資生)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "一柳 健司 吉岡 博文 / ICHIYANAGI Kenji YOSHIOKA Hirofumi",
  },
  {
    id: "info-123",
    title: "分子生物学1(生命)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "山篠 貴史 中道 範人 / YAMASHINO Takafumi NAKAMICHI Norihito",
  },
  {
    id: "info-124",
    title: "環境政策学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "岩永 青史 / IWANAGA Seiji",
  },
  {
    id: "info-125",
    title: "生理活性物質化学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "中川 優 恒松 雄太 / NAKAGAWA Yu TSUNEMATSU Yuta",
  },
  {
    id: "info-126",
    title: "[G30]化学物理学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "内橋 貴之 / UCHIHASHI Takayuki",
  },
  {
    id: "info-127",
    title: "森林社会共生学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "岩永 青史 / IWANAGA Seiji",
  },
  {
    id: "info-128",
    title: "生理活性物質化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "中川 優 恒松 雄太 / NAKAGAWA Yu TSUNEMATSU Yuta",
  },
  {
    id: "info-129",
    title: "有機化学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "西川 俊夫 横島 聡 / NISHIKAWA Toshio YOKOSHIMA Satoshi",
  },
  {
    id: "info-130",
    title: "地形情報学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "山本 一清 五味 高志 戸丸 信弘 / YAMAMOTO Kazukiyo GOMI Takashi TOMARU Nobuhiro",
  },
  {
    id: "info-131",
    title: "応用植物分子科学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "藤田 祐一 上口 智治 / FUJITA Yuichi UEGUCHI Chiharu",
  },
  {
    id: "info-132",
    title: "[G30]遺伝学3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "杉山 伸 / SUGIYAMA Shin",
  },
  {
    id: "info-133",
    title: "森林資源管理学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "山本 一清 五味 高志 戸丸 信弘 / YAMAMOTO Kazukiyo GOMI Takashi TOMARU Nobuhiro",
  },
  {
    id: "info-134",
    title: "応用植物分子科学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "藤田 祐一 上口 智治 / FUJITA Yuichi UEGUCHI Chiharu",
  },
  {
    id: "info-135",
    title: "生命と技術の倫理(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher:
      "大蔵 聡 石黒 澄衞 河野 廉 原田 一宏 石川 明 三浦 聡 梶村 恒 / OHKURA Satoshi ISHIGURO Sumie KAWANO Yasushi HARADA Kazuhiro ISHIKAWA Akira MIURA Satoshi KAJIMURA Hisashi",
  },
  {
    id: "info-136",
    title: "生物統計学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher:
      "山本 一清 一柳 健司 阿部 秀樹 梶村 恒 中川 弥智子 土井 一行 岩永 青史 / YAMAMOTO Kazukiyo ICHIYANAGI Kenji ABE Hideki KAJIMURA Hisashi NAKAGAWA Michiko DOI Kazuyuki IWANAGA Seiji",
  },
  {
    id: "info-137",
    title: "生物情報処理演習(環境・資生)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher:
      "山本 一清 一柳 健司 阿部 秀樹 梶村 恒 中川 弥智子 土井 一行 岩永 青史 / YAMAMOTO Kazukiyo ICHIYANAGI Kenji ABE Hideki KAJIMURA Hisashi NAKAGAWA Michiko DOI Kazuyuki IWANAGA Seiji",
  },
  {
    id: "info-138",
    title: "農学セミナー2(生命)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "中道 範人 / NAKAMICHI Norihito",
  },
  {
    id: "info-139",
    title: "Agricultural Science(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher:
      "井上 直子 青木 弾 山内 章 谷口 光隆 束村 博子 村瀬 潤 小谷 亜由美 水口 智江可 伊藤 香純 北浦 靖之 / INOUE Naoko AOKI Dan YAMAUCHI Akira TANIGUCHI Mitsutaka TSUKAMURA Hiroko MURASE Jun KOTANI Ayumi MINAKUCHI Chieka ITO Kasumi KITAURA Yasuyuki",
  },
  {
    id: "info-140",
    title: "[G30]Agricultural Science",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher: "井上 直子 / INOUE Naoko",
  },
  {
    id: "info-141",
    title: "Agricultural Sciences",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher:
      "井上 直子 五味 高志 青木 弾 COROVIC Jasmina 谷口 光隆 村瀬 潤 水口 智江可 伊藤 香純 土井 一行 / INOUE Naoko GOMI Takashi AOKI Dan COROVIC Jasmina TANIGUCHI Mitsutaka MURASE Jun MINAKUCHI Chieka ITO Kasumi DOI Kazuyuki",
  },
  {
    id: "info-142",
    title: "農学セミナー2(環境)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher: "今井 貴規 小谷 亜由美 / IMAI Takanori KOTANI Ayumi",
  },
  {
    id: "info-143",
    title: "農学セミナー2(資生)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher: "山縣 高宏 / YAMAGATA Takahiro",
  },
  {
    id: "info-144",
    title: "土壌学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher:
      "渡邉 彰 村瀬 潤 浅川 晋 / WATANABE Akira MURASE Jun ASAKAWA Susumu",
  },
  {
    id: "info-145",
    title: "Academic Presentation Skills",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "MATURANA Andres Daniel",
  },
  {
    id: "info-146",
    title: "[G30][遠隔]計算化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "柳井 毅 / YANAI Takeshi",
  },
  {
    id: "info-147",
    title: "農学セミナー3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "MATURANA Andres Daniel",
  },
  {
    id: "info-148",
    title: "資源微生物学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "池田 素子 竹本 大吾 / IKEDA Motoko TAKEMOTO Daigo",
  },
  {
    id: "info-149",
    title: "微生物学1(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "木村 眞 / KIMURA Makoto",
  },
  {
    id: "info-150",
    title: "設計製図(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "安藤 幸世 / ANDO Kosei",
  },
  {
    id: "info-151",
    title: "微生物生態学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "渡邉 健史 浅川 晋 / WATANABE Takeshi ASAKAWA Susumu",
  },
  {
    id: "info-152",
    title: "[G30]遺伝学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "info-153",
    title: "[G30]細胞学3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "木下 専 / KINOSHITA Makoto",
  },
  {
    id: "info-154",
    title: "設計製図",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "安藤 幸世 / ANDO Kosei",
  },
  {
    id: "info-155",
    title: "微生物生態学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "渡邉 健史 浅川 晋 / WATANABE Takeshi ASAKAWA Susumu",
  },
  {
    id: "info-156",
    title: "生物圏環境学1(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher:
      "五味 高志 渡邉 彰 小谷 亜由美 / GOMI Takashi WATANABE Akira KOTANI Ayumi",
  },
  {
    id: "info-157",
    title: "バイオマス変換化学1(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher:
      "青木 弾 福島 和彦 今井 貴規 / AOKI Dan FUKUSHIMA Kazuhiko IMAI Takanori",
  },
  {
    id: "info-158",
    title: "資源生物科学基盤実験実習(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "石川 明 / ISHIKAWA Akira",
  },
  {
    id: "info-159",
    title: "バイオマス変換化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher:
      "青木 弾 福島 和彦 今井 貴規 / AOKI Dan FUKUSHIMA Kazuhiko IMAI Takanori",
  },
  {
    id: "info-160",
    title: "生物統計学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher:
      "新美 友章 橋本(杉本) 美海 山本 治樹 / NIIMI Tomoaki HASHIMOTO(SUGIMOTO) Mimi YAMAMOTO Haruki",
  },
  {
    id: "info-161",
    title: "住宅科学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "info-162",
    title: "生物情報処理演習(生命)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher:
      "新美 友章 橋本(杉本) 美海 山本 治樹 / NIIMI Tomoaki HASHIMOTO(SUGIMOTO) Mimi YAMAMOTO Haruki",
  },
  {
    id: "info-163",
    title: "住宅科学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "info-164",
    title: "高分子設計学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "野村 信嘉 青井 啓悟 / NOMURA Nobuyoshi AOI Keigo",
  },
  {
    id: "info-165",
    title: "高分子設計学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "野村 信嘉 青井 啓悟 / NOMURA Nobuyoshi AOI Keigo",
  },
  {
    id: "info-166",
    title: "細胞生物学4(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "新美 友章 大島 健司 / NIIMI Tomoaki OSHIMA Kenji",
  },
  {
    id: "info-167",
    title: "[G30]生化学3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher:
      "小嶋 誠司 打田 直行 廣田 毅 吉成 晃 / KOJIMA Seiji UCHIDA Naoyuki HIROTA Tsuyoshi YOSHINARI Akira",
  },
  {
    id: "info-168",
    title: "分子細胞生物学4",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "新美 友章 大島 健司 / NIIMI Tomoaki OSHIMA Kenji",
  },
  {
    id: "info-169",
    title: "動物生産科学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "村井 篤嗣 / MURAI Atsushi",
  },
  {
    id: "info-170",
    title: "動物栄養学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "村井 篤嗣 / MURAI Atsushi",
  },
  {
    id: "info-171",
    title: "植物生産科学2(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "白武 勝裕 / SHIRATAKE Katsuhiro",
  },
  {
    id: "info-172",
    title: "園芸科学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "白武 勝裕 / SHIRATAKE Katsuhiro",
  },
  {
    id: "info-173",
    title: "昆虫生産科学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher:
      "池田 素子 水口 智江可 三高 雄希 浜島 りな / IKEDA Motoko MINAKUCHI Chieka MITAKA Yuki HAMAJIMA Rina",
  },
  {
    id: "info-174",
    title: "昆虫科学2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher:
      "池田 素子 水口 智江可 三高 雄希 浜島 りな / IKEDA Motoko MINAKUCHI Chieka MITAKA Yuki HAMAJIMA Rina",
  },
  {
    id: "info-175",
    title: "動物生産科学3(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher:
      "大蔵 聡 松山 秀一 中村 翔 上野山 賀久 井上 直子 / OHKURA Satoshi MATSUYAMA Shuichi NAKAMURA Sho UENOYAMA Yoshihisa INOUE Naoko",
  },
  {
    id: "info-176",
    title: "動物管理衛生学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher:
      "大蔵 聡 松山 秀一 中村 翔 上野山 賀久 井上 直子 / OHKURA Satoshi MATSUYAMA Shuichi NAKAMURA Sho UENOYAMA Yoshihisa INOUE Naoko",
  },
  {
    id: "info-177",
    title: "植物保護学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "竹本 大吾 佐藤 育男 吉岡 博文 水口 智江可 三高 雄希 千葉 壮太郎 / TAKEMOTO Daigo SATO Ikuo YOSHIOKA Hirofumi MINAKUCHI Chieka MITAKA Yuki CHIBA Sotaro",
  },
  {
    id: "info-178",
    title: "植物保護学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "竹本 大吾 佐藤 育男 吉岡 博文 水口 智江可 三高 雄希 千葉 壮太郎 / TAKEMOTO Daigo SATO Ikuo YOSHIOKA Hirofumi MINAKUCHI Chieka MITAKA Yuki CHIBA Sotaro",
  },
  {
    id: "info-179",
    title: "持続的生物生産学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "秋2",
    cellKey: "Mon-1",
    teacher:
      "大蔵 聡 三浦 聡 近藤 始彦 / OHKURA Satoshi MIURA Satoshi KONDO Motohiko",
  },
  {
    id: "info-180",
    title: "持続的生物生産学",
    department: "情報",
    section: "専門",
    semester: "秋2",
    cellKey: "Mon-1",
    teacher:
      "大蔵 聡 三浦 聡 近藤 始彦 / OHKURA Satoshi MIURA Satoshi KONDO Motohiko",
  },
  {
    id: "info-181",
    title: "植物分類・植生学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 戸丸 信弘 中川 弥智子 / TOMARU Nobuhiro NAKAGAWA Michiko",
  },
  {
    id: "info-182",
    title: "特許法(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 鬼頭 雅弘 / KITO Masahiro",
  },
  {
    id: "info-183",
    title: "食品工学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 井上 孝司 森 大輔 石川 篤志 小関 誠 / INOUE Takashi MORI Daisuke ISHIKAWA Atsushi OZEKI Makoto",
  },
  {
    id: "info-184",
    title: "農学部特別講義 バイオベンチャーとイノ (2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 河野 廉 矢野 貴大 上原 雅行 / KAWANO Yasushi YANO Takahiro UEHARA Masayuki",
  },
  {
    id: "info-185",
    title: "農学部特別講義 農林行政論1 (2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 小林 勝利 / KOBAYASHI Katsutoshi",
  },
  {
    id: "info-186",
    title: "農学部特別講義 農林行政論2 (2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 小林 勝利 / KOBAYASHI Katsutoshi",
  },
  {
    id: "info-187",
    title: "農学部特別講義 農業農村工学(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 西村 伸一 / NISHIMURA Shinichi",
  },
  {
    id: "info-188",
    title: "木質保存環境学(隔年奇数年開講 2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 大村 和香子 / OHMURA Wakako",
  },
  {
    id: "info-189",
    title: "専門セミナー(環境)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 梶村 恒 / KAJIMURA Hisashi",
  },
  {
    id: "info-190",
    title: "資源生物科学専門講義 アイソトープ実験法(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 上野山 賀久 / UENOYAMA Yoshihisa",
  },
  {
    id: "info-191",
    title: "資源生物科学専門講義 植物ゲノム利用学 (2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 佐塚 隆志 / SAZUKA Takashi",
  },
  {
    id: "info-192",
    title: "資源生物科学専門講義生物データベース利用演習(2016以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 隅山 健太 白武 勝裕 佐藤 豊 / SUMIYAMA Kenta SHIRATAKE Katsuhiro SATO Yutaka",
  },
  {
    id: "info-193",
    title: "専門セミナー(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 中道 範人 / NAKAMICHI Norihito",
  },
  {
    id: "info-194",
    title: "[G30]アドバンス応用生命科学実験法及び実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 邊見 久 / HEMMI Hisashi",
  },
  {
    id: "info-195",
    title: "[G30]特別実験(卒業研究)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 各研究室担当教員 / Faculty in charge of each laboratory",
  },
  {
    id: "info-196",
    title: "農林行政論1",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 小林 勝利 / KOBAYASHI Katsutoshi",
  },
  {
    id: "info-197",
    title: "農林行政論2",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 小林 勝利 / KOBAYASHI Katsutoshi",
  },
  {
    id: "info-198",
    title: "特許法",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 鬼頭 雅弘 / KITO Masahiro",
  },
  {
    id: "info-199",
    title: "食品工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 井上 孝司 森 大輔 石川 篤志 小関 誠 / INOUE Takashi MORI Daisuke ISHIKAWA Atsushi OZEKI Makoto",
  },
  {
    id: "info-200",
    title: "農学部特別講義 バイオベンチャーとイノベーション",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 河野 廉 矢野 貴大 上原 雅行 / KAWANO Yasushi YANO Takahiro UEHARA Masayuki",
  },
  {
    id: "info-201",
    title: "農学部特別講義 農業農村工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 西村 伸一 / NISHIMURA Shinichi",
  },
  {
    id: "info-202",
    title: "森林資源管理学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 松本 武 / MATSUMOTO Takeshi",
  },
  {
    id: "info-203",
    title: "木質保存環境学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 大村 和香子 / OHMURA Wakako",
  },
  {
    id: "info-204",
    title: "専門セミナー(環境)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 梶村 恒 / KAJIMURA Hisashi",
  },
  {
    id: "info-205",
    title: "海外学生受入研修",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 三屋 史朗 / MITSUYA Shiro",
  },
  {
    id: "info-206",
    title: "資源生物科学専門講義 植物ゲノム利用学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 佐塚 隆志 / SAZUKA Takashi",
  },
  {
    id: "info-207",
    title: "資源生物科学専門講義 アイソトープ実験法",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 上野山 賀久 / UENOYAMA Yoshihisa",
  },
  {
    id: "info-208",
    title: "専門セミナー(資生)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 一柳 健司 / ICHIYANAGI Kenji",
  },
  {
    id: "info-209",
    title: "専門セミナー(生命)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 中道 範人 / NAKAMICHI Norihito",
  },
  {
    id: "info-210",
    title: "職業指導",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 小谷 亜由美 / KOTANI Ayumi",
  },
  {
    id: "info-211",
    title: "農学部特別講義 食文化論 奇数年開講(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other Peter Matthews 上野山 賀久 / Peter Matthews UENOYAMA Yoshihisa",
  },
  {
    id: "info-212",
    title: "卒業論文(環境)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 梶村 恒 / KAJIMURA Hisashi",
  },
  {
    id: "info-213",
    title: "海外実地研修(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 三屋 史朗 / MITSUYA Shiro",
  },
  {
    id: "info-214",
    title: "資源生物科学専門講義 国際農学演習 (2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 三屋 史朗 / MITSUYA Shiro",
  },
  {
    id: "info-215",
    title: "卒業論文(生命)(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 中道 範人 / NAKAMICHI Norihito",
  },
  {
    id: "info-216",
    title: "[G30]専門セミナー",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 中道 範人 / NAKAMICHI Norihito",
  },
  {
    id: "info-217",
    title: "農学部特別講義 食文化論",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other Peter Matthews 上野山 賀久 / Peter Matthews UENOYAMA Yoshihisa",
  },
  {
    id: "info-218",
    title: "卒業論文研究(環境)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other 各研究室担当教員 / Faculty in charge of each laboratory",
  },
  {
    id: "info-219",
    title: "海外実地研修",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 三屋 史朗 / MITSUYA Shiro",
  },
  {
    id: "info-220",
    title: "資源生物科学専門講義 国際農学演習",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 三屋 史朗 / MITSUYA Shiro",
  },
  {
    id: "info-221",
    title: "卒業論文研究(資生)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other 一柳 健司 各研究室担当教員 / ICHIYANAGI Kenji Faculty in charge of each laboratory",
  },
  {
    id: "info-222",
    title: "卒業論文研究(生命)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other 中道 範人 各研究室担当教員 / NAKAMICHI Norihito Faculty in charge of each laboratory",
  },
  {
    id: "info-223",
    title: "[G30]海外専門セミナー",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 石黒 澄衞 井上 直子 / ISHIGURO Sumie INOUE Naoko",
  },
  {
    id: "info-224",
    title: "海外専門セミナー",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 石黒 澄衞 井上 直子 / ISHIGURO Sumie INOUE Naoko",
  },
  {
    id: "info-225",
    title: "国内実地研修",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 一柳 健司 伊藤 智和 / ICHIYANAGI Kenji ITO Tomokazu",
  },
  {
    id: "info-226",
    title: "資源生物科学基盤実験実習(3年生用)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 石川 明 / ISHIKAWA Akira",
  },
  {
    id: "info-227",
    title: "生物環境科学基盤実験実習(2016年度以前入学)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 山﨑 真理子 / YAMASAKI Mariko",
  },
  {
    id: "info-228",
    title: "農学部特別講義 国際開発論",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 伊藤 香純 / ITO Kasumi",
  },
];
