import { Course } from "../courses";
export const CIA_COURSES: Course[] = [
  {
    id: "info-1",
    title: "代数学要論I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "古庄 英和 / FURUSHO Hidekazu",
  },
  {
    id: "info-2",
    title: "代数学続論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "岡田 聡一 / OKADA Soichi",
  },
  {
    id: "info-3",
    title: "物理学概論I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "久野 純治 / HISANO Junji",
  },
  {
    id: "info-4",
    title: "無機化学特論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher:
      "唯 美津木 邨次 智 山田 泰之 / TADA Mizuki MURATSUGU Satoshi YAMADA Yasuyuki",
  },
  {
    id: "info-5",
    title: "[G30]流体力学及び演習",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "info-6",
    title: "量子力学II",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "棚橋 誠治 / TANABASHI Masaharu",
  },
  {
    id: "info-7",
    title: "物理的運動学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "犬塚 修一郎 / INUTSUKA Shu-ichiro",
  },
  {
    id: "info-8",
    title: "先端物理学特論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "info-9",
    title: "リモートセンシング",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "髙橋 暢宏 石坂 丞二 / TAKAHASHI Nobuhiro ISHIZAKA Joji",
  },
  {
    id: "info-10",
    title: "[G30] 生物有機化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "西川 俊夫 / NISHIKAWA Toshio",
  },
  {
    id: "info-11",
    title: "確率論I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "中島 誠 / NAKASHIMA Makoto",
  },
  {
    id: "info-12",
    title: "分析化学実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher:
      "山田 泰之 田中 健太郎 河野 慎一郎 / YAMADA Yasuyuki TANAKA Kentaro KAWANO Shinichiro",
  },
  {
    id: "info-13",
    title: "生物科学実験法及び実験VIII",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "岡田 泰和 / OKADA Yasukazu",
  },
  {
    id: "info-14",
    title: "地球生物学実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher:
      "林 誠司 高橋 聡 後藤 佑介 依田 憲 庄子 晶子 / HAYASHI Seiji TAKAHASHI Satoshi GOTO Yusuke YODA Ken SHOJI Akiko",
  },
  {
    id: "info-15",
    title: "[G30]理学部化学実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "藤本 和宏 / FUJIMOTO Kazuhiro",
  },
  {
    id: "info-16",
    title: "[G30] 生命科学実験I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "小嶋 誠司 清水 貴史 / KOJIMA Seiji SHIMIZU Takashi",
  },
  {
    id: "info-17",
    title: "[G30]量子力学3",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "info-18",
    title: "解析学要論I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "松尾 信一郎 / MATSUO Shinichiroh",
  },
  {
    id: "info-19",
    title: "解析学続論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "寺澤 祐高 / TERASAWA Yutaka",
  },
  {
    id: "info-20",
    title: "量子力学IV",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "紺谷 浩 山川 洋一 / KONTANI Hiroshi YAMAKAWA Youichi",
  },
  {
    id: "info-21",
    title: "連続体力学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "犬塚 修一郎 / INUTSUKA Shu-ichiro",
  },
  {
    id: "info-22",
    title: "化学演習I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher:
      "斎藤 進 齋藤 雅明 河野 慎一郎 大城 宗一郎 橋谷 文貴 松田 晃孝 / SAITO Susumu SAITO Masaaki KAWANO Shinichiro OGI Soichiro HASHIYA Fumitaka MATSUDA Akitaka",
  },
  {
    id: "info-23",
    title: "生物科学実験I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "info-24",
    title: "分子生物学演習I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "田中 実 久本 直毅 / TANAKA Minoru HISAMOTO Naoki",
  },
  {
    id: "info-25",
    title: "分子生物学演習I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "木下 専 土屋 雄一朗 / KINOSHITA Makoto TSUCHIYA Yuichiro",
  },
  {
    id: "info-26",
    title: "分子生物学演習I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "木下 俊則 髙橋 洋平 / KINOSHITA Toshinori TAKAHASHI Yohei",
  },
  {
    id: "info-27",
    title: "分子生物学演習I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "嘉村 巧 上川内 あづさ / KAMURA Takumi KAMIKOUCHI Azusa",
  },
  {
    id: "info-28",
    title: "[G30]先端有機・高分子化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "福井 識人 / FUKUI Norihito",
  },
  {
    id: "info-29",
    title: "素粒子物理学II",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "早川 雅司 / HAYAKAWA Masashi",
  },
  {
    id: "info-30",
    title: "電磁気学特論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "渡邉 智彦 / WATANABE Tomohiko",
  },
  {
    id: "info-31",
    title: "有機機器分析",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "村井 征史 未定(理) / MURAI Masahito",
  },
  {
    id: "info-32",
    title: "[G30] 微生物学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "木村 眞 邊見 久 COROVIC Jasmina / KIMURA Makoto HEMMI Hisashi COROVIC Jasmina",
  },
  {
    id: "info-33",
    title: "解析学III",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "植田 好道 / UEDA Yoshimichi",
  },
  {
    id: "info-34",
    title: "物理学演習III",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "小林 晃人 戸部 和弘 木村 明洋 横山 修一郎 山影 相 山口 康宏 / KOBAYASHI Akito TOBE Kazuhiro KIMURA Akihiro YOKOYAMA Shuichiro YAMAKAGE Ai YAMAGUCHI Yasuhiro",
  },
  {
    id: "info-35",
    title: "物理学実験I[βクラス]",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "info-36",
    title: "量子力学II演習[αクラス]",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "小林 晃人 / KOBAYASHI Akito",
  },
  {
    id: "info-37",
    title: "生物科学実験法及び実験IX",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "岡田 泰和 / OKADA Yasukazu",
  },
  {
    id: "info-38",
    title: "[G30]物理学実験2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "info-39",
    title: "幾何学I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "HESSELHOLT LARS",
  },
  {
    id: "info-40",
    title: "統計物理学II演習[αクラス]",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "小林 晃人 / KOBAYASHI Akito",
  },
  {
    id: "info-41",
    title: "[G30]統計物理学3",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "info-42",
    title: "解析学要論II",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "吉田 伸生 / YOSHIDA Nobuo",
  },
  {
    id: "info-43",
    title: "数理解析・計算機数学III",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "LE GALL Francois Pierre M / LE GALL Francois Pierre Marcel",
  },
  {
    id: "info-44",
    title: "生態学II",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "依田 憲 後藤 佑介 庄子 晶子 / YODA Ken GOTO Yusuke SHOJI Akiko",
  },
  {
    id: "info-45",
    title: "[G30]生物物理学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "Florence Tama",
  },
  {
    id: "info-46",
    title: "生物物理学II",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "倭 剛久 / YAMATO Takahisa",
  },
  {
    id: "info-47",
    title: "物性化学I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "須田 理行 / SUDA Masayuki",
  },
  {
    id: "info-48",
    title: "[G30] 有機化学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "info-49",
    title: "[G30] 植物生理学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher:
      "中道 範人 村中 智明 BELLEGARDE Fanny 前田 真一 / NAKAMICHI Norihito MURANAKA Tomoaki BELLEGARDE Fanny MAEDA Shin ichi",
  },
  {
    id: "info-50",
    title: "無機化学実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher:
      "邨次 智 唯 美津木 愛場 雄一郎 荘司 長三 福 健太郎 / MURATSUGU Satoshi TADA Mizuki AIBA Yuichiro SHOJI Osami FUKU Kentaro",
  },
  {
    id: "info-51",
    title: "生物科学実験IV",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "日比 正彦 / HIBI Masahiko",
  },
  {
    id: "info-52",
    title: "地質学実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher:
      "纐纈 佑衣 高橋 聡 藤原 慎一 道林 克禎 竹内 誠 加藤 丈典 束田 和弘 林 誠司 HUMBLET Marc Andre / KOUKETSU Yui TAKAHASHI Satoshi FUJIWARA Shin-ichi MICHIBAYASHI Katsuyoshi TAKEUCHI Makoto KATO Takenori TSUKADA Kazuhiro HAYASHI Seiji HUMBLET Marc Andre",
  },
  {
    id: "info-53",
    title: "[G30][遠隔]計算機ソフトウェア2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher:
      "大塚 雄一 飯島 陽久 米澤 拓郎 小川 浩平 / OTSUKA Yuichi IIJIMA Haruhisa YONEZAWA Takuro OGAWA Kohei",
  },
  {
    id: "info-54",
    title: "幾何学要論I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "泉 圭介 / IZUMI Keisuke",
  },
  {
    id: "info-55",
    title: "幾何学続論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "太田 啓史 / OHTA Hiroshi",
  },
  {
    id: "info-56",
    title: "海洋科学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "角皆 潤 / TSUNOGAI Urumu",
  },
  {
    id: "info-57",
    title: "[G30] 有機化学4",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "info-58",
    title: "統計物理学II",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "紺谷 浩 / KONTANI Hiroshi",
  },
  {
    id: "info-59",
    title: "原子核物理学II",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "原田 正康 / HARADA Masayasu",
  },
  {
    id: "info-60",
    title: "化学演習II",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher:
      "斎藤 進 齋藤 雅明 河野 慎一郎 大城 宗一郎 橋谷 文貴 松田 晃孝 / SAITO Susumu SAITO Masaaki KAWANO Shinichiro OGI Soichiro HASHIYA Fumitaka MATSUDA Akitaka",
  },
  {
    id: "info-61",
    title: "有機化学特論I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "斎藤 進 / SAITO Susumu",
  },
  {
    id: "info-62",
    title: "地球化学分析法I及び実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "淺原 良浩 橋口 未奈子 / ASAHARA Yoshihiro HASHIGUCHI Minako",
  },
  {
    id: "info-63",
    title: "地球惑星物理学演習I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "橋本 千尋 城野 信一 / HASHIMOTO Chihiro SIRONO Sin-iti",
  },
  {
    id: "info-64",
    title: "[G30] 宇宙物理学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "竹内 努 / TAKEUCHI Tsutomu",
  },
  {
    id: "info-65",
    title: "[G30] 生化学4",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher:
      "灘野 大太 石黒 澄衞 山篠 貴史 / NADANO Daita ISHIGURO Sumie YAMASHINO Takafumi",
  },
  {
    id: "info-66",
    title: "数学演習VII",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "喜多 奈々緒 笹原 康浩 / KITA Nanao SASAHARA Yasuhiro",
  },
  {
    id: "info-67",
    title: "代数学I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "BACHMANN Henrik lennart",
  },
  {
    id: "info-68",
    title: "物理学演習III",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher:
      "小林 晃人 戸部 和弘 木村 明洋 横山 修一郎 山影 相 山口 康宏 / KOBAYASHI Akito TOBE Kazuhiro KIMURA Akihiro YOKOYAMA Shuichiro YAMAKAGE Ai YAMAGUCHI Yasuhiro",
  },
  {
    id: "info-69",
    title: "物理学実験I[αクラス]",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "info-70",
    title: "量子力学II演習[βクラス]",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "小林 晃人 / KOBAYASHI Akito",
  },
  {
    id: "info-71",
    title: "有機化学実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher:
      "伊藤 英人 大城 宗一郎 八木 亜樹子 山口 茂弘 谷 洋介 村井 征史 / ITO Hideto OGI Soichiro YAGI Akiko YAMAGUCHI Shigehiro TANI Yosuke MURAI Masahito",
  },
  {
    id: "info-72",
    title: "[G30]物理学セミナー1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "堀井 泰之 / HORII Yasuyuki",
  },
  {
    id: "info-73",
    title: "数学演習VIII",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "喜多 奈々緒 笹原 康浩 / KITA Nanao SASAHARA Yasuhiro",
  },
  {
    id: "info-74",
    title: "数理物理学I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "菅野 浩明 / KANNO Hiroaki",
  },
  {
    id: "info-75",
    title: "統計物理学II演習[βクラス]",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "小林 晃人 / KOBAYASHI Akito",
  },
  {
    id: "info-76",
    title: "生物科学実験V",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "清水 貴史 / SHIMIZU Takashi",
  },
  {
    id: "info-77",
    title: "数学演習IX",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "荒野 悠輝 木下 真也 / ARANO Yuki KINOSHITA Shinya",
  },
  {
    id: "info-78",
    title: "統計物理学IV",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "河野 浩 / KOHNO Hiroshi",
  },
  {
    id: "info-79",
    title: "宇宙物理学I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "中澤 知洋 / NAKAZAWA Kazuhiro",
  },
  {
    id: "info-80",
    title: "数学演習X",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "荒野 悠輝 木下 真也 / ARANO Yuki KINOSHITA Shinya",
  },
  {
    id: "info-81",
    title: "数理科学展望III",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "GARRIGUE JACQUES 林 正人 Neal Bez / GARRIGUE JACQUES HAYASHI Masahito Neal Bez",
  },
  {
    id: "info-82",
    title: "生物物理学I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "内橋 貴之 / UCHIHASHI Takayuki",
  },
  {
    id: "info-83",
    title: "宇宙物理学III",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "堀田 英之 / HOTTA Hideyuki",
  },
  {
    id: "info-84",
    title: "生物化学特論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "猪子 誠人 / INOKO Akihito",
  },
  {
    id: "info-85",
    title: "地球惑星化学II",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "日高 洋 / HIDAKA Hiroshi",
  },
  {
    id: "info-86",
    title: "[G30]物性物理学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "GELLOZ Bernard Jacques",
  },
  {
    id: "info-87",
    title: "[G30] 細胞学4",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "柴田 秀樹 MATURANA Andres Daniel 小田 裕昭 / SHIBATA Hideki MATURANA Andres Daniel ODA Hiroaki",
  },
  {
    id: "info-88",
    title: "応用数理I",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-4",
    teacher: "永尾 太郎 / NAGAO Taro",
  },
  {
    id: "info-89",
    title: "[G30]物理学演習4a",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-4",
    teacher: "山影 相 / YAMAKAGE Ai",
  },
  {
    id: "info-90",
    title: "[G30]物理学演習4b",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-4",
    teacher: "山影 相 / YAMAKAGE Ai",
  },
  {
    id: "info-91",
    title: "分子遺伝学IIa",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "松本 有樹修 / MATSUMOTO Akinobu",
  },
  {
    id: "info-92",
    title: "生物学特論XV",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "八木 克将 髙橋 宏二 / YAGI Yoshimasa TAKAHASHI Koji",
  },
  {
    id: "info-93",
    title: "分子生理学Ia",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "木下 俊則 髙橋 洋平 / KINOSHITA Toshinori TAKAHASHI Yohei",
  },
  {
    id: "info-94",
    title: "細胞学Ia",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "大澤 志津江 井川 敬介 / OHSAWA Shizue IKAWA Keisuke",
  },
  {
    id: "info-95",
    title: "遺伝学Ia",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher:
      "嘉村 巧 西村 浩平 小原 圭介 / KAMURA Takumi NISHIMURA Kohei OBARA Keisuke",
  },
  {
    id: "info-96",
    title: "現代測地学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-3",
    teacher: "伊藤 武男 / ITO Takeo",
  },
  {
    id: "info-97",
    title: "生命化学Ia",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "日比 正彦 / HIBI Masahiko",
  },
  {
    id: "info-98",
    title: "発生学Ib",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "田中 実 菊地 真理子 / TANAKA Minoru KIKUCHI Mariko",
  },
  {
    id: "info-99",
    title: "生物学各論IIa",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-1",
    teacher:
      "五島 剛太 山田 萌恵 自見 直人 / GOSHIMA Gohta YAMADA Moe JIMI Naoto",
  },
  {
    id: "info-100",
    title: "有機地球化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "三村 耕一 / MIMURA Koichi",
  },
  {
    id: "info-101",
    title: "分子遺伝学Ia",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "上川内 あづさ 石川 由希 田中 良弥 / KAMIKOUCHI Azusa ISHIKAWA Yuki TANAKA Ryoya",
  },
  {
    id: "info-102",
    title: "生物学特論XVI",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Mon-1",
    teacher: "八木 克将 髙橋 宏二 / YAGI Yoshimasa TAKAHASHI Koji",
  },
  {
    id: "info-103",
    title: "発生学Ia",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "久本 直毅 花房 洋 / HISAMOTO Naoki HANAFUSA Hiroshi",
  },
  {
    id: "info-104",
    title: "細胞学Ib",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Wed-1",
    teacher: "小田 祥久 / ODA Yoshihisa",
  },
  {
    id: "info-105",
    title: "遺伝学Ib",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Wed-2",
    teacher: "木下 専 / KINOSHITA Makoto",
  },
  {
    id: "info-106",
    title: "生命化学Ib",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Thu-1",
    teacher: "松林 嘉克 / MATSUBAYASHI Yoshikatsu",
  },
  {
    id: "info-107",
    title: "分子生理学Ib",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Thu-2",
    teacher: "打田 直行 / UCHIDA Naoyuki",
  },
  {
    id: "info-108",
    title: "生命化学IIa",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Fri-1",
    teacher: "土屋 雄一朗 / TSUCHIYA Yuichiro",
  },
  {
    id: "info-109",
    title: "環境化学",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Fri-1",
    teacher: "南 雅代 / MINAMI Masayo",
  },
  {
    id: "info-110",
    title: "分子遺伝学Ib",
    department: "情報",
    section: "専門",
    semester: "春2",
    cellKey: "Fri-2",
    teacher: "多田 安臣 / TADA Yasuomi",
  },
  {
    id: "info-111",
    title: "現代数学基礎AII",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "糟谷 久矢 / KASUYA Hisashi",
  },
  {
    id: "info-112",
    title: "数理科学展望I",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher:
      "植田 好道 納谷 信 谷本 祥 / UEDA Yoshimichi NAYATANI Shin TANIMOTO Sho",
  },
  {
    id: "info-113",
    title: "無機物化機器分析",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher:
      "田中 健太郎 伏谷 瑞穂 邨次 智 須田 理行 唯 美津木 菱川 明栄 松下 未知雄 愛場 雄一郎 山田 泰之 荘司 長三 成田 秀樹 / TANAKA Kentaro FUSHITANI Mizuho MURATSUGU Satoshi SUDA Masayuki TADA Mizuki HISHIKAWA Akiyoshi MATSUSHITA Michio AIBA Yuichiro YAMADA Yasuyuki SHOJI Osami NARITA Hideki",
  },
  {
    id: "info-114",
    title: "地球計測学演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "渡辺 俊樹 / WATANABE Toshiki",
  },
  {
    id: "info-115",
    title: "数理物理学IV",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "濱中 真志 / HAMANAKA Masashi",
  },
  {
    id: "info-116",
    title: "宇宙物理学II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "立原 研悟 / TACHIHARA Kengo",
  },
  {
    id: "info-117",
    title: "生物無機化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "荘司 長三 / SHOJI Osami",
  },
  {
    id: "info-118",
    title: "地球惑星観測論",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "田所 敬一 / TADOKORO Keiichi",
  },
  {
    id: "info-119",
    title: "[G30]素粒子物理学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "原田 正康 / HARADA Masayasu",
  },
  {
    id: "info-120",
    title: "[G30]物性物理学3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "谷山 智康 / TANIYAMA Tomoyasu",
  },
  {
    id: "info-121",
    title: "計算数学基礎",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "GARRIGUE JACQUES 佐藤 猛 / GARRIGUE JACQUES SATOH Takeshi",
  },
  {
    id: "info-122",
    title: "現代数学研究",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "岡田 聡一 / OKADA Soichi",
  },
  {
    id: "info-123",
    title: "幾何学II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "白水 徹也 / SHIROMIZU Tetsuya",
  },
  {
    id: "info-124",
    title: "生物化学実験",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher:
      "木村 康明 阿部 洋 橋谷 文貴 / KIMURA Yasuaki ABE Hiroshi HASHIYA Fumitaka",
  },
  {
    id: "info-125",
    title: "生物科学実験法及び実験VI",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "清水 貴史 / SHIMIZU Takashi",
  },
  {
    id: "info-126",
    title: "太陽系物理学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "渡邊 誠一郎 / WATANABE Sei-ichiro",
  },
  {
    id: "info-127",
    title: "[G30] 生命科学実験II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "小嶋 誠司 清水 貴史 / KOJIMA Seiji SHIMIZU Takashi",
  },
  {
    id: "info-128",
    title: "気候科学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "植村 立 松井 仁志 / UEMURA Ryu MATSUI Hitoshi",
  },
  {
    id: "info-129",
    title: "生態学I",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "平野 恭弘 西田 佐知子 / HIRANO Yasuhiro NISHIDA Sachiko",
  },
  {
    id: "info-130",
    title: "[G30]物性物理学1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "GELLOZ Bernard Jacques",
  },
  {
    id: "info-131",
    title: "[G30]量子力学2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "info-132",
    title: "代数学要論II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "髙橋 亮 / TAKAHASHI Ryo",
  },
  {
    id: "info-133",
    title: "物理実験学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "奥村 曉 / OKUMURA Akira",
  },
  {
    id: "info-134",
    title: "原子核物理学I",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "清水 裕彦 / SHIMIZU Hirohiko",
  },
  {
    id: "info-135",
    title: "[G30]物理学セミナー2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "田村 陽一 / TAMURA Yoichi",
  },
  {
    id: "info-136",
    title: "[G30] 有機化学3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "info-137",
    title: "確率・統計基礎",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "森 立平 / MORI Ryuhei",
  },
  {
    id: "info-138",
    title: "量子力学III",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "戸部 和弘 / TOBE Kazuhiro",
  },
  {
    id: "info-139",
    title: "高分子化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "関 隆広",
  },
  {
    id: "info-140",
    title: "地質学特論",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "竹内 誠 高橋 聡 道林 克禎 林 誠司 纐纈 佑衣 / TAKEUCHI Makoto TAKAHASHI Satoshi MICHIBAYASHI Katsuyoshi HAYASHI Seiji KOUKETSU Yui",
  },
  {
    id: "info-141",
    title: "[G30]計測工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "栗本 宗明 / KURIMOTO Muneaki",
  },
  {
    id: "info-142",
    title: "[G30] 生理・解剖学2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "日比 正彦 / HIBI Masahiko",
  },
  {
    id: "info-143",
    title: "現代数学基礎CIII",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "菅野 浩明 / KANNO Hiroaki",
  },
  {
    id: "info-144",
    title: "数理科学展望IV",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher:
      "杉本 充 LE GALL Francois Pierre M 永尾 太郎 / SUGIMOTO Mitsuru LE GALL Francois Pierre Marcel NAGAO Taro",
  },
  {
    id: "info-145",
    title: "物理学演習IV",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "山川 洋一 西川 宜彦 / YAMAKAWA Youichi NISHIKAWA Yoshihiko",
  },
  {
    id: "info-146",
    title: "物理学実験II[βクラス]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "info-147",
    title: "量子力学III演習[αクラス]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "山川 洋一 / YAMAKAWA Youichi",
  },
  {
    id: "info-148",
    title: "生物科学実験法及び実験VII",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "岡田 泰和 / OKADA Yasukazu",
  },
  {
    id: "info-149",
    title: "気象学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "篠田 太郎 / SHINODA Taro",
  },
  {
    id: "info-150",
    title: "[G30]物理学実験1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "info-151",
    title: "確率論II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "吉田 伸生 / YOSHIDA Nobuo",
  },
  {
    id: "info-152",
    title: "統計物理学III演習[αクラス]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "山川 洋一 / YAMAKAWA Youichi",
  },
  {
    id: "info-153",
    title: "太陽地球系科学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "野澤 悟德 / NOZAWA Satonori",
  },
  {
    id: "info-154",
    title: "現代数学基礎CII",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "菱田 俊明 / HISHIDA Toshiaki",
  },
  {
    id: "info-155",
    title: "数理解析・計算機数学I",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "久保 仁 笹原 康浩 / KUBO Masashi SASAHARA Yasuhiro",
  },
  {
    id: "info-156",
    title: "数理解析・計算機数学II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "平井 広志 / HIRAI Hiroshi",
  },
  {
    id: "info-157",
    title: "化学物理学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "槇 亙介 / MAKI Kosuke",
  },
  {
    id: "info-158",
    title: "化学統計力学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "青柳 忍 / AOYAGI Shinobu",
  },
  {
    id: "info-159",
    title: "宇宙化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "平原 靖大 / HIRAHARA Yasuhiro",
  },
  {
    id: "info-160",
    title: "[G30]化学物理学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "内橋 貴之 / UCHIHASHI Takayuki",
  },
  {
    id: "info-161",
    title: "プラズマ物理学I",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "渡邉 智彦 / WATANABE Tomohiko",
  },
  {
    id: "info-162",
    title: "物性化学II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "成田 秀樹 須田 理行 / NARITA Hideki SUDA Masayuki",
  },
  {
    id: "info-163",
    title: "生物圏進化学I",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "高橋 聡 林 誠司 / TAKAHASHI Satoshi HAYASHI Seiji",
  },
  {
    id: "info-164",
    title: "情報科学概論II[βクラス]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "立原 研悟 / TACHIHARA Kengo",
  },
  {
    id: "info-165",
    title: "物理学セミナー第VIIの1[I-1α]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "谷山 智康 谷口 博基 / TANIYAMA Tomoyasu TANIGUCHI Hiroki",
  },
  {
    id: "info-166",
    title: "物理学セミナー第VIIIの1[II-1α]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "奥平 琢也 / OKUDAIRA Takuya",
  },
  {
    id: "info-167",
    title: "物理学セミナー第IXの1[III-1α]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "田村 陽一 / TAMURA Yoichi",
  },
  {
    id: "info-168",
    title: "物理学セミナー第Xの1[IV-1α]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "倭 剛久 / YAMATO Takahisa",
  },
  {
    id: "info-169",
    title: "物理化学実験",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher:
      "松下 未知雄 稲井 直人 伏谷 瑞穂 柳井 毅 須田 理行 齋藤 雅明 菱川 明栄 松田 晃孝 成田 秀樹 藤本 和宏 / MATSUSHITA Michio INAI Naoto FUSHITANI Mizuho YANAI Takeshi SUDA Masayuki SAITO Masaaki HISHIKAWA Akiyoshi MATSUDA Akitaka NARITA Hideki FUJIMOTO Kazuhiro",
  },
  {
    id: "info-170",
    title: "生物科学実験II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "松本 有樹修 / MATSUMOTO Akinobu",
  },
  {
    id: "info-171",
    title: "[G30] Agricultural Science",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher: "井上 直子 / INOUE Naoko",
  },
  {
    id: "info-172",
    title: "幾何学要論II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "森吉 仁志 / MORIYOSHI Hitoshi",
  },
  {
    id: "info-173",
    title: "数学演習V",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher:
      "泉 圭介 久本 智之 松尾 信一郎 / IZUMI Keisuke HISAMOTO Tomoyuki MATSUO Shinichiroh",
  },
  {
    id: "info-174",
    title: "代数学II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "柳田 伸太郎 / YANAGIDA Shintaro",
  },
  {
    id: "info-175",
    title: "情報科学概論I",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "立原 研悟 小林 浩 / TACHIHARA Kengo KOBAYASHI Hiroshi",
  },
  {
    id: "info-176",
    title: "物性物理学I",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "寺崎 一郎 / TERASAKI Ichiro",
  },
  {
    id: "info-177",
    title: "地球惑星科学セミナーI",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "杉谷 健一郎 / SUGITANI Kenichiro",
  },
  {
    id: "info-178",
    title: "[G30][遠隔]計算化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "柳井 毅 / YANAI Takeshi",
  },
  {
    id: "info-179",
    title: "数学演習VI",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher:
      "泉 圭介 久本 智之 松尾 信一郎 / IZUMI Keisuke HISAMOTO Tomoyuki MATSUO Shinichiroh",
  },
  {
    id: "info-180",
    title: "解析学IV",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "Neal Bez",
  },
  {
    id: "info-181",
    title: "統計物理学III",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "大成 誠一郎 / ONARI Seiichiro",
  },
  {
    id: "info-182",
    title: "物性物理学II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "谷口 博基 / TANIGUCHI Hiroki",
  },
  {
    id: "info-183",
    title: "有機化学特論II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "伊藤 英人 南保 正和 / ITO Hideto NAMBO Masakazu",
  },
  {
    id: "info-184",
    title: "[G30]高分子化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "上垣外 正己 / KAMIGAITO Masami",
  },
  {
    id: "info-185",
    title: "現代数学基礎BII",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "中村 勇哉 / NAKAMURA Yusuke",
  },
  {
    id: "info-186",
    title: "物理学セミナー第VIIの2[I-1β]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "下志万 貴博 小林 義明 / SHIMOJIMA Takahiro KOBAYASHI Yoshiaki",
  },
  {
    id: "info-187",
    title: "物理学セミナー第VIIIの2[II-1β]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "南部 保貞 / NAMBU Yasusada",
  },
  {
    id: "info-188",
    title: "物理学セミナー第IXの2[III-1β]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "國生 拓摩 / KOKUSHO Takuma",
  },
  {
    id: "info-189",
    title: "物理学セミナー第Xの2[IV-1β]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "野口 巧 / NOGUCHI Takumi",
  },
  {
    id: "info-190",
    title: "物理学実験II[αクラス]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "info-191",
    title: "生物科学実験III",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "松本 有樹修 / MATSUMOTO Akinobu",
  },
  {
    id: "info-192",
    title: "数値解析法及び演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "城野 信一 / SIRONO Sin-iti",
  },
  {
    id: "info-193",
    title: "[G30]物理学演習3a",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "市來 淨與 / ICHIKI Kiyotomo",
  },
  {
    id: "info-194",
    title: "[G30]物理学演習3b",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "市來 淨與 / ICHIKI Kiyotomo",
  },
  {
    id: "info-195",
    title: "[G30]計算機ソフトウェア1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "長谷川 浩 LU Shan / HASEGAWA Hiroshi LU Shan",
  },
  {
    id: "info-196",
    title: "解析学要論III",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "杉本 充 / SUGIMOTO Mitsuru",
  },
  {
    id: "info-197",
    title: "素粒子物理学I",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "info-198",
    title: "一般相対論",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "南部 保貞 / NAMBU Yasusada",
  },
  {
    id: "info-199",
    title: "地震学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "熊谷 博之 / KUMAGAI Hiroyuki",
  },
  {
    id: "info-200",
    title: "[G30] 有機化学5",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "info-201",
    title: "応用数理II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "永尾 太郎 / NAGAO Taro",
  },
  {
    id: "info-202",
    title: "物理学演習IV",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "山川 洋一 西川 宜彦 / YAMAKAWA Youichi NISHIKAWA Yoshihiko",
  },
  {
    id: "info-203",
    title: "量子力学III演習[βクラス]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "山川 洋一 / YAMAKAWA Youichi",
  },
  {
    id: "info-204",
    title: "地球化学分析法II及び実験",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "三村 耕一 / MIMURA Koichi",
  },
  {
    id: "info-205",
    title: "統計物理学III演習[βクラス]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "山川 洋一 / YAMAKAWA Youichi",
  },
  {
    id: "info-206",
    title: "[G30]統計物理学2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "info-207",
    title: "生物学各論Ia",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "岡田 泰和 / OKADA Yasukazu",
  },
  {
    id: "info-208",
    title: "生物物理学Ia",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "廣明 秀一 / HIROAKI Hidekazu",
  },
  {
    id: "info-209",
    title: "分子生理学IIa",
    department: "情報",
    section: "専門",
    semester: "秋2",
    cellKey: "Mon-2",
    teacher: "乘本 裕明 / NORIMOTO Hiroaki",
  },
  {
    id: "info-210",
    title: "生物物理学Ib",
    department: "情報",
    section: "専門",
    semester: "秋2",
    cellKey: "Tue-1",
    teacher:
      "成田 哲博 瀧口 金吾 平子 善章 / NARITA Akihiro TAKIGUCHI Kingo HIRAKO Yoshiaki",
  },
  {
    id: "info-211",
    title: "数学研究AI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 石井 亮 / ISHII Akira",
  },
  {
    id: "info-212",
    title: "数学研究BI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 植田 好道 / UEDA Yoshimichi",
  },
  {
    id: "info-213",
    title: "数学研究CI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 太田 啓史 / OHTA Hiroshi",
  },
  {
    id: "info-214",
    title: "数学研究EI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 岡田 聡一 / OKADA Soichi",
  },
  {
    id: "info-215",
    title: "数学研究FI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other GARRIGUE JACQUES / GARRIGUE JACQUES",
  },
  {
    id: "info-216",
    title: "数学研究GI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 白水 徹也 / SHIROMIZU Tetsuya",
  },
  {
    id: "info-217",
    title: "数学研究HI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 杉本 充 / SUGIMOTO Mitsuru",
  },
  {
    id: "info-218",
    title: "数学研究KI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 菱田 俊明 / HISHIDA Toshiaki",
  },
  {
    id: "info-219",
    title: "数学研究LI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 古庄 英和 / FURUSHO Hidekazu",
  },
  {
    id: "info-220",
    title: "数学研究MI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other Neal Bez / Neal Bez",
  },
  {
    id: "info-221",
    title: "数学研究NI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 森吉 仁志 / MORIYOSHI Hitoshi",
  },
  {
    id: "info-222",
    title: "数学研究OI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 粟田 英資 / AWATA Hidetoshi",
  },
  {
    id: "info-223",
    title: "数学研究PI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other JAERISCH Johannes Klaus B / JAERISCH Johannes Klaus Bernhard",
  },
  {
    id: "info-224",
    title: "数学研究RI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 喜多 奈々緒 / KITA Nanao",
  },
  {
    id: "info-225",
    title: "数学研究SI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 内藤 久資 / NAITO Hisashi",
  },
  {
    id: "info-226",
    title: "数学研究UI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 中島 誠 / NAKASHIMA Makoto",
  },
  {
    id: "info-227",
    title: "数学研究VI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 中村 勇哉 / NAKAMURA Yusuke",
  },
  {
    id: "info-228",
    title: "数学研究WI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 林 孝宏 / HAYASHI Takahiro",
  },
  {
    id: "info-229",
    title: "数学研究JI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 中西 知樹 / NAKANISHI Tomoki",
  },
  {
    id: "info-230",
    title: "数学研究QI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 大久保 俊 / OHKUBO Shun",
  },
  {
    id: "info-231",
    title: "数学研究YI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 松尾 信一郎 / MATSUO Shinichiroh",
  },
  {
    id: "info-232",
    title: "統計・情報数理I",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 森 忠彦 / MORI Tadahiko",
  },
  {
    id: "info-233",
    title: "統計・情報数理II",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 日下部 健児 清水 信広 西岡 隆 / KUSAKABE Kenji SHIMIZU Nobuhiro NISHIOKA Takashi",
  },
  {
    id: "info-234",
    title: "代数学特別講義II",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 伊藤 由佳理 / ITO Yukari",
  },
  {
    id: "info-235",
    title: "幾何学特別講義III",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other MAHMOUDI Sonia / MAHMOUDI Sonia",
  },
  {
    id: "info-236",
    title: "確率論特別講義I",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 桑江 一洋 / KUWAE Kazuhiro",
  },
  {
    id: "info-237",
    title: "応用数理特別講義I",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 菅野 浩明 / KANNO Hiroaki",
  },
  {
    id: "info-238",
    title: "生物物理学集中実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 村上 緑 / MURAKAMI Midori",
  },
  {
    id: "info-239",
    title: "臨海実習",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 五島 剛太 森田 真布 自見 直人 / GOSHIMA Gohta MORITA Maho JIMI Naoto",
  },
  {
    id: "info-240",
    title: "生物学特論IV",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 土屋 雄一朗 長谷部 光泰 / TSUCHIYA Yuichiro HASEBE Mitsuyasu",
  },
  {
    id: "info-241",
    title: "生物学特論XIV",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 岩見 真吾 / IWAMI Shingo",
  },
  {
    id: "info-242",
    title: "[G30] アドバンス生命科学実験法及び実験1",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 杉山 伸 / SUGIYAMA Shin",
  },
  {
    id: "info-243",
    title: "[G30] アドバンス生命科学実験法及び実験2",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 杉山 伸 / SUGIYAMA Shin",
  },
  {
    id: "info-244",
    title: "[G30] アドバンス生命科学実験法及び実験3",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 杉山 伸 / SUGIYAMA Shin",
  },
  {
    id: "info-245",
    title: "[G30] アドバンス生命科学実験法及び実験4",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 杉山 伸 / SUGIYAMA Shin",
  },
  {
    id: "info-246",
    title: "[G30] アドバンス生命科学実験法及び実験5",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 杉山 伸 / SUGIYAMA Shin",
  },
  {
    id: "info-247",
    title: "[G30] 特別実験(卒業実験)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 野間 健太郎 / NOMA Kentaro",
  },
  {
    id: "info-248",
    title: "[G30] 臨海実習",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 五島 剛太 森田 真布 自見 直人 / GOSHIMA Gohta MORITA Maho JIMI Naoto",
  },
  {
    id: "info-249",
    title: "数学研究AII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 石井 亮 / ISHII Akira",
  },
  {
    id: "info-250",
    title: "数学研究BII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 植田 好道 / UEDA Yoshimichi",
  },
  {
    id: "info-251",
    title: "数学研究CII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 太田 啓史 / OHTA Hiroshi",
  },
  {
    id: "info-252",
    title: "数学研究DII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 大平 徹 / OHIRA Toru",
  },
  {
    id: "info-253",
    title: "数学研究EII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 岡田 聡一 / OKADA Soichi",
  },
  {
    id: "info-254",
    title: "数学研究FII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other GARRIGUE JACQUES / GARRIGUE JACQUES",
  },
  {
    id: "info-255",
    title: "数学研究GII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 白水 徹也 / SHIROMIZU Tetsuya",
  },
  {
    id: "info-256",
    title: "数学研究HII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 杉本 充 / SUGIMOTO Mitsuru",
  },
  {
    id: "info-257",
    title: "数学研究KII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 菱田 俊明 / HISHIDA Toshiaki",
  },
  {
    id: "info-258",
    title: "数学研究LII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 古庄 英和 / FURUSHO Hidekazu",
  },
  {
    id: "info-259",
    title: "数学研究MII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other Neal Bez / Neal Bez",
  },
  {
    id: "info-260",
    title: "数学研究NII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 森吉 仁志 / MORIYOSHI Hitoshi",
  },
  {
    id: "info-261",
    title: "数学研究OII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 粟田 英資 / AWATA Hidetoshi",
  },
  {
    id: "info-262",
    title: "数学研究PII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other JAERISCH Johannes Klaus B / JAERISCH Johannes Klaus Bernhard",
  },
  {
    id: "info-263",
    title: "数学研究RII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 喜多 奈々緒 / KITA Nanao",
  },
  {
    id: "info-264",
    title: "数学研究SII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 内藤 久資 / NAITO Hisashi",
  },
  {
    id: "info-265",
    title: "数学研究UII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 中島 誠 / NAKASHIMA Makoto",
  },
  {
    id: "info-266",
    title: "数学研究VII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 中村 勇哉 / NAKAMURA Yusuke",
  },
  {
    id: "info-267",
    title: "数学研究WII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 林 孝宏 / HAYASHI Takahiro",
  },
  {
    id: "info-268",
    title: "数学研究JII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 中西 知樹 / NAKANISHI Tomoki",
  },
  {
    id: "info-269",
    title: "数学研究QII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 大久保 俊 / OHKUBO Shun",
  },
  {
    id: "info-270",
    title: "数学研究YII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 松尾 信一郎 / MATSUO Shinichiroh",
  },
  {
    id: "info-271",
    title: "幾何学特別講義II",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other BOURNE Christopher jack / BOURNE Christopher jack",
  },
  {
    id: "info-272",
    title: "解析学特別講義IV",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 神本 晋吾 / KAMIMOTO Shingo",
  },
  {
    id: "info-273",
    title: "数理物理学特別講義II",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 白石 潤一 / SHIRAISHI Junichi",
  },
  {
    id: "info-274",
    title: "応用数理特別講義II",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 菅野 浩明 / KANNO Hiroaki",
  },
  {
    id: "info-275",
    title: "応用数理特別講義III",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 平岡 裕章 / HIRAOKA Yasuaki",
  },
  {
    id: "info-276",
    title: "生物学特論III",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other 吉岡 泰 坂本 亘 / YOSHIOKA Yasushi SAKAMOTO Wataru",
  },
  {
    id: "info-277",
    title: "生物学特論V",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other 中野 俊詩 豊島 有 / NAKANO Syunji TOYOSHIMA Yu",
  },
  {
    id: "info-278",
    title: "生物学特論XI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other 木下 俊則 増冨 祐司 / KINOSHITA Toshinori MASUTOMI Yuji",
  },
  {
    id: "info-279",
    title: "生物学特論XII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other 瀧口 金吾 野村 慎一郎 / TAKIGUCHI Kingo NOMURA Shin-ichiro",
  },
  {
    id: "info-280",
    title: "生物学特論XIII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other 小嶋 誠司 港 雄介 / KOJIMA Seiji MINATO Yusuke",
  },
  {
    id: "info-281",
    title: "生物科学実験法及び実験X",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 岡田 泰和 / OKADA Yasukazu",
  },
  {
    id: "info-282",
    title: "生物科学実験法及び実験XI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 乘本 裕明 / NORIMOTO Hiroaki",
  },
  {
    id: "info-283",
    title: "生物科学実験法及び実験XII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 乘本 裕明 / NORIMOTO Hiroaki",
  },
  {
    id: "info-284",
    title: "生物科学実験法及び実験XIII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 乘本 裕明 / NORIMOTO Hiroaki",
  },
  {
    id: "info-285",
    title: "生物科学実験法及び実験XIV",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 乘本 裕明 / NORIMOTO Hiroaki",
  },
  {
    id: "info-286",
    title: "[G30]物理学特別実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 田村 陽一 / TAMURA Yoichi",
  },
  {
    id: "info-287",
    title: "[G30]特別実験(卒業研究)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 斎藤 進 / SAITO Susumu",
  },
  {
    id: "info-288",
    title: "[G30] 特別実験(卒業実験)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 野間 健太郎 / NOMA Kentaro",
  },
  {
    id: "info-289",
    title: "物理学講究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 原田 正康 / HARADA Masayasu",
  },
  {
    id: "info-290",
    title: "物理学特別実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 田村 陽一 / TAMURA Yoichi",
  },
  {
    id: "info-291",
    title: "物理学講究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 原田 正康 / HARADA Masayasu",
  },
  {
    id: "info-292",
    title: "特別実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 斎藤 進 / SAITO Susumu",
  },
  {
    id: "info-293",
    title: "卒業実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 小田 祥久 / ODA Yoshihisa",
  },
  {
    id: "info-294",
    title: "博物館実習1",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 西田 佐知子 藤原 慎一 / NISHIDA Sachiko FUJIWARA Shin-ichi",
  },
  {
    id: "info-295",
    title: "博物館実習2",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 新美 倫子 門脇 誠二 / NIIMI Michiko KADOWAKI Seiji",
  },
  {
    id: "info-296",
    title: "フィールドセミナーI(地球科学野外巡検)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 竹内 誠 高橋 聡 道林 克禎 林 誠司 纐纈 佑衣 / TAKEUCHI Makoto TAKAHASHI Satoshi MICHIBAYASHI Katsuyoshi HAYASHI Seiji KOUKETSU Yui",
  },
  {
    id: "info-297",
    title: "地球惑星科学特別研究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 高野 雅夫 / TAKANO Masao",
  },
  {
    id: "info-298",
    title: "地球惑星科学特別研究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 竹内 誠 / TAKEUCHI Makoto",
  },
  {
    id: "info-299",
    title: "地球惑星科学特別研究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 道林 克禎 / MICHIBAYASHI Katsuyoshi",
  },
  {
    id: "info-300",
    title: "地球惑星科学特別研究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 高橋 聡 / TAKAHASHI Satoshi",
  },
  {
    id: "info-301",
    title: "地球惑星科学特別研究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 渡邊 誠一郎 / WATANABE Sei-ichiro",
  },
  {
    id: "info-302",
    title: "地球惑星科学特別研究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 坂井 亜規子 / SAKAI Akiko",
  },
  {
    id: "info-303",
    title: "地球惑星科学特別研究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 三村 耕一 / MIMURA Koichi",
  },
  {
    id: "info-304",
    title: "地球惑星科学特別研究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 日高 洋 / HIDAKA Hiroshi",
  },
  {
    id: "info-305",
    title: "地球惑星科学特別研究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 平原 靖大 / HIRAHARA Yasuhiro",
  },
  {
    id: "info-306",
    title: "地球惑星科学特別研究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Full-year course Intensive(Sp-Fa) Other Other 依田 憲 / YODA Ken",
  },
  {
    id: "info-307",
    title: "フィールドセミナーII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 道林 克禎 / MICHIBAYASHI Katsuyoshi",
  },
  {
    id: "info-308",
    title: "大気水圏フィールドセミナーI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 松井 仁志 永尾 一平 篠田 雅人 / MATSUI Hitoshi NAGAO Ippei SHINODA Masato",
  },
  {
    id: "info-309",
    title: "大気水圏フィールドセミナーII",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 中川 書子 角皆 潤 / NAKAGAWA Fumiko TSUNOGAI Urumu",
  },
  {
    id: "info-310",
    title: "博物館実習3",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 吉田 英一 束田 和弘 / YOSHIDA Hidekazu TSUKADA Kazuhiro",
  },
  {
    id: "info-311",
    title: "数学研究DI",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 大平 徹 / OHIRA Toru",
  },
  {
    id: "info-312",
    title: "情報科学概論II[αクラス]",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "立原 研悟 三石 郁之 / TACHIHARA Kengo MITSUISHI Ikuyuki",
  },
  {
    id: "info-313",
    title: "地質調査(春)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 高橋 聡 / TAKAHASHI Satoshi",
  },
  {
    id: "info-314",
    title: "地質調査(秋)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 道林 克禎 / MICHIBAYASHI Katsuyoshi",
  },
  {
    id: "info-315",
    title: "[G30]物理学講究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 棚橋 誠治 / TANABASHI Masaharu",
  },
  {
    id: "info-316",
    title: "[G30]物理学講究",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 原田 正康 / HARADA Masayasu",
  },
  {
    id: "info-317",
    title: "[G30]物理学特別実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 野口 巧 / NOGUCHI Takumi",
  },
  {
    id: "info-318",
    title: "[G30]理学部化学実験",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "藤本 和宏 / FUJIMOTO Kazuhiro",
  },
  {
    id: "info-319",
    title: "[G30]特別実験(卒業研究)",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 斎藤 進 / SAITO Susumu",
  },
];
