import { Course } from "../courses";
export const CIA_COURSES: Course[] = [
  {
    id: "cia-1",
    title: "代数学要論I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "古庄 英和 / FURUSHO Hidekazu",
  },
  {
    id: "cia-2",
    title: "代数学続論",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "岡田 聡一 / OKADA Soichi",
  },
  {
    id: "cia-3",
    title: "物理学概論I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "久野 純治 / HISANO Junji",
  },
  {
    id: "cia-4",
    title: "無機化学特論",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-1",
    teacher:
      "唯 美津木 邨次 智 山田 泰之 / TADA Mizuki MURATSUGU Satoshi YAMADA Yasuyuki",
  },
  {
    id: "cia-5",
    title: "[G30]流体力学及び演習",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "cia-6",
    title: "量子力学II",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "棚橋 誠治 / TANABASHI Masaharu",
  },
  {
    id: "cia-7",
    title: "物理的運動学",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "犬塚 修一郎 / INUTSUKA Shu-ichiro",
  },
  {
    id: "cia-8",
    title: "先端物理学特論",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "cia-9",
    title: "リモートセンシング",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "髙橋 暢宏 石坂 丞二 / TAKAHASHI Nobuhiro ISHIZAKA Joji",
  },
  {
    id: "cia-10",
    title: "[G30] 生物有機化学",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "西川 俊夫 / NISHIKAWA Toshio",
  },
  {
    id: "cia-11",
    title: "確率論I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "中島 誠 / NAKASHIMA Makoto",
  },
  {
    id: "cia-12",
    title: "分析化学実験",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-3",
    teacher:
      "山田 泰之 田中 健太郎 河野 慎一郎 / YAMADA Yasuyuki TANAKA Kentaro KAWANO Shinichiro",
  },
  {
    id: "cia-13",
    title: "生物科学実験法及び実験VIII",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "岡田 泰和 / OKADA Yasukazu",
  },
  {
    id: "cia-14",
    title: "地球生物学実験",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-3",
    teacher:
      "林 誠司 高橋 聡 後藤 佑介 依田 憲 庄子 晶子 / HAYASHI Seiji TAKAHASHI Satoshi GOTO Yusuke YODA Ken SHOJI Akiko",
  },
  {
    id: "cia-15",
    title: "[G30]理学部化学実験",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "藤本 和宏 / FUJIMOTO Kazuhiro",
  },
  {
    id: "cia-16",
    title: "[G30] 生命科学実験I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "小嶋 誠司 清水 貴史 / KOJIMA Seiji SHIMIZU Takashi",
  },
  {
    id: "cia-17",
    title: "[G30]量子力学3",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "cia-18",
    title: "解析学要論I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "松尾 信一郎 / MATSUO Shinichiroh",
  },
  {
    id: "cia-19",
    title: "解析学続論",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "寺澤 祐高 / TERASAWA Yutaka",
  },
  {
    id: "cia-20",
    title: "量子力学IV",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "紺谷 浩 山川 洋一 / KONTANI Hiroshi YAMAKAWA Youichi",
  },
  {
    id: "cia-21",
    title: "連続体力学",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "犬塚 修一郎 / INUTSUKA Shu-ichiro",
  },
  {
    id: "cia-22",
    title: "化学演習I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher:
      "斎藤 進 齋藤 雅明 河野 慎一郎 大城 宗一郎 橋谷 文貴 松田 晃孝 / SAITO Susumu SAITO Masaaki KAWANO Shinichiro OGI Soichiro HASHIYA Fumitaka MATSUDA Akitaka",
  },
  {
    id: "cia-23",
    title: "生物科学実験I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "cia-24",
    title: "分子生物学演習I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "田中 実 久本 直毅 / TANAKA Minoru HISAMOTO Naoki",
  },
  {
    id: "cia-25",
    title: "分子生物学演習I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "木下 専 土屋 雄一朗 / KINOSHITA Makoto TSUCHIYA Yuichiro",
  },
  {
    id: "cia-26",
    title: "分子生物学演習I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "木下 俊則 髙橋 洋平 / KINOSHITA Toshinori TAKAHASHI Yohei",
  },
  {
    id: "cia-27",
    title: "分子生物学演習I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "嘉村 巧 上川内 あづさ / KAMURA Takumi KAMIKOUCHI Azusa",
  },
  {
    id: "cia-28",
    title: "[G30]先端有機・高分子化学",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "福井 識人 / FUKUI Norihito",
  },
  {
    id: "cia-29",
    title: "素粒子物理学II",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "早川 雅司 / HAYAKAWA Masashi",
  },
  {
    id: "cia-30",
    title: "電磁気学特論",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "渡邉 智彦 / WATANABE Tomohiko",
  },
  {
    id: "cia-31",
    title: "有機機器分析",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "村井 征史 未定(理) / MURAI Masahito",
  },
  {
    id: "cia-32",
    title: "[G30] 微生物学",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "木村 眞 邊見 久 COROVIC Jasmina / KIMURA Makoto HEMMI Hisashi COROVIC Jasmina",
  },
  {
    id: "cia-33",
    title: "解析学III",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "植田 好道 / UEDA Yoshimichi",
  },
  {
    id: "cia-34",
    title: "物理学演習III",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-3",
    teacher:
      "小林 晃人 戸部 和弘 木村 明洋 横山 修一郎 山影 相 山口 康宏 / KOBAYASHI Akito TOBE Kazuhiro KIMURA Akihiro YOKOYAMA Shuichiro YAMAKAGE Ai YAMAGUCHI Yasuhiro",
  },
  {
    id: "cia-35",
    title: "物理学実験I[βクラス]",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "cia-36",
    title: "量子力学II演習[αクラス]",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "小林 晃人 / KOBAYASHI Akito",
  },
  {
    id: "cia-37",
    title: "生物科学実験法及び実験IX",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "岡田 泰和 / OKADA Yasukazu",
  },
  {
    id: "cia-38",
    title: "[G30]物理学実験2",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "cia-39",
    title: "幾何学I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "HESSELHOLT LARS",
  },
  {
    id: "cia-40",
    title: "統計物理学II演習[αクラス]",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "小林 晃人 / KOBAYASHI Akito",
  },
  {
    id: "cia-41",
    title: "[G30]統計物理学3",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Tue-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "cia-42",
    title: "解析学要論II",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "吉田 伸生 / YOSHIDA Nobuo",
  },
  {
    id: "cia-43",
    title: "数理解析・計算機数学III",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "LE GALL Francois Pierre M / LE GALL Francois Pierre Marcel",
  },
  {
    id: "cia-44",
    title: "生態学II",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "依田 憲 後藤 佑介 庄子 晶子 / YODA Ken GOTO Yusuke SHOJI Akiko",
  },
  {
    id: "cia-45",
    title: "[G30]生物物理学",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "Florence Tama",
  },
  {
    id: "cia-46",
    title: "生物物理学II",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "倭 剛久 / YAMATO Takahisa",
  },
  {
    id: "cia-47",
    title: "物性化学I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "須田 理行 / SUDA Masayuki",
  },
  {
    id: "cia-48",
    title: "[G30] 有機化学2",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "cia-49",
    title: "[G30] 植物生理学",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-2",
    teacher:
      "中道 範人 村中 智明 BELLEGARDE Fanny 前田 真一 / NAKAMICHI Norihito MURANAKA Tomoaki BELLEGARDE Fanny MAEDA Shin ichi",
  },
  {
    id: "cia-50",
    title: "無機化学実験",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-3",
    teacher:
      "邨次 智 唯 美津木 愛場 雄一郎 荘司 長三 福 健太郎 / MURATSUGU Satoshi TADA Mizuki AIBA Yuichiro SHOJI Osami FUKU Kentaro",
  },
  {
    id: "cia-51",
    title: "生物科学実験IV",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-3",
    teacher: "日比 正彦 / HIBI Masahiko",
  },
  {
    id: "cia-52",
    title: "地質学実験",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-3",
    teacher:
      "纐纈 佑衣 高橋 聡 藤原 慎一 道林 克禎 竹内 誠 加藤 丈典 束田 和弘 林 誠司 HUMBLET Marc Andre / KOUKETSU Yui TAKAHASHI Satoshi FUJIWARA Shin-ichi MICHIBAYASHI Katsuyoshi TAKEUCHI Makoto KATO Takenori TSUKADA Kazuhiro HAYASHI Seiji HUMBLET Marc Andre",
  },
  {
    id: "cia-53",
    title: "[G30][遠隔]計算機ソフトウェア2",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-4",
    teacher:
      "大塚 雄一 飯島 陽久 米澤 拓郎 小川 浩平 / OTSUKA Yuichi IIJIMA Haruhisa YONEZAWA Takuro OGAWA Kohei",
  },
  {
    id: "cia-54",
    title: "幾何学要論I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "泉 圭介 / IZUMI Keisuke",
  },
  {
    id: "cia-55",
    title: "幾何学続論",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "太田 啓史 / OHTA Hiroshi",
  },
  {
    id: "cia-56",
    title: "海洋科学",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "角皆 潤 / TSUNOGAI Urumu",
  },
  {
    id: "cia-57",
    title: "[G30] 有機化学4",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "cia-58",
    title: "統計物理学II",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "紺谷 浩 / KONTANI Hiroshi",
  },
  {
    id: "cia-59",
    title: "原子核物理学II",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "原田 正康 / HARADA Masayasu",
  },
  {
    id: "cia-60",
    title: "化学演習II",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-2",
    teacher:
      "斎藤 進 齋藤 雅明 河野 慎一郎 大城 宗一郎 橋谷 文貴 松田 晃孝 / SAITO Susumu SAITO Masaaki KAWANO Shinichiro OGI Soichiro HASHIYA Fumitaka MATSUDA Akitaka",
  },
  {
    id: "cia-61",
    title: "有機化学特論I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "斎藤 進 / SAITO Susumu",
  },
  {
    id: "cia-62",
    title: "地球化学分析法I及び実験",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "淺原 良浩 橋口 未奈子 / ASAHARA Yoshihiro HASHIGUCHI Minako",
  },
  {
    id: "cia-63",
    title: "地球惑星物理学演習I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "橋本 千尋 城野 信一 / HASHIMOTO Chihiro SIRONO Sin-iti",
  },
  {
    id: "cia-64",
    title: "[G30] 宇宙物理学",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "竹内 努 / TAKEUCHI Tsutomu",
  },
  {
    id: "cia-65",
    title: "[G30] 生化学4",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-2",
    teacher:
      "灘野 大太 石黒 澄衞 山篠 貴史 / NADANO Daita ISHIGURO Sumie YAMASHINO Takafumi",
  },
  {
    id: "cia-66",
    title: "数学演習VII",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "喜多 奈々緒 笹原 康浩 / KITA Nanao SASAHARA Yasuhiro",
  },
  {
    id: "cia-67",
    title: "代数学I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "BACHMANN Henrik lennart",
  },
  {
    id: "cia-68",
    title: "物理学演習III",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-3",
    teacher:
      "小林 晃人 戸部 和弘 木村 明洋 横山 修一郎 山影 相 山口 康宏 / KOBAYASHI Akito TOBE Kazuhiro KIMURA Akihiro YOKOYAMA Shuichiro YAMAKAGE Ai YAMAGUCHI Yasuhiro",
  },
  {
    id: "cia-69",
    title: "物理学実験I[αクラス]",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "cia-70",
    title: "量子力学II演習[βクラス]",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "小林 晃人 / KOBAYASHI Akito",
  },
  {
    id: "cia-71",
    title: "有機化学実験",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-3",
    teacher:
      "伊藤 英人 大城 宗一郎 八木 亜樹子 山口 茂弘 谷 洋介 村井 征史 / ITO Hideto OGI Soichiro YAGI Akiko YAMAGUCHI Shigehiro TANI Yosuke MURAI Masahito",
  },
  {
    id: "cia-72",
    title: "[G30]物理学セミナー1",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "堀井 泰之 / HORII Yasuyuki",
  },
  {
    id: "cia-73",
    title: "数学演習VIII",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "喜多 奈々緒 笹原 康浩 / KITA Nanao SASAHARA Yasuhiro",
  },
  {
    id: "cia-74",
    title: "数理物理学I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "菅野 浩明 / KANNO Hiroaki",
  },
  {
    id: "cia-75",
    title: "統計物理学II演習[βクラス]",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "小林 晃人 / KOBAYASHI Akito",
  },
  {
    id: "cia-76",
    title: "生物科学実験V",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "清水 貴史 / SHIMIZU Takashi",
  },
  {
    id: "cia-77",
    title: "数学演習IX",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "荒野 悠輝 木下 真也 / ARANO Yuki KINOSHITA Shinya",
  },
  {
    id: "cia-78",
    title: "統計物理学IV",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "河野 浩 / KOHNO Hiroshi",
  },
  {
    id: "cia-79",
    title: "宇宙物理学I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "中澤 知洋 / NAKAZAWA Kazuhiro",
  },
  {
    id: "cia-80",
    title: "数学演習X",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "荒野 悠輝 木下 真也 / ARANO Yuki KINOSHITA Shinya",
  },
  {
    id: "cia-81",
    title: "数理科学展望III",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "GARRIGUE JACQUES 林 正人 Neal Bez / GARRIGUE JACQUES HAYASHI Masahito Neal Bez",
  },
  {
    id: "cia-82",
    title: "生物物理学I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "内橋 貴之 / UCHIHASHI Takayuki",
  },
  {
    id: "cia-83",
    title: "宇宙物理学III",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "堀田 英之 / HOTTA Hideyuki",
  },
  {
    id: "cia-84",
    title: "生物化学特論",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "猪子 誠人 / INOKO Akihito",
  },
  {
    id: "cia-85",
    title: "地球惑星化学II",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "日高 洋 / HIDAKA Hiroshi",
  },
  {
    id: "cia-86",
    title: "[G30]物性物理学2",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "GELLOZ Bernard Jacques",
  },
  {
    id: "cia-87",
    title: "[G30] 細胞学4",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "柴田 秀樹 MATURANA Andres Daniel 小田 裕昭 / SHIBATA Hideki MATURANA Andres Daniel ODA Hiroaki",
  },
  {
    id: "cia-88",
    title: "応用数理I",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "永尾 太郎 / NAGAO Taro",
  },
  {
    id: "cia-89",
    title: "[G30]物理学演習4a",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "山影 相 / YAMAKAGE Ai",
  },
  {
    id: "cia-90",
    title: "[G30]物理学演習4b",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "山影 相 / YAMAKAGE Ai",
  },
  {
    id: "cia-91",
    title: "分子遺伝学IIa",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "松本 有樹修 / MATSUMOTO Akinobu",
  },
  {
    id: "cia-92",
    title: "生物学特論XV",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "八木 克将 髙橋 宏二 / YAGI Yoshimasa TAKAHASHI Koji",
  },
  {
    id: "cia-93",
    title: "分子生理学Ia",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "木下 俊則 髙橋 洋平 / KINOSHITA Toshinori TAKAHASHI Yohei",
  },
  {
    id: "cia-94",
    title: "細胞学Ia",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "大澤 志津江 井川 敬介 / OHSAWA Shizue IKAWA Keisuke",
  },
  {
    id: "cia-95",
    title: "遺伝学Ia",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-2",
    teacher:
      "嘉村 巧 西村 浩平 小原 圭介 / KAMURA Takumi NISHIMURA Kohei OBARA Keisuke",
  },
  {
    id: "cia-96",
    title: "現代測地学",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Wed-3",
    teacher: "伊藤 武男 / ITO Takeo",
  },
  {
    id: "cia-97",
    title: "生命化学Ia",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "日比 正彦 / HIBI Masahiko",
  },
  {
    id: "cia-98",
    title: "発生学Ib",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "田中 実 菊地 真理子 / TANAKA Minoru KIKUCHI Mariko",
  },
  {
    id: "cia-99",
    title: "生物学各論IIa",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-1",
    teacher:
      "五島 剛太 山田 萌恵 自見 直人 / GOSHIMA Gohta YAMADA Moe JIMI Naoto",
  },
  {
    id: "cia-100",
    title: "有機地球化学",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "三村 耕一 / MIMURA Koichi",
  },
  {
    id: "cia-101",
    title: "分子遺伝学Ia",
    section: "専門",
    department: "理",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "上川内 あづさ 石川 由希 田中 良弥 / KAMIKOUCHI Azusa ISHIKAWA Yuki TANAKA Ryoya",
  },
  {
    id: "cia-102",
    title: "生物学特論XVI",
    section: "専門",
    department: "理",
    semester: "春2",
    cellKey: "Mon-1",
    teacher: "八木 克将 髙橋 宏二 / YAGI Yoshimasa TAKAHASHI Koji",
  },
  {
    id: "cia-103",
    title: "発生学Ia",
    section: "専門",
    department: "理",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "久本 直毅 花房 洋 / HISAMOTO Naoki HANAFUSA Hiroshi",
  },
  {
    id: "cia-104",
    title: "細胞学Ib",
    section: "専門",
    department: "理",
    semester: "春2",
    cellKey: "Wed-1",
    teacher: "小田 祥久 / ODA Yoshihisa",
  },
  {
    id: "cia-105",
    title: "遺伝学Ib",
    section: "専門",
    department: "理",
    semester: "春2",
    cellKey: "Wed-2",
    teacher: "木下 専 / KINOSHITA Makoto",
  },
  {
    id: "cia-106",
    title: "生命化学Ib",
    section: "専門",
    department: "理",
    semester: "春2",
    cellKey: "Thu-1",
    teacher: "松林 嘉克 / MATSUBAYASHI Yoshikatsu",
  },
  {
    id: "cia-107",
    title: "分子生理学Ib",
    section: "専門",
    department: "理",
    semester: "春2",
    cellKey: "Thu-2",
    teacher: "打田 直行 / UCHIDA Naoyuki",
  },
  {
    id: "cia-108",
    title: "生命化学IIa",
    section: "専門",
    department: "理",
    semester: "春2",
    cellKey: "Fri-1",
    teacher: "土屋 雄一朗 / TSUCHIYA Yuichiro",
  },
  {
    id: "cia-109",
    title: "環境化学",
    section: "専門",
    department: "理",
    semester: "春2",
    cellKey: "Fri-1",
    teacher: "南 雅代 / MINAMI Masayo",
  },
  {
    id: "cia-110",
    title: "分子遺伝学Ib",
    section: "専門",
    department: "理",
    semester: "春2",
    cellKey: "Fri-2",
    teacher: "多田 安臣 / TADA Yasuomi",
  },
  {
    id: "cia-111",
    title: "現代数学基礎AII",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "糟谷 久矢 / KASUYA Hisashi",
  },
  {
    id: "cia-112",
    title: "数理科学展望I",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher:
      "植田 好道 納谷 信 谷本 祥 / UEDA Yoshimichi NAYATANI Shin TANIMOTO Sho",
  },
  {
    id: "cia-113",
    title: "無機物化機器分析",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher:
      "田中 健太郎 伏谷 瑞穂 邨次 智 須田 理行 唯 美津木 菱川 明栄 松下 未知雄 愛場 雄一郎 山田 泰之 荘司 長三 成田 秀樹 / TANAKA Kentaro FUSHITANI Mizuho MURATSUGU Satoshi SUDA Masayuki TADA Mizuki HISHIKAWA Akiyoshi MATSUSHITA Michio AIBA Yuichiro YAMADA Yasuyuki SHOJI Osami NARITA Hideki",
  },
  {
    id: "cia-114",
    title: "地球計測学演習",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "渡辺 俊樹 / WATANABE Toshiki",
  },
  {
    id: "cia-115",
    title: "数理物理学IV",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "濱中 真志 / HAMANAKA Masashi",
  },
  {
    id: "cia-116",
    title: "宇宙物理学II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "立原 研悟 / TACHIHARA Kengo",
  },
  {
    id: "cia-117",
    title: "生物無機化学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "荘司 長三 / SHOJI Osami",
  },
  {
    id: "cia-118",
    title: "地球惑星観測論",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "田所 敬一 / TADOKORO Keiichi",
  },
  {
    id: "cia-119",
    title: "[G30]素粒子物理学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "原田 正康 / HARADA Masayasu",
  },
  {
    id: "cia-120",
    title: "[G30]物性物理学3",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "谷山 智康 / TANIYAMA Tomoyasu",
  },
  {
    id: "cia-121",
    title: "計算数学基礎",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "GARRIGUE JACQUES 佐藤 猛 / GARRIGUE JACQUES SATOH Takeshi",
  },
  {
    id: "cia-122",
    title: "現代数学研究",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "岡田 聡一 / OKADA Soichi",
  },
  {
    id: "cia-123",
    title: "幾何学II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "白水 徹也 / SHIROMIZU Tetsuya",
  },
  {
    id: "cia-124",
    title: "生物化学実験",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher:
      "木村 康明 阿部 洋 橋谷 文貴 / KIMURA Yasuaki ABE Hiroshi HASHIYA Fumitaka",
  },
  {
    id: "cia-125",
    title: "生物科学実験法及び実験VI",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "清水 貴史 / SHIMIZU Takashi",
  },
  {
    id: "cia-126",
    title: "太陽系物理学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "渡邊 誠一郎 / WATANABE Sei-ichiro",
  },
  {
    id: "cia-127",
    title: "[G30] 生命科学実験II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "小嶋 誠司 清水 貴史 / KOJIMA Seiji SHIMIZU Takashi",
  },
  {
    id: "cia-128",
    title: "気候科学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "植村 立 松井 仁志 / UEMURA Ryu MATSUI Hitoshi",
  },
  {
    id: "cia-129",
    title: "生態学I",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "平野 恭弘 西田 佐知子 / HIRANO Yasuhiro NISHIDA Sachiko",
  },
  {
    id: "cia-130",
    title: "[G30]物性物理学1",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "GELLOZ Bernard Jacques",
  },
  {
    id: "cia-131",
    title: "[G30]量子力学2",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "cia-132",
    title: "代数学要論II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "髙橋 亮 / TAKAHASHI Ryo",
  },
  {
    id: "cia-133",
    title: "物理実験学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "奥村 曉 / OKUMURA Akira",
  },
  {
    id: "cia-134",
    title: "原子核物理学I",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "清水 裕彦 / SHIMIZU Hirohiko",
  },
  {
    id: "cia-135",
    title: "[G30]物理学セミナー2",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "田村 陽一 / TAMURA Yoichi",
  },
  {
    id: "cia-136",
    title: "[G30] 有機化学3",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "cia-137",
    title: "確率・統計基礎",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "森 立平 / MORI Ryuhei",
  },
  {
    id: "cia-138",
    title: "量子力学III",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "戸部 和弘 / TOBE Kazuhiro",
  },
  {
    id: "cia-139",
    title: "高分子化学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "関 隆広",
  },
  {
    id: "cia-140",
    title: "地質学特論",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "竹内 誠 高橋 聡 道林 克禎 林 誠司 纐纈 佑衣 / TAKEUCHI Makoto TAKAHASHI Satoshi MICHIBAYASHI Katsuyoshi HAYASHI Seiji KOUKETSU Yui",
  },
  {
    id: "cia-141",
    title: "[G30]計測工学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "栗本 宗明 / KURIMOTO Muneaki",
  },
  {
    id: "cia-142",
    title: "[G30] 生理・解剖学2",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "日比 正彦 / HIBI Masahiko",
  },
  {
    id: "cia-143",
    title: "現代数学基礎CIII",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "菅野 浩明 / KANNO Hiroaki",
  },
  {
    id: "cia-144",
    title: "数理科学展望IV",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher:
      "杉本 充 LE GALL Francois Pierre M 永尾 太郎 / SUGIMOTO Mitsuru LE GALL Francois Pierre Marcel NAGAO Taro",
  },
  {
    id: "cia-145",
    title: "物理学演習IV",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "山川 洋一 西川 宜彦 / YAMAKAWA Youichi NISHIKAWA Yoshihiko",
  },
  {
    id: "cia-146",
    title: "物理学実験II[βクラス]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "cia-147",
    title: "量子力学III演習[αクラス]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "山川 洋一 / YAMAKAWA Youichi",
  },
  {
    id: "cia-148",
    title: "生物科学実験法及び実験VII",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "岡田 泰和 / OKADA Yasukazu",
  },
  {
    id: "cia-149",
    title: "気象学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "篠田 太郎 / SHINODA Taro",
  },
  {
    id: "cia-150",
    title: "[G30]物理学実験1",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "cia-151",
    title: "確率論II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "吉田 伸生 / YOSHIDA Nobuo",
  },
  {
    id: "cia-152",
    title: "統計物理学III演習[αクラス]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "山川 洋一 / YAMAKAWA Youichi",
  },
  {
    id: "cia-153",
    title: "太陽地球系科学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "野澤 悟德 / NOZAWA Satonori",
  },
  {
    id: "cia-154",
    title: "現代数学基礎CII",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "菱田 俊明 / HISHIDA Toshiaki",
  },
  {
    id: "cia-155",
    title: "数理解析・計算機数学I",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "久保 仁 笹原 康浩 / KUBO Masashi SASAHARA Yasuhiro",
  },
  {
    id: "cia-156",
    title: "数理解析・計算機数学II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "平井 広志 / HIRAI Hiroshi",
  },
  {
    id: "cia-157",
    title: "化学物理学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "槇 亙介 / MAKI Kosuke",
  },
  {
    id: "cia-158",
    title: "化学統計力学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "青柳 忍 / AOYAGI Shinobu",
  },
  {
    id: "cia-159",
    title: "宇宙化学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "平原 靖大 / HIRAHARA Yasuhiro",
  },
  {
    id: "cia-160",
    title: "[G30]化学物理学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "内橋 貴之 / UCHIHASHI Takayuki",
  },
  {
    id: "cia-161",
    title: "プラズマ物理学I",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "渡邉 智彦 / WATANABE Tomohiko",
  },
  {
    id: "cia-162",
    title: "物性化学II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "成田 秀樹 須田 理行 / NARITA Hideki SUDA Masayuki",
  },
  {
    id: "cia-163",
    title: "生物圏進化学I",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "高橋 聡 林 誠司 / TAKAHASHI Satoshi HAYASHI Seiji",
  },
  {
    id: "cia-164",
    title: "情報科学概論II[βクラス]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "立原 研悟 / TACHIHARA Kengo",
  },
  {
    id: "cia-165",
    title: "物理学セミナー第VIIの1[I-1α]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "谷山 智康 谷口 博基 / TANIYAMA Tomoyasu TANIGUCHI Hiroki",
  },
  {
    id: "cia-166",
    title: "物理学セミナー第VIIIの1[II-1α]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "奥平 琢也 / OKUDAIRA Takuya",
  },
  {
    id: "cia-167",
    title: "物理学セミナー第IXの1[III-1α]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "田村 陽一 / TAMURA Yoichi",
  },
  {
    id: "cia-168",
    title: "物理学セミナー第Xの1[IV-1α]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "倭 剛久 / YAMATO Takahisa",
  },
  {
    id: "cia-169",
    title: "物理化学実験",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher:
      "松下 未知雄 稲井 直人 伏谷 瑞穂 柳井 毅 須田 理行 齋藤 雅明 菱川 明栄 松田 晃孝 成田 秀樹 藤本 和宏 / MATSUSHITA Michio INAI Naoto FUSHITANI Mizuho YANAI Takeshi SUDA Masayuki SAITO Masaaki HISHIKAWA Akiyoshi MATSUDA Akitaka NARITA Hideki FUJIMOTO Kazuhiro",
  },
  {
    id: "cia-170",
    title: "生物科学実験II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "松本 有樹修 / MATSUMOTO Akinobu",
  },
  {
    id: "cia-171",
    title: "[G30] Agricultural Science",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher: "井上 直子 / INOUE Naoko",
  },
  {
    id: "cia-172",
    title: "幾何学要論II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "森吉 仁志 / MORIYOSHI Hitoshi",
  },
  {
    id: "cia-173",
    title: "数学演習V",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher:
      "泉 圭介 久本 智之 松尾 信一郎 / IZUMI Keisuke HISAMOTO Tomoyuki MATSUO Shinichiroh",
  },
  {
    id: "cia-174",
    title: "代数学II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "柳田 伸太郎 / YANAGIDA Shintaro",
  },
  {
    id: "cia-175",
    title: "情報科学概論I",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "立原 研悟 小林 浩 / TACHIHARA Kengo KOBAYASHI Hiroshi",
  },
  {
    id: "cia-176",
    title: "物性物理学I",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "寺崎 一郎 / TERASAKI Ichiro",
  },
  {
    id: "cia-177",
    title: "地球惑星科学セミナーI",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "杉谷 健一郎 / SUGITANI Kenichiro",
  },
  {
    id: "cia-178",
    title: "[G30][遠隔]計算化学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "柳井 毅 / YANAI Takeshi",
  },
  {
    id: "cia-179",
    title: "数学演習VI",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher:
      "泉 圭介 久本 智之 松尾 信一郎 / IZUMI Keisuke HISAMOTO Tomoyuki MATSUO Shinichiroh",
  },
  {
    id: "cia-180",
    title: "解析学IV",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "Neal Bez",
  },
  {
    id: "cia-181",
    title: "統計物理学III",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "大成 誠一郎 / ONARI Seiichiro",
  },
  {
    id: "cia-182",
    title: "物性物理学II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "谷口 博基 / TANIGUCHI Hiroki",
  },
  {
    id: "cia-183",
    title: "有機化学特論II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "伊藤 英人 南保 正和 / ITO Hideto NAMBO Masakazu",
  },
  {
    id: "cia-184",
    title: "[G30]高分子化学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "上垣外 正己 / KAMIGAITO Masami",
  },
  {
    id: "cia-185",
    title: "現代数学基礎BII",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "中村 勇哉 / NAKAMURA Yusuke",
  },
  {
    id: "cia-186",
    title: "物理学セミナー第VIIの2[I-1β]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "下志万 貴博 小林 義明 / SHIMOJIMA Takahiro KOBAYASHI Yoshiaki",
  },
  {
    id: "cia-187",
    title: "物理学セミナー第VIIIの2[II-1β]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "南部 保貞 / NAMBU Yasusada",
  },
  {
    id: "cia-188",
    title: "物理学セミナー第IXの2[III-1β]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "國生 拓摩 / KOKUSHO Takuma",
  },
  {
    id: "cia-189",
    title: "物理学セミナー第Xの2[IV-1β]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "野口 巧 / NOGUCHI Takumi",
  },
  {
    id: "cia-190",
    title: "物理学実験II[αクラス]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "cia-191",
    title: "生物科学実験III",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "松本 有樹修 / MATSUMOTO Akinobu",
  },
  {
    id: "cia-192",
    title: "数値解析法及び演習",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "城野 信一 / SIRONO Sin-iti",
  },
  {
    id: "cia-193",
    title: "[G30]物理学演習3a",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "市來 淨與 / ICHIKI Kiyotomo",
  },
  {
    id: "cia-194",
    title: "[G30]物理学演習3b",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "市來 淨與 / ICHIKI Kiyotomo",
  },
  {
    id: "cia-195",
    title: "[G30]計算機ソフトウェア1",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "長谷川 浩 LU Shan / HASEGAWA Hiroshi LU Shan",
  },
  {
    id: "cia-196",
    title: "解析学要論III",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "杉本 充 / SUGIMOTO Mitsuru",
  },
  {
    id: "cia-197",
    title: "素粒子物理学I",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "飯嶋 徹 / IIJIMA Toru",
  },
  {
    id: "cia-198",
    title: "一般相対論",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "南部 保貞 / NAMBU Yasusada",
  },
  {
    id: "cia-199",
    title: "地震学",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "熊谷 博之 / KUMAGAI Hiroyuki",
  },
  {
    id: "cia-200",
    title: "[G30] 有機化学5",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "cia-201",
    title: "応用数理II",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "永尾 太郎 / NAGAO Taro",
  },
  {
    id: "cia-202",
    title: "物理学演習IV",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "山川 洋一 西川 宜彦 / YAMAKAWA Youichi NISHIKAWA Yoshihiko",
  },
  {
    id: "cia-203",
    title: "量子力学III演習[βクラス]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "山川 洋一 / YAMAKAWA Youichi",
  },
  {
    id: "cia-204",
    title: "地球化学分析法II及び実験",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "三村 耕一 / MIMURA Koichi",
  },
  {
    id: "cia-205",
    title: "統計物理学III演習[βクラス]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "山川 洋一 / YAMAKAWA Youichi",
  },
  {
    id: "cia-206",
    title: "[G30]統計物理学2",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "cia-207",
    title: "生物学各論Ia",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "岡田 泰和 / OKADA Yasukazu",
  },
  {
    id: "cia-208",
    title: "生物物理学Ia",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "廣明 秀一 / HIROAKI Hidekazu",
  },
  {
    id: "cia-209",
    title: "分子生理学IIa",
    section: "専門",
    department: "理",
    semester: "秋2",
    cellKey: "Mon-2",
    teacher: "乘本 裕明 / NORIMOTO Hiroaki",
  },
  {
    id: "cia-210",
    title: "生物物理学Ib",
    section: "専門",
    department: "理",
    semester: "秋2",
    cellKey: "Tue-1",
    teacher:
      "成田 哲博 瀧口 金吾 平子 善章 / NARITA Akihiro TAKIGUCHI Kingo HIRAKO Yoshiaki",
  },
  {
    id: "cia-211",
    title: "数学研究AI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "石井 亮 / ISHII Akira",
  },
  {
    id: "cia-212",
    title: "数学研究BI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "植田 好道 / UEDA Yoshimichi",
  },
  {
    id: "cia-213",
    title: "数学研究CI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "太田 啓史 / OHTA Hiroshi",
  },
  {
    id: "cia-214",
    title: "数学研究EI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "岡田 聡一 / OKADA Soichi",
  },
  {
    id: "cia-215",
    title: "数学研究FI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "GARRIGUE JACQUES",
  },
  {
    id: "cia-216",
    title: "数学研究GI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "白水 徹也 / SHIROMIZU Tetsuya",
  },
  {
    id: "cia-217",
    title: "数学研究HI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "杉本 充 / SUGIMOTO Mitsuru",
  },
  {
    id: "cia-218",
    title: "数学研究KI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "菱田 俊明 / HISHIDA Toshiaki",
  },
  {
    id: "cia-219",
    title: "数学研究LI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "古庄 英和 / FURUSHO Hidekazu",
  },
  {
    id: "cia-220",
    title: "数学研究MI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "Neal Bez",
  },
  {
    id: "cia-221",
    title: "数学研究NI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "森吉 仁志 / MORIYOSHI Hitoshi",
  },
  {
    id: "cia-222",
    title: "数学研究OI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "粟田 英資 / AWATA Hidetoshi",
  },
  {
    id: "cia-223",
    title: "数学研究PI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "JAERISCH Johannes Klaus B / JAERISCH Johannes Klaus Bernhard",
  },
  {
    id: "cia-224",
    title: "数学研究RI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "喜多 奈々緒 / KITA Nanao",
  },
  {
    id: "cia-225",
    title: "数学研究SI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "内藤 久資 / NAITO Hisashi",
  },
  {
    id: "cia-226",
    title: "数学研究UI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "中島 誠 / NAKASHIMA Makoto",
  },
  {
    id: "cia-227",
    title: "数学研究VI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "中村 勇哉 / NAKAMURA Yusuke",
  },
  {
    id: "cia-228",
    title: "数学研究WI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "林 孝宏 / HAYASHI Takahiro",
  },
  {
    id: "cia-229",
    title: "数学研究JI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "中西 知樹 / NAKANISHI Tomoki",
  },
  {
    id: "cia-230",
    title: "数学研究QI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "大久保 俊 / OHKUBO Shun",
  },
  {
    id: "cia-231",
    title: "数学研究YI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "松尾 信一郎 / MATSUO Shinichiroh",
  },
  {
    id: "cia-232",
    title: "統計・情報数理I",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "森 忠彦 / MORI Tadahiko",
  },
  {
    id: "cia-233",
    title: "統計・情報数理II",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher:
      "日下部 健児 清水 信広 西岡 隆 / KUSAKABE Kenji SHIMIZU Nobuhiro NISHIOKA Takashi",
  },
  {
    id: "cia-234",
    title: "代数学特別講義II",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "伊藤 由佳理 / ITO Yukari",
  },
  {
    id: "cia-235",
    title: "幾何学特別講義III",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "MAHMOUDI Sonia",
  },
  {
    id: "cia-236",
    title: "確率論特別講義I",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "桑江 一洋 / KUWAE Kazuhiro",
  },
  {
    id: "cia-237",
    title: "応用数理特別講義I",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "菅野 浩明 / KANNO Hiroaki",
  },
  {
    id: "cia-238",
    title: "生物物理学集中実験",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "村上 緑 / MURAKAMI Midori",
  },
  {
    id: "cia-239",
    title: "臨海実習",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher:
      "五島 剛太 森田 真布 自見 直人 / GOSHIMA Gohta MORITA Maho JIMI Naoto",
  },
  {
    id: "cia-240",
    title: "生物学特論IV",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "土屋 雄一朗 長谷部 光泰 / TSUCHIYA Yuichiro HASEBE Mitsuyasu",
  },
  {
    id: "cia-241",
    title: "生物学特論XIV",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "岩見 真吾 / IWAMI Shingo",
  },
  {
    id: "cia-242",
    title: "[G30] アドバンス生命科学実験法及び実験1",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "杉山 伸 / SUGIYAMA Shin",
  },
  {
    id: "cia-243",
    title: "[G30] アドバンス生命科学実験法及び実験2",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "杉山 伸 / SUGIYAMA Shin",
  },
  {
    id: "cia-244",
    title: "[G30] アドバンス生命科学実験法及び実験3",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "杉山 伸 / SUGIYAMA Shin",
  },
  {
    id: "cia-245",
    title: "[G30] アドバンス生命科学実験法及び実験4",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "杉山 伸 / SUGIYAMA Shin",
  },
  {
    id: "cia-246",
    title: "[G30] アドバンス生命科学実験法及び実験5",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "杉山 伸 / SUGIYAMA Shin",
  },
  {
    id: "cia-247",
    title: "[G30] 特別実験(卒業実験)",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "野間 健太郎 / NOMA Kentaro",
  },
  {
    id: "cia-248",
    title: "[G30] 臨海実習",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher:
      "五島 剛太 森田 真布 自見 直人 / GOSHIMA Gohta MORITA Maho JIMI Naoto",
  },
  {
    id: "cia-249",
    title: "数学研究AII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "石井 亮 / ISHII Akira",
  },
  {
    id: "cia-250",
    title: "数学研究BII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "植田 好道 / UEDA Yoshimichi",
  },
  {
    id: "cia-251",
    title: "数学研究CII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "太田 啓史 / OHTA Hiroshi",
  },
  {
    id: "cia-252",
    title: "数学研究DII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "大平 徹 / OHIRA Toru",
  },
  {
    id: "cia-253",
    title: "数学研究EII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "岡田 聡一 / OKADA Soichi",
  },
  {
    id: "cia-254",
    title: "数学研究FII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "GARRIGUE JACQUES",
  },
  {
    id: "cia-255",
    title: "数学研究GII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "白水 徹也 / SHIROMIZU Tetsuya",
  },
  {
    id: "cia-256",
    title: "数学研究HII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "杉本 充 / SUGIMOTO Mitsuru",
  },
  {
    id: "cia-257",
    title: "数学研究KII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "菱田 俊明 / HISHIDA Toshiaki",
  },
  {
    id: "cia-258",
    title: "数学研究LII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "古庄 英和 / FURUSHO Hidekazu",
  },
  {
    id: "cia-259",
    title: "数学研究MII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "Neal Bez",
  },
  {
    id: "cia-260",
    title: "数学研究NII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "森吉 仁志 / MORIYOSHI Hitoshi",
  },
  {
    id: "cia-261",
    title: "数学研究OII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "粟田 英資 / AWATA Hidetoshi",
  },
  {
    id: "cia-262",
    title: "数学研究PII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "JAERISCH Johannes Klaus B / JAERISCH Johannes Klaus Bernhard",
  },
  {
    id: "cia-263",
    title: "数学研究RII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "喜多 奈々緒 / KITA Nanao",
  },
  {
    id: "cia-264",
    title: "数学研究SII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "内藤 久資 / NAITO Hisashi",
  },
  {
    id: "cia-265",
    title: "数学研究UII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "中島 誠 / NAKASHIMA Makoto",
  },
  {
    id: "cia-266",
    title: "数学研究VII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "中村 勇哉 / NAKAMURA Yusuke",
  },
  {
    id: "cia-267",
    title: "数学研究WII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "林 孝宏 / HAYASHI Takahiro",
  },
  {
    id: "cia-268",
    title: "数学研究JII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "中西 知樹 / NAKANISHI Tomoki",
  },
  {
    id: "cia-269",
    title: "数学研究QII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "大久保 俊 / OHKUBO Shun",
  },
  {
    id: "cia-270",
    title: "数学研究YII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "松尾 信一郎 / MATSUO Shinichiroh",
  },
  {
    id: "cia-271",
    title: "幾何学特別講義II",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "BOURNE Christopher jack",
  },
  {
    id: "cia-272",
    title: "解析学特別講義IV",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "神本 晋吾 / KAMIMOTO Shingo",
  },
  {
    id: "cia-273",
    title: "数理物理学特別講義II",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "白石 潤一 / SHIRAISHI Junichi",
  },
  {
    id: "cia-274",
    title: "応用数理特別講義II",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "菅野 浩明 / KANNO Hiroaki",
  },
  {
    id: "cia-275",
    title: "応用数理特別講義III",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "平岡 裕章 / HIRAOKA Yasuaki",
  },
  {
    id: "cia-276",
    title: "生物学特論III",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "吉岡 泰 坂本 亘 / YOSHIOKA Yasushi SAKAMOTO Wataru",
  },
  {
    id: "cia-277",
    title: "生物学特論V",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "中野 俊詩 豊島 有 / NAKANO Syunji TOYOSHIMA Yu",
  },
  {
    id: "cia-278",
    title: "生物学特論XI",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "木下 俊則 増冨 祐司 / KINOSHITA Toshinori MASUTOMI Yuji",
  },
  {
    id: "cia-279",
    title: "生物学特論XII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "瀧口 金吾 野村 慎一郎 / TAKIGUCHI Kingo NOMURA Shin-ichiro",
  },
  {
    id: "cia-280",
    title: "生物学特論XIII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "小嶋 誠司 港 雄介 / KOJIMA Seiji MINATO Yusuke",
  },
  {
    id: "cia-281",
    title: "生物科学実験法及び実験X",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "岡田 泰和 / OKADA Yasukazu",
  },
  {
    id: "cia-282",
    title: "生物科学実験法及び実験XI",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "乘本 裕明 / NORIMOTO Hiroaki",
  },
  {
    id: "cia-283",
    title: "生物科学実験法及び実験XII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "乘本 裕明 / NORIMOTO Hiroaki",
  },
  {
    id: "cia-284",
    title: "生物科学実験法及び実験XIII",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "乘本 裕明 / NORIMOTO Hiroaki",
  },
  {
    id: "cia-285",
    title: "生物科学実験法及び実験XIV",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "乘本 裕明 / NORIMOTO Hiroaki",
  },
  {
    id: "cia-286",
    title: "[G30]物理学特別実験",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "田村 陽一 / TAMURA Yoichi",
  },
  {
    id: "cia-287",
    title: "[G30]特別実験(卒業研究)",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "斎藤 進 / SAITO Susumu",
  },
  {
    id: "cia-288",
    title: "[G30] 特別実験(卒業実験)",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "野間 健太郎 / NOMA Kentaro",
  },
  {
    id: "cia-289",
    title: "物理学講究",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 原田 正康 / HARADA Masayasu",
  },
  {
    id: "cia-290",
    title: "物理学特別実験",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 田村 陽一 / TAMURA Yoichi",
  },
  {
    id: "cia-291",
    title: "物理学講究",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 原田 正康 / HARADA Masayasu",
  },
  {
    id: "cia-292",
    title: "特別実験",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 斎藤 進 / SAITO Susumu",
  },
  {
    id: "cia-293",
    title: "卒業実験",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 小田 祥久 / ODA Yoshihisa",
  },
  {
    id: "cia-294",
    title: "博物館実習1",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 西田 佐知子 藤原 慎一 / NISHIDA Sachiko FUJIWARA Shin-ichi",
  },
  {
    id: "cia-295",
    title: "博物館実習2",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 新美 倫子 門脇 誠二 / NIIMI Michiko KADOWAKI Seiji",
  },
  {
    id: "cia-296",
    title: "フィールドセミナーI(地球科学野外巡検)",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 竹内 誠 高橋 聡 道林 克禎 林 誠司 纐纈 佑衣 / TAKEUCHI Makoto TAKAHASHI Satoshi MICHIBAYASHI Katsuyoshi HAYASHI Seiji KOUKETSU Yui",
  },
  {
    id: "cia-297",
    title: "地球惑星科学特別研究",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 高野 雅夫 / TAKANO Masao",
  },
  {
    id: "cia-298",
    title: "地球惑星科学特別研究",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 竹内 誠 / TAKEUCHI Makoto",
  },
  {
    id: "cia-299",
    title: "地球惑星科学特別研究",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 道林 克禎 / MICHIBAYASHI Katsuyoshi",
  },
  {
    id: "cia-300",
    title: "地球惑星科学特別研究",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 高橋 聡 / TAKAHASHI Satoshi",
  },
  {
    id: "cia-301",
    title: "地球惑星科学特別研究",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 渡邊 誠一郎 / WATANABE Sei-ichiro",
  },
  {
    id: "cia-302",
    title: "地球惑星科学特別研究",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 坂井 亜規子 / SAKAI Akiko",
  },
  {
    id: "cia-303",
    title: "地球惑星科学特別研究",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 三村 耕一 / MIMURA Koichi",
  },
  {
    id: "cia-304",
    title: "地球惑星科学特別研究",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 日高 洋 / HIDAKA Hiroshi",
  },
  {
    id: "cia-305",
    title: "地球惑星科学特別研究",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 平原 靖大 / HIRAHARA Yasuhiro",
  },
  {
    id: "cia-306",
    title: "地球惑星科学特別研究",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher: "Full-year course Intensive(Sp-Fa) Other Other 依田 憲 / YODA Ken",
  },
  {
    id: "cia-307",
    title: "フィールドセミナーII",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 道林 克禎 / MICHIBAYASHI Katsuyoshi",
  },
  {
    id: "cia-308",
    title: "大気水圏フィールドセミナーI",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 松井 仁志 永尾 一平 篠田 雅人 / MATSUI Hitoshi NAGAO Ippei SHINODA Masato",
  },
  {
    id: "cia-309",
    title: "大気水圏フィールドセミナーII",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 中川 書子 角皆 潤 / NAKAGAWA Fumiko TSUNOGAI Urumu",
  },
  {
    id: "cia-310",
    title: "博物館実習3",
    section: "専門",
    department: "理",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 吉田 英一 束田 和弘 / YOSHIDA Hidekazu TSUKADA Kazuhiro",
  },
  {
    id: "cia-311",
    title: "数学研究DI",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "大平 徹 / OHIRA Toru",
  },
  {
    id: "cia-312",
    title: "情報科学概論II[αクラス]",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "立原 研悟 三石 郁之 / TACHIHARA Kengo MITSUISHI Ikuyuki",
  },
  {
    id: "cia-313",
    title: "地質調査(春)",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "高橋 聡 / TAKAHASHI Satoshi",
  },
  {
    id: "cia-314",
    title: "地質調査(秋)",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "道林 克禎 / MICHIBAYASHI Katsuyoshi",
  },
  {
    id: "cia-315",
    title: "[G30]物理学講究",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "棚橋 誠治 / TANABASHI Masaharu",
  },
  {
    id: "cia-316",
    title: "[G30]物理学講究",
    section: "専門",
    department: "理",
    semester: "秋集中",
    teacher: "原田 正康 / HARADA Masayasu",
  },
  {
    id: "cia-317",
    title: "[G30]物理学特別実験",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "野口 巧 / NOGUCHI Takumi",
  },
  {
    id: "cia-318",
    title: "[G30]理学部化学実験",
    section: "専門",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "藤本 和宏 / FUJIMOTO Kazuhiro",
  },
  {
    id: "cia-319",
    title: "[G30]特別実験(卒業研究)",
    section: "専門",
    department: "理",
    semester: "春集中",
    teacher: "斎藤 進 / SAITO Susumu",
  },
];
