import { Course } from "../courses";
export const CIA_B_COURSES: Course[] = [
  {
    id: "cia_b-1",
    title: "量子化学I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "柳井 毅 / YANAI Takeshi",
  },
  {
    id: "cia_b-2",
    title: "[G30] 無機材料化学2",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "cia_b-3",
    title: "[G30] 量子化学1",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "PHUNG Quan manh",
  },
  {
    id: "cia_b-4",
    title: "無機化学I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "唯 美津木 / TADA Mizuki",
  },
  {
    id: "cia_b-5",
    title: "有機化学III",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "伊藤 英人 / ITO Hideto",
  },
  {
    id: "cia_b-6",
    title: "地球生物学",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "藤原 慎一 門脇 誠二 / FUJIWARA Shin-ichi KADOWAKI Seiji",
  },
  {
    id: "cia_b-7",
    title: "[G30] 量子化学3",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "藤本 和宏 / FUJIMOTO Kazuhiro",
  },
  {
    id: "cia_b-8",
    title: "[G30] 生化学2",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "cia_b-9",
    title: "現代数学基礎AI",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "森吉 仁志 / MORIYOSHI Hitoshi",
  },
  {
    id: "cia_b-10",
    title: "数理物理学II演習",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "原田 正康 / HARADA Masayasu",
  },
  {
    id: "cia_b-11",
    title: "岩石学",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "道林 克禎 / MICHIBAYASHI Katsuyoshi",
  },
  {
    id: "cia_b-12",
    title: "電磁気学II演習",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "原田 正康 / HARADA Masayasu",
  },
  {
    id: "cia_b-13",
    title: "基礎細胞学I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-4",
    teacher:
      "平子 善章 小原 圭介 成田 哲博 / HIRAKO Yoshiaki OBARA Keisuke NARITA Akihiro",
  },
  {
    id: "cia_b-14",
    title: "地球惑星物理学基礎",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "橋本 千尋 / HASHIMOTO Chihiro",
  },
  {
    id: "cia_b-15",
    title: "現代数学基礎BI",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "中西 知樹 / NAKANISHI Tomoki",
  },
  {
    id: "cia_b-16",
    title: "数理物理学I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "柳 哲文 / YOO Chulmoon",
  },
  {
    id: "cia_b-17",
    title: "無機化学IV",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "荘司 長三 / SHOJI Osami",
  },
  {
    id: "cia_b-18",
    title: "[G30] 無機化学1",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "cia_b-19",
    title: "解析力学I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "原田 正康 / HARADA Masayasu",
  },
  {
    id: "cia_b-20",
    title: "解析力学",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "原田 正康 / HARADA Masayasu",
  },
  {
    id: "cia_b-21",
    title: "物理化学基礎",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "菱川 明栄 / HISHIKAWA Akiyoshi",
  },
  {
    id: "cia_b-22",
    title: "岩石学実験",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "道林 克禎 竹内 誠 纐纈 佑衣 / MICHIBAYASHI Katsuyoshi TAKEUCHI Makoto KOUKETSU Yui",
  },
  {
    id: "cia_b-23",
    title: "堆積地質学",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "吉田 英一 / YOSHIDA Hidekazu",
  },
  {
    id: "cia_b-24",
    title: "[G30]電磁気学",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "cia_b-25",
    title: "数学演習III",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-3",
    teacher:
      "JAERISCH Johannes Klaus B 佐藤 猛 大須賀 けん斗 / JAERISCH Johannes Klaus Bernhard SATOH Takeshi OSUGA Kento",
  },
  {
    id: "cia_b-26",
    title: "化学講究I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "斎藤 進 / SAITO Susumu",
  },
  {
    id: "cia_b-27",
    title: "地球惑星物理学概論",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "並木 敦子 熊谷 博之 / NAMIKI Atsuko KUMAGAI Hiroyuki",
  },
  {
    id: "cia_b-28",
    title: "[G30]化学講究1",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "斎藤 進 / SAITO Susumu",
  },
  {
    id: "cia_b-29",
    title: "数学演習IV",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "JAERISCH Johannes Klaus B 佐藤 猛 大須賀 けん斗 / JAERISCH Johannes Klaus Bernhard SATOH Takeshi OSUGA Kento",
  },
  {
    id: "cia_b-30",
    title: "地球惑星化学I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "三村 耕一 日高 洋 / MIMURA Koichi HIDAKA Hiroshi",
  },
  {
    id: "cia_b-31",
    title: "[G30]物理学演習2c",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "白戸 高志 / SHIROTO Takashi",
  },
  {
    id: "cia_b-32",
    title: "現代数学基礎CI",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "加藤 淳 / KATO Jun",
  },
  {
    id: "cia_b-33",
    title: "有機化学I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "山口 茂弘 / YAMAGUCHI Shigehiro",
  },
  {
    id: "cia_b-34",
    title: "基礎生物学演習I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "杉山 伸 平子 善章 / SUGIYAMA Shin HIRAKO Yoshiaki",
  },
  {
    id: "cia_b-35",
    title: "基礎生物学演習I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "荒木 聡彦 岩波 翔也 / ARAKI Satohiko IWANAMI Shoya",
  },
  {
    id: "cia_b-36",
    title: "基礎生物学演習I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "中野 俊詩 西村 浩平 / NAKANO Syunji NISHIMURA Kohei",
  },
  {
    id: "cia_b-37",
    title: "基礎生物学演習I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "野間 健太郎 清水 貴史 / NOMA Kentaro SHIMIZU Takashi",
  },
  {
    id: "cia_b-38",
    title: "地球惑星数学及び演習",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "城野 信一 / SIRONO Sin-iti",
  },
  {
    id: "cia_b-39",
    title: "[G30] 遺伝学2",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "cia_b-40",
    title: "数理物理学II",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "大成 誠一郎 / ONARI Seiichiro",
  },
  {
    id: "cia_b-41",
    title: "分析化学I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "田中 健太郎 / TANAKA Kentaro",
  },
  {
    id: "cia_b-42",
    title: "流体力学",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "坂井 亜規子 / SAKAI Akiko",
  },
  {
    id: "cia_b-43",
    title: "[G30] 無機化学3",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "cia_b-44",
    title: "物理学演習I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-3",
    teacher:
      "原田 正康 槇 亙介 河野 浩 柳 哲文 三野 広幸 木村 明洋 市來 淨與 山川 洋一 山口 康宏 / HARADA Masayasu MAKI Kosuke KOHNO Hiroshi YOO Chulmoon MINO Hiroyuki KIMURA Akihiro ICHIKI Kiyotomo YAMAKAWA Youichi YAMAGUCHI Yasuhiro",
  },
  {
    id: "cia_b-45",
    title: "数理物理学I演習",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-3",
    teacher: "原田 正康 / HARADA Masayasu",
  },
  {
    id: "cia_b-46",
    title: "解析力学演習",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "原田 正康 / HARADA Masayasu",
  },
  {
    id: "cia_b-47",
    title: "[G30] 生理・発生生物学",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "cia_b-48",
    title: "[G30] 物理化学2",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "PHUNG Quan manh",
  },
  {
    id: "cia_b-49",
    title: "[G30]解析力学2",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "重森 正樹 / SHIGEMORI Masaki",
  },
  {
    id: "cia_b-50",
    title: "[G30] 量子力学1",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "重森 正樹 / SHIGEMORI Masaki",
  },
  {
    id: "cia_b-51",
    title: "[G30] 数学演習2a",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "BOURNE Christopher jack",
  },
  {
    id: "cia_b-52",
    title: "[G30] 数学演習2b",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "BACHMANN Henrik lennart",
  },
  {
    id: "cia_b-53",
    title: "[G30]物理学基礎演習1b",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Thu-5",
    teacher: "梅畑 豪紀 / UMEHATA Hideki",
  },
  {
    id: "cia_b-54",
    title: "物理化学",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "須田 理行 柳井 毅 / SUDA Masayuki YANAI Takeshi",
  },
  {
    id: "cia_b-55",
    title: "量子化学II",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "菱川 明栄 / HISHIKAWA Akiyoshi",
  },
  {
    id: "cia_b-56",
    title: "[G30] 地球環境科学",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "HUMBLET Marc Andre",
  },
  {
    id: "cia_b-57",
    title: "生物化学I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "阿部 洋 / ABE Hiroshi",
  },
  {
    id: "cia_b-58",
    title: "地球惑星科学の最前線",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Fri-3",
    teacher:
      "纐纈 佑衣 渡邊 誠一郎 高橋 聡 藤原 慎一 高野 雅夫 加藤 丈典 藤田 耕史 伊藤 武男 日高 洋 植村 立 庄子 晶子 / KOUKETSU Yui WATANABE Sei-ichiro TAKAHASHI Satoshi FUJIWARA Shin-ichi TAKANO Masao KATO Takenori FUJITA Koji ITO Takeo HIDAKA Hiroshi UEMURA Ryu SHOJI Akiko",
  },
  {
    id: "cia_b-59",
    title: "[G30]物理学演習2a",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Fri-3",
    teacher:
      "WOJDYLO John Andrew 下志万 貴博 王 子謙 / WOJDYLO John Andrew SHIMOJIMA Takahiro WANG Ziqian",
  },
  {
    id: "cia_b-60",
    title: "[G30]物理学演習2b",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "重森 正樹 寺田 隆広 / SHIGEMORI Masaki TERADA Takahiro",
  },
  {
    id: "cia_b-61",
    title: "数学展望I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Fri-4",
    teacher: "納谷 信 / NAYATANI Shin",
  },
  {
    id: "cia_b-62",
    title: "現代物理学序論I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Fri-4",
    teacher:
      "飯嶋 徹 田村 陽一 野口 巧 谷山 智康 / IIJIMA Toru TAMURA Yoichi NOGUCHI Takumi TANIYAMA Tomoyasu",
  },
  {
    id: "cia_b-63",
    title: "数学演習I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Fri-5",
    teacher: "加藤 淳 / KATO Jun",
  },
  {
    id: "cia_b-64",
    title: "[G30]物理学基礎演習2",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Fri-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "cia_b-65",
    title: "構造地質学",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "竹内 誠 / TAKEUCHI Makoto",
  },
  {
    id: "cia_b-66",
    title: "基礎遺伝学I",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "大嶋 篤典 八木 克将 / OSHIMA Atsunori YAGI Yoshimasa",
  },
  {
    id: "cia_b-67",
    title: "基礎生物物理学Ia",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "廣明 秀一 / HIROAKI Hidekazu",
  },
  {
    id: "cia_b-68",
    title: "基礎生化学Ia",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "花房 洋 / HANAFUSA Hiroshi",
  },
  {
    id: "cia_b-69",
    title: "基礎生化学IIa",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-3",
    teacher: "井原 邦夫 / IHARA Kunio",
  },
  {
    id: "cia_b-70",
    title: "基礎生理学Ia",
    section: "専門基礎",
    department: "理",
    semester: "春1",
    cellKey: "Wed-4",
    teacher:
      "木下 俊則 中野 俊詩 髙橋 洋平 / KINOSHITA Toshinori NAKANO Syunji TAKAHASHI Yohei",
  },
  {
    id: "cia_b-71",
    title: "テクトニクス",
    section: "専門基礎",
    department: "理",
    semester: "春2",
    cellKey: "Mon-1",
    teacher: "竹内 誠 / TAKEUCHI Makoto",
  },
  {
    id: "cia_b-72",
    title: "基礎遺伝学II",
    section: "専門基礎",
    department: "理",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "多田 安臣 野元 美佳 / TADA Yasuomi NOMOTO Mika",
  },
  {
    id: "cia_b-73",
    title: "基礎生化学Ib",
    section: "専門基礎",
    department: "理",
    semester: "春2",
    cellKey: "Mon-3",
    teacher: "西村 浩平 / NISHIMURA Kohei",
  },
  {
    id: "cia_b-74",
    title: "基礎生物物理学Ib",
    section: "専門基礎",
    department: "理",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "兒玉 哲也 太田 元規 / KODAMA Tetsuya OTA Motonori",
  },
  {
    id: "cia_b-75",
    title: "基礎生化学IIb",
    section: "専門基礎",
    department: "理",
    semester: "春2",
    cellKey: "Wed-3",
    teacher: "清水 貴史 / SHIMIZU Takashi",
  },
  {
    id: "cia_b-76",
    title: "[G30]量子化学2",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "PHUNG Quan manh",
  },
  {
    id: "cia_b-77",
    title: "[G30] 生化学1",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "cia_b-78",
    title: "[G30] 無機化学2",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "cia_b-79",
    title: "[G30] 生理・解剖学1",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "cia_b-80",
    title: "[G30] 細胞学2",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "野間 健太郎 / NOMA Kentaro",
  },
  {
    id: "cia_b-81",
    title: "[G30] 分析化学",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "cia_b-82",
    title: "電磁気学",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "金田 英宏 / KANEDA Hidehiro",
  },
  {
    id: "cia_b-83",
    title: "無機化学III",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "荘司 長三 / SHOJI Osami",
  },
  {
    id: "cia_b-84",
    title: "基礎遺伝学III",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "松本 有樹修 渡邉 正勝 / MATSUMOTO Akinobu WATANABE Masakatsu",
  },
  {
    id: "cia_b-85",
    title: "地球惑星物理学実験法及び実験I",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "伊藤 武男 並木 敦子 市原 寛 前田 裕太 寺川 寿子 田所 敬一 相木 秀則 鷺谷 威 須藤 健悟 渡辺 俊樹 / ITO Takeo NAMIKI Atsuko ICHIHARA Hiroshi MAEDA Yuta TERAKAWA Toshiko TADOKORO Keiichi AIKI Hidenori SAGIYA Takeshi SUDOH Kengo WATANABE Toshiki",
  },
  {
    id: "cia_b-86",
    title: "[G30] 無機材料化学1",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "cia_b-87",
    title: "化学講究II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "斎藤 進 / SAITO Susumu",
  },
  {
    id: "cia_b-88",
    title: "[G30]化学講究2",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "斎藤 進 / SAITO Susumu",
  },
  {
    id: "cia_b-89",
    title: "[G30] 数学演習1a",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "RICHARD Serge charles",
  },
  {
    id: "cia_b-90",
    title: "[G30] 数学演習1b",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "BACHMANN Henrik lennart",
  },
  {
    id: "cia_b-91",
    title: "[G30]数理物理学演習1",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "WOJDYLO John Andrew 井黒 就平 / WOJDYLO John Andrew IGURO Shuhei",
  },
  {
    id: "cia_b-92",
    title: "[G30]数理物理学1",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "cia_b-93",
    title: "物理学基礎演習I[クラス1-6]",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "小林 晃人 / KOBAYASHI Akito",
  },
  {
    id: "cia_b-94",
    title: "物理学基礎演習I[クラス7-12]",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "田村 陽一 / TAMURA Yoichi",
  },
  {
    id: "cia_b-95",
    title: "分析化学II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "田中 健太郎 / TANAKA Kentaro",
  },
  {
    id: "cia_b-96",
    title: "基礎細胞学II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "久本 直毅 花房 洋 / HISAMOTO Naoki HANAFUSA Hiroshi",
  },
  {
    id: "cia_b-97",
    title: "地球環境学",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher:
      "高野 雅夫 中川 書子 宮坂 隆文 長田 和雄 / TAKANO Masao NAKAGAWA Fumiko MIYASAKA Takafumi OSADA Kazuo",
  },
  {
    id: "cia_b-98",
    title: "数学演習II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "川村 友美 / KAWAMURA Tomomi",
  },
  {
    id: "cia_b-99",
    title: "統計物理学I",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "宮崎 州正 / MIYAZAKI Kunimasa",
  },
  {
    id: "cia_b-100",
    title: "無機化学II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "唯 美津木 / TADA Mizuki",
  },
  {
    id: "cia_b-101",
    title: "地球内部物性論",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "熊谷 博之 / KUMAGAI Hiroyuki",
  },
  {
    id: "cia_b-102",
    title: "[G30] 遺伝学3",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "杉山 伸 八木 克将 野間 健太郎 / SUGIYAMA Shin YAGI Yoshimasa NOMA Kentaro",
  },
  {
    id: "cia_b-103",
    title: "数学展望II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "柳田 伸太郎 / YANAGIDA Shintaro",
  },
  {
    id: "cia_b-104",
    title: "地球ダイナミクス",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "道林 克禎 寺川 寿子 / MICHIBAYASHI Katsuyoshi TERAKAWA Toshiko",
  },
  {
    id: "cia_b-105",
    title: "生物化学II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "阿部 洋 / ABE Hiroshi",
  },
  {
    id: "cia_b-106",
    title: "[遠隔]計算化学概論",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "柳井 毅 / YANAI Takeshi",
  },
  {
    id: "cia_b-107",
    title: "基礎生物学演習II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "井原 邦夫 石川 由希 / IHARA Kunio ISHIKAWA Yuki",
  },
  {
    id: "cia_b-108",
    title: "基礎生物学演習II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "佐藤 良勝 大澤 志津江 / SATO Yoshikatsu OHSAWA Shizue",
  },
  {
    id: "cia_b-109",
    title: "基礎生物学演習II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "成田 哲博 小原 圭介 / NARITA Akihiro OBARA Keisuke",
  },
  {
    id: "cia_b-110",
    title: "基礎生物学演習II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher:
      "打田 直行 乘本 裕明 廣田 毅 / UCHIDA Naoyuki NORIMOTO Hiroaki HIROTA Tsuyoshi",
  },
  {
    id: "cia_b-111",
    title: "[G30] 物理化学1",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "PHUNG Quan manh",
  },
  {
    id: "cia_b-112",
    title: "量子力学I",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "前川 展祐 / MAEKAWA Nobuhiro",
  },
  {
    id: "cia_b-113",
    title: "有機化学II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "八木 亜樹子 / YAGI Akiko",
  },
  {
    id: "cia_b-114",
    title: "[G30] 遺伝学1",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "cia_b-115",
    title: "[G30] 細胞学3",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "木下 専 / KINOSHITA Makoto",
  },
  {
    id: "cia_b-116",
    title: "力学特論演習",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "宮崎 州正 / MIYAZAKI Kunimasa",
  },
  {
    id: "cia_b-117",
    title: "量子力学I演習",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "宮崎 州正 / MIYAZAKI Kunimasa",
  },
  {
    id: "cia_b-118",
    title: "[G30]数理物理学演習2",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "藤田 隆明 遠藤 知弘 / FUJITA Takaaki ENDO Tomohiro",
  },
  {
    id: "cia_b-119",
    title: "[G30] 有機化学1",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "cia_b-120",
    title: "同位体地球化学",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "淺原 良浩 / ASAHARA Yoshihiro",
  },
  {
    id: "cia_b-121",
    title: "[G30] 地球惑星科学",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "HUMBLET Marc Andre",
  },
  {
    id: "cia_b-122",
    title: "解析力学II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "前川 展祐 / MAEKAWA Nobuhiro",
  },
  {
    id: "cia_b-123",
    title: "力学特論",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "前川 展祐 / MAEKAWA Nobuhiro",
  },
  {
    id: "cia_b-124",
    title: "熱力学基礎",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "渡邊 誠一郎 / WATANABE Sei-ichiro",
  },
  {
    id: "cia_b-125",
    title: "[G30] 生化学3",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher:
      "小嶋 誠司 打田 直行 廣田 毅 吉成 晃 / KOJIMA Seiji UCHIDA Naoyuki HIROTA Tsuyoshi YOSHINARI Akira",
  },
  {
    id: "cia_b-126",
    title: "物理学演習II",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "宮崎 州正 / MIYAZAKI Kunimasa",
  },
  {
    id: "cia_b-127",
    title: "電磁気学演習",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "宮崎 州正 / MIYAZAKI Kunimasa",
  },
  {
    id: "cia_b-128",
    title: "大気水圏科学基礎",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "須藤 健悟 中塚 武 / SUDOH Kengo NAKATSUKA Takeshi",
  },
  {
    id: "cia_b-129",
    title: "統計物理学I演習",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "宮崎 州正 / MIYAZAKI Kunimasa",
  },
  {
    id: "cia_b-130",
    title: "地質調査法",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "道林 克禎 / MICHIBAYASHI Katsuyoshi",
  },
  {
    id: "cia_b-131",
    title: "基礎発生学Ia",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "日比 正彦 / HIBI Masahiko",
  },
  {
    id: "cia_b-132",
    title: "基礎生化学IIIa",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "松林 嘉克 髙橋 宏二 / MATSUBAYASHI Yoshikatsu TAKAHASHI Koji",
  },
  {
    id: "cia_b-133",
    title: "生命理学特別講義I",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "廣田 毅 佐々木 武馬 小原 圭介 佐藤 良勝 中野 俊詩 石川 由希 自見 直人 / HIROTA Tsuyoshi SASAKI Takema OBARA Keisuke SATO Yoshikatsu NAKANO Syunji ISHIKAWA Yuki JIMI Naoto",
  },
  {
    id: "cia_b-134",
    title: "基礎発生学Ib",
    section: "専門基礎",
    department: "理",
    semester: "秋2",
    cellKey: "Mon-1",
    teacher: "小田 祥久 佐々木 武馬 / ODA Yoshihisa SASAKI Takema",
  },
  {
    id: "cia_b-135",
    title: "基礎生化学IIIb",
    section: "専門基礎",
    department: "理",
    semester: "秋2",
    cellKey: "Wed-2",
    teacher:
      "嘉村 巧 小原 圭介 廣田 毅 / KAMURA Takumi OBARA Keisuke HIROTA Tsuyoshi",
  },
  {
    id: "cia_b-136",
    title: "生命理学特別講義II",
    section: "専門基礎",
    department: "理",
    semester: "秋2",
    cellKey: "Wed-2",
    teacher:
      "西村 浩平 吉成 晃 野元 美佳 岩波 翔也 西川 将司 兼子 拓也 大西 真理 / NISHIMURA Kohei YOSHINARI Akira NOMOTO Mika IWANAMI Shoya NISHIKAWA Masashi KANEKO Takuya OHNISHI Mari",
  },
  {
    id: "cia_b-137",
    title: "[G30]解析力学1",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-5",
    teacher: "重森 正樹 / SHIGEMORI Masaki",
  },
  {
    id: "cia_b-138",
    title: "[G30]数理物理学2",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "藤田 隆明 遠藤 知弘 / FUJITA Takaaki ENDO Tomohiro",
  },
  {
    id: "cia_b-139",
    title: "[G30]統計物理学1",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "cia_b-140",
    title: "[G30]物理学演習1a",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "洗平 昌晃 / ARAIDAI Masaaki",
  },
  {
    id: "cia_b-141",
    title: "[G30]物理学演習1b",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "cia_b-142",
    title: "[G30]物理学基礎演習1a",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "ESCRIVA MANAS Alberto",
  },
  {
    id: "cia_b-143",
    title: "[G30] 細胞学1",
    section: "専門基礎",
    department: "理",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "野間 健太郎 / NOMA Kentaro",
  },
];
