import { Course } from "../courses";
export const ECO_B_COURSES: Course[] = [
  {
    id: "eco_b-1",
    title: "経営II",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "宮﨑 正也 / MIYAZAKI Masaya",
  },
  {
    id: "eco_b-2",
    title: "ミクロ経済学II",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "花薗 誠 三好 向洋 / HANAZONO Makoto MIYOSHI Kouyou",
  },
  {
    id: "eco_b-3",
    title: "ミクロ経済学II(E)",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "金 健輝 / KIM Kunhyui",
  },
  {
    id: "eco_b-4",
    title: "専門基礎演習II(E)",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "金 健輝 / KIM Kunhyui",
  },
  {
    id: "eco_b-5",
    title: "政治経済学II",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "藤田 真哉 / FUJITA Shinya",
  },
  {
    id: "eco_b-6",
    title: "社会科学のための日本語II(E)",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-5",
    teacher: "瓦井 由紀 松尾 陽 / KAWARAI Yuki MATSUO Yoh",
  },
  {
    id: "eco_b-7",
    title: "エコノメトリックスII(E)",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "金 健輝 / KIM Kunhyui",
  },
  {
    id: "eco_b-8",
    title: "一般経済史II",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "福澤 直樹 / FUKUZAWA Naoki",
  },
  {
    id: "eco_b-9",
    title: "応用経営学II(E)",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "岡島 広子 / OKAJIMA Hiroko",
  },
  {
    id: "eco_b-10",
    title: "マクロ経済学II",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-5",
    teacher: "工藤 教孝 / KUDOH Noritaka",
  },
  {
    id: "eco_b-11",
    title: "専門基礎演習IV(E)",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-5",
    teacher: "岡島 広子 / OKAJIMA Hiroko",
  },
  {
    id: "eco_b-12",
    title: "財務諸表II",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "小沢 浩 / OZAWA Hiroshi",
  },
  {
    id: "eco_b-13",
    title: "計量経済II",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "園田 正 / SONODA Tadashi",
  },
  {
    id: "eco_b-14",
    title: "社会科学のための日本語III(E)",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "瓦井 由紀 松尾 陽 / KAWARAI Yuki MATSUO Yoh",
  },
  {
    id: "eco_b-15",
    title: "会計学II(E)",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-5",
    teacher: "姜 周亨 / KANG Juhyung",
  },
  {
    id: "eco_b-16",
    title: "会計I",
    section: "専門基礎",
    department: "経済",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "小沢 浩 浅野 俊人 / OZAWA Hiroshi ASANO Toshihito",
  },
  {
    id: "eco_b-17",
    title: "財務諸表I",
    section: "専門基礎",
    department: "経済",
    semester: "春2",
    cellKey: "Fri-1",
    teacher: "小沢 浩 浅野 俊人 / OZAWA Hiroshi ASANO Toshihito",
  },
  {
    id: "eco_b-18",
    title: "マクロ経済学I(E)",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "金 健輝 / KIM Kunhyui",
  },
  {
    id: "eco_b-19",
    title: "経済トピックス(E)",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "金 健輝 / KIM Kunhyui",
  },
  {
    id: "eco_b-20",
    title: "経営学I(E)",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "岡島 広子 / OKAJIMA Hiroko",
  },
  {
    id: "eco_b-21",
    title: "専門基礎演習I(E)",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "金 健輝 / KIM Kunhyui",
  },
  {
    id: "eco_b-22",
    title: "専門基礎演習III(E)",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "岡島 広子 / OKAJIMA Hiroko",
  },
  {
    id: "eco_b-23",
    title: "一般経済史I",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "木越 義則 / KIGOSHI Yoshinori",
  },
  {
    id: "eco_b-24",
    title: "経営I",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "涌田 幸宏 / WAKUTA Yukihiro",
  },
  {
    id: "eco_b-25",
    title: "社会科学のための日本語I(E)",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "瓦井 由紀 松尾 陽 / KAWARAI Yuki MATSUO Yoh",
  },
  {
    id: "eco_b-26",
    title: "計量経済I",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "尚 晋 / SHANG Jin",
  },
  {
    id: "eco_b-27",
    title: "マクロ経済学I",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Thu-5",
    teacher: "柳原 光芳 / YANAGIHARA Mitsuyoshi",
  },
  {
    id: "eco_b-28",
    title: "ミクロ経済学I",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "田村 彌 / TAMURA Wataru",
  },
  {
    id: "eco_b-29",
    title: "政治経済学I",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "鍋島 直樹 / NABESHIMA Naoki",
  },
  {
    id: "eco_b-30",
    title: "会計II",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "小沢 浩 浅野 俊人 / OZAWA Hiroshi ASANO Toshihito",
  },
  {
    id: "eco_b-31",
    title: "[遠隔]経済学史I(E)",
    section: "専門基礎",
    department: "経済",
    semester: "春集中",
    teacher: "韓 丹 / HAN Dan",
  },
  {
    id: "eco_b-32",
    title: "経済史I(E)",
    section: "専門基礎",
    department: "経済",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "福澤 直樹 / FUKUZAWA Naoki",
  },
];
