import { Course } from "../courses";
export const ECO_COURSES: Course[] = [
  {
    id: "eco-1",
    title: "農業経済特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "園田 正 / SONODA Tadashi",
  },
  {
    id: "eco-2",
    title: "日本経済史特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "小林 篤史 / KOBAYASHI Atsushi",
  },
  {
    id: "eco-3",
    title: "政治学入門(現代日本政治)(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "武田 宏子 / TAKEDA Hiroko",
  },
  {
    id: "eco-4",
    title: "環境政治(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "野村 康 / NOMURA Ko",
  },
  {
    id: "eco-5",
    title: "経営戦略特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "宮﨑 正也 / MIYAZAKI Masaya",
  },
  {
    id: "eco-6",
    title: "[遠隔]政治理論(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "西山 渓 / NISHIYAMA Kei",
  },
  {
    id: "eco-7",
    title: "国際経済特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-5",
    teacher: "柳瀬 明彦 / YANASE Akihiko",
  },
  {
    id: "eco-8",
    title: "International Economics A(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Mon-5",
    teacher: "柳瀬 明彦 / YANASE Akihiko",
  },
  {
    id: "eco-9",
    title: "監査",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "松脇 昌美 / MATSUWAKI Masami",
  },
  {
    id: "eco-10",
    title: "政治思想(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "加藤 哲理 / KATO Tetsuri",
  },
  {
    id: "eco-11",
    title: "Supply Chain Management A(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "岡島 広子 / OKAJIMA Hiroko",
  },
  {
    id: "eco-12",
    title: "マーケティング特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "山口 景子 / YAMAGUCHI Keiko",
  },
  {
    id: "eco-13",
    title: "日本の法システムと法哲学(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "松尾 陽 / MATSUO Yoh",
  },
  {
    id: "eco-14",
    title: "経済政策特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "萬行 英二 / MANGYO Eiji",
  },
  {
    id: "eco-15",
    title: "Economic Policy(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "萬行 英二 / MANGYO Eiji",
  },
  {
    id: "eco-16",
    title: "国際関係論入門(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "大久保 明 / OKUBO Akira",
  },
  {
    id: "eco-17",
    title: "産業組織特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "ZHOU Yu",
  },
  {
    id: "eco-18",
    title: "Industrial Organization A(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "ZHOU Yu",
  },
  {
    id: "eco-19",
    title: "経営分析",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "姜 周亨 / KANG Juhyung",
  },
  {
    id: "eco-20",
    title: "応用ミクロ経済学(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "ZHOU Yu",
  },
  {
    id: "eco-21",
    title: "金融特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-1",
    teacher:
      "DING Zirui 大西 淳 清水 克俊 / DING Zirui ONISHI Atsushi SHIMIZU Katsutoshi",
  },
  {
    id: "eco-22",
    title: "国際会計",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "向 伊知郎 / MUKAI Ichiro",
  },
  {
    id: "eco-23",
    title: "Money and Finance A(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-1",
    teacher:
      "DING Zirui 大西 淳 清水 克俊 / DING Zirui ONISHI Atsushi SHIMIZU Katsutoshi",
  },
  {
    id: "eco-24",
    title: "開発経済学(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "中田 実 / NAKADA Minoru",
  },
  {
    id: "eco-25",
    title: "労働経済特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "工藤 教孝 / KUDOH Noritaka",
  },
  {
    id: "eco-26",
    title: "生産管理",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "樋野 励 / HINO Rei",
  },
  {
    id: "eco-27",
    title: "Labor Economics A(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "工藤 教孝 / KUDOH Noritaka",
  },
  {
    id: "eco-28",
    title: "社会思想史特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "原田 哲史 福澤 直樹 / HARADA Tetsushi FUKUZAWA Naoki",
  },
  {
    id: "eco-29",
    title: "経営労務特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "小西 琴絵 / KONISHI Kotoe",
  },
  {
    id: "eco-30",
    title: "財政特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-5",
    teacher: "御子柴 みなも / MIKOSHIBA Minamo",
  },
  {
    id: "eco-31",
    title: "経営情報特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Thu-5",
    teacher: "樋野 励 / HINO Rei",
  },
  {
    id: "eco-32",
    title: "管理会計特論",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "東田 明 / HIGASHIDAAKIRA",
  },
  {
    id: "eco-33",
    title: "経済学卒論研究II(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "土井 康裕 / DOI Yasuhiro",
  },
  {
    id: "eco-34",
    title: "ファイナンス",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "中島 英喜 / NAKASHIMA Hideki",
  },
  {
    id: "eco-35",
    title: "Advanced Income Theory I(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "DELAMOU Cece Cherif 工藤 教孝 / DELAMOU Cece Cherif KUDOH Noritaka",
  },
  {
    id: "eco-36",
    title: "経営組織",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "犬塚 篤 / INUZUKA Atsushi",
  },
  {
    id: "eco-37",
    title: "経済学演習II(E)",
    section: "専門",
    department: "経済",
    semester: "春1",
    cellKey: "Fri-4",
    teacher: "土井 康裕 / DOI Yasuhiro",
  },
  {
    id: "eco-38",
    title: "経営戦略",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "宮﨑 正也 / MIYAZAKI Masaya",
  },
  {
    id: "eco-39",
    title: "経営分析特論",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "仙場 胡丹 / SEMBA Hu Dan",
  },
  {
    id: "eco-40",
    title: "経済学史",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "西本 和見 / NISHIMOTO Kazumi",
  },
  {
    id: "eco-41",
    title: "生産管理特論",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "岡島 広子 / OKAJIMA Hiroko",
  },
  {
    id: "eco-42",
    title: "Production Management A(E)",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "岡島 広子 / OKAJIMA Hiroko",
  },
  {
    id: "eco-43",
    title: "労働経済",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "岸 智子 / KISHI Tomoko",
  },
  {
    id: "eco-44",
    title: "マーケティング",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "山口 景子 / YAMAGUCHI Keiko",
  },
  {
    id: "eco-45",
    title: "監査特論",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "仙場 胡丹 / SEMBA Hu Dan",
  },
  {
    id: "eco-46",
    title: "ファイナンス特論",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "中島 英喜 / NAKASHIMA Hideki",
  },
  {
    id: "eco-47",
    title: "財務会計",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "浅見 裕子 / ASAMI Yuko",
  },
  {
    id: "eco-48",
    title: "行政学(E)",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "荒見 玲子 / ARAMI Reiko",
  },
  {
    id: "eco-49",
    title: "財務会計特論",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Tue-5",
    teacher: "浅見 裕子 / ASAMI Yuko",
  },
  {
    id: "eco-50",
    title: "Advanced Microeconomics II(E)",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "ZHOU Yu",
  },
  {
    id: "eco-51",
    title: "産業組織",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "花薗 誠 / HANAZONO Makoto",
  },
  {
    id: "eco-52",
    title: "管理会計",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "小沢 浩 / OZAWA Hiroshi",
  },
  {
    id: "eco-53",
    title: "国際会計特論",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "姜 周亨 / KANG Juhyung",
  },
  {
    id: "eco-54",
    title: "International Accounting A(E)",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "姜 周亨 / KANG Juhyung",
  },
  {
    id: "eco-55",
    title: "経営情報",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "樋野 励 / HINO Rei",
  },
  {
    id: "eco-56",
    title: "西洋経済史特論",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "福澤 直樹 / FUKUZAWA Naoki",
  },
  {
    id: "eco-57",
    title: "経営労務",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "小西 琴絵 / KONISHI Kotoe",
  },
  {
    id: "eco-58",
    title: "研究方法論入門(E)",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "MCGINTY Sean Michael KUHN Michelle louise",
  },
  {
    id: "eco-59",
    title: "法学基礎(E)",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "CARAPETO Roberto",
  },
  {
    id: "eco-60",
    title: "現代資本主義特論",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Thu-5",
    teacher: "鍋島 直樹 / NABESHIMA Naoki",
  },
  {
    id: "eco-61",
    title: "経済学卒論研究I(E)",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "土井 康裕 / DOI Yasuhiro",
  },
  {
    id: "eco-62",
    title: "公共経済特論",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "玉井 寿樹 / TAMAI Toshiki",
  },
  {
    id: "eco-63",
    title: "経営組織特論",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "犬塚 篤 / INUZUKA Atsushi",
  },
  {
    id: "eco-64",
    title: "経済学演習I(E)",
    section: "専門",
    department: "経済",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "土井 康裕 / DOI Yasuhiro",
  },
  {
    id: "eco-65",
    title: "[遠隔]経済学史特論",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "韓 丹 / HAN Dan",
  },
  {
    id: "eco-66",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "木村 彰吾 / KIMURA Shogo",
  },
  {
    id: "eco-67",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "木村 彰吾 / KIMURA Shogo",
  },
  {
    id: "eco-68",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "鍋島 直樹 / NABESHIMA Naoki",
  },
  {
    id: "eco-69",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "鍋島 直樹 / NABESHIMA Naoki",
  },
  {
    id: "eco-70",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "福澤 直樹 / FUKUZAWA Naoki",
  },
  {
    id: "eco-71",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "福澤 直樹 / FUKUZAWA Naoki",
  },
  {
    id: "eco-72",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "立石 寛 / TATEISHI Hiroshi",
  },
  {
    id: "eco-73",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "立石 寛 / TATEISHI Hiroshi",
  },
  {
    id: "eco-74",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "中屋 信彦 / NAKAYA Nobuhiko",
  },
  {
    id: "eco-75",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "中屋 信彦 / NAKAYA Nobuhiko",
  },
  {
    id: "eco-76",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "園田 正 / SONODA Tadashi",
  },
  {
    id: "eco-77",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "園田 正 / SONODA Tadashi",
  },
  {
    id: "eco-78",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "宮﨑 正也 / MIYAZAKI Masaya",
  },
  {
    id: "eco-79",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "宮﨑 正也 / MIYAZAKI Masaya",
  },
  {
    id: "eco-80",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "柳原 光芳 / YANAGIHARA Mitsuyoshi",
  },
  {
    id: "eco-81",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "柳原 光芳 / YANAGIHARA Mitsuyoshi",
  },
  {
    id: "eco-82",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "清水 克俊 / SHIMIZU Katsutoshi",
  },
  {
    id: "eco-83",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "清水 克俊 / SHIMIZU Katsutoshi",
  },
  {
    id: "eco-84",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "小沢 浩 / OZAWA Hiroshi",
  },
  {
    id: "eco-85",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "小沢 浩 / OZAWA Hiroshi",
  },
  {
    id: "eco-86",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "仙場 胡丹 / SEMBA Hu Dan",
  },
  {
    id: "eco-87",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "仙場 胡丹 / SEMBA Hu Dan",
  },
  {
    id: "eco-88",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "花薗 誠 / HANAZONO Makoto",
  },
  {
    id: "eco-89",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "花薗 誠 / HANAZONO Makoto",
  },
  {
    id: "eco-90",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "中島 英喜 / NAKASHIMA Hideki",
  },
  {
    id: "eco-91",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "中島 英喜 / NAKASHIMA Hideki",
  },
  {
    id: "eco-92",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "藤田 真哉 / FUJITA Shinya",
  },
  {
    id: "eco-93",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "藤田 真哉 / FUJITA Shinya",
  },
  {
    id: "eco-94",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "柳瀬 明彦 / YANASE Akihiko",
  },
  {
    id: "eco-95",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "柳瀬 明彦 / YANASE Akihiko",
  },
  {
    id: "eco-96",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "犬塚 篤 / INUZUKA Atsushi",
  },
  {
    id: "eco-97",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "犬塚 篤 / INUZUKA Atsushi",
  },
  {
    id: "eco-98",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "土井 康裕 / DOI Yasuhiro",
  },
  {
    id: "eco-99",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "土井 康裕 / DOI Yasuhiro",
  },
  {
    id: "eco-100",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "木越 義則 / KIGOSHI Yoshinori",
  },
  {
    id: "eco-101",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "木越 義則 / KIGOSHI Yoshinori",
  },
  {
    id: "eco-102",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "工藤 教孝 / KUDOH Noritaka",
  },
  {
    id: "eco-103",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "工藤 教孝 / KUDOH Noritaka",
  },
  {
    id: "eco-104",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "樋野 励 / HINO Rei",
  },
  {
    id: "eco-105",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "樋野 励 / HINO Rei",
  },
  {
    id: "eco-106",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "玉井 寿樹 / TAMAI Toshiki",
  },
  {
    id: "eco-107",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "玉井 寿樹 / TAMAI Toshiki",
  },
  {
    id: "eco-108",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "田村 彌 / TAMURA Wataru",
  },
  {
    id: "eco-109",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "田村 彌 / TAMURA Wataru",
  },
  {
    id: "eco-110",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "伊藤 カンナ / ITO Kanna",
  },
  {
    id: "eco-111",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "伊藤 カンナ / ITO Kanna",
  },
  {
    id: "eco-112",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "山口 景子 / YAMAGUCHI Keiko",
  },
  {
    id: "eco-113",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "山口 景子 / YAMAGUCHI Keiko",
  },
  {
    id: "eco-114",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "ZHOU Yu",
  },
  {
    id: "eco-115",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "ZHOU Yu",
  },
  {
    id: "eco-116",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "篠田 和彦 / SHINODA Kazuhiko",
  },
  {
    id: "eco-117",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "篠田 和彦 / SHINODA Kazuhiko",
  },
  {
    id: "eco-118",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "御子柴 みなも / MIKOSHIBA Minamo",
  },
  {
    id: "eco-119",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "御子柴 みなも / MIKOSHIBA Minamo",
  },
  {
    id: "eco-120",
    title: "経済学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "小林 篤史 / KOBAYASHI Atsushi",
  },
  {
    id: "eco-121",
    title: "経営学演習I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "小林 篤史 / KOBAYASHI Atsushi",
  },
  {
    id: "eco-122",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "木村 彰吾 / KIMURA Shogo",
  },
  {
    id: "eco-123",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "木村 彰吾 / KIMURA Shogo",
  },
  {
    id: "eco-124",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "鍋島 直樹 / NABESHIMA Naoki",
  },
  {
    id: "eco-125",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "鍋島 直樹 / NABESHIMA Naoki",
  },
  {
    id: "eco-126",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "福澤 直樹 / FUKUZAWA Naoki",
  },
  {
    id: "eco-127",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "福澤 直樹 / FUKUZAWA Naoki",
  },
  {
    id: "eco-128",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "立石 寛 / TATEISHI Hiroshi",
  },
  {
    id: "eco-129",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "立石 寛 / TATEISHI Hiroshi",
  },
  {
    id: "eco-130",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "中屋 信彦 / NAKAYA Nobuhiko",
  },
  {
    id: "eco-131",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "中屋 信彦 / NAKAYA Nobuhiko",
  },
  {
    id: "eco-132",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "園田 正 / SONODA Tadashi",
  },
  {
    id: "eco-133",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "園田 正 / SONODA Tadashi",
  },
  {
    id: "eco-134",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "宮﨑 正也 / MIYAZAKI Masaya",
  },
  {
    id: "eco-135",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "宮﨑 正也 / MIYAZAKI Masaya",
  },
  {
    id: "eco-136",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "柳原 光芳 / YANAGIHARA Mitsuyoshi",
  },
  {
    id: "eco-137",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "柳原 光芳 / YANAGIHARA Mitsuyoshi",
  },
  {
    id: "eco-138",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "清水 克俊 / SHIMIZU Katsutoshi",
  },
  {
    id: "eco-139",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "清水 克俊 / SHIMIZU Katsutoshi",
  },
  {
    id: "eco-140",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "小沢 浩 / OZAWA Hiroshi",
  },
  {
    id: "eco-141",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "小沢 浩 / OZAWA Hiroshi",
  },
  {
    id: "eco-142",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "仙場 胡丹 / SEMBA Hu Dan",
  },
  {
    id: "eco-143",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "仙場 胡丹 / SEMBA Hu Dan",
  },
  {
    id: "eco-144",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "花薗 誠 / HANAZONO Makoto",
  },
  {
    id: "eco-145",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "花薗 誠 / HANAZONO Makoto",
  },
  {
    id: "eco-146",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "中島 英喜 / NAKASHIMA Hideki",
  },
  {
    id: "eco-147",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "中島 英喜 / NAKASHIMA Hideki",
  },
  {
    id: "eco-148",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "藤田 真哉 / FUJITA Shinya",
  },
  {
    id: "eco-149",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "藤田 真哉 / FUJITA Shinya",
  },
  {
    id: "eco-150",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "柳瀬 明彦 / YANASE Akihiko",
  },
  {
    id: "eco-151",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "柳瀬 明彦 / YANASE Akihiko",
  },
  {
    id: "eco-152",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "犬塚 篤 / INUZUKA Atsushi",
  },
  {
    id: "eco-153",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "犬塚 篤 / INUZUKA Atsushi",
  },
  {
    id: "eco-154",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "土井 康裕 / DOI Yasuhiro",
  },
  {
    id: "eco-155",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "土井 康裕 / DOI Yasuhiro",
  },
  {
    id: "eco-156",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "木越 義則 / KIGOSHI Yoshinori",
  },
  {
    id: "eco-157",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "木越 義則 / KIGOSHI Yoshinori",
  },
  {
    id: "eco-158",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "工藤 教孝 / KUDOH Noritaka",
  },
  {
    id: "eco-159",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "工藤 教孝 / KUDOH Noritaka",
  },
  {
    id: "eco-160",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "樋野 励 / HINO Rei",
  },
  {
    id: "eco-161",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "樋野 励 / HINO Rei",
  },
  {
    id: "eco-162",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "玉井 寿樹 / TAMAI Toshiki",
  },
  {
    id: "eco-163",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "玉井 寿樹 / TAMAI Toshiki",
  },
  {
    id: "eco-164",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "田村 彌 / TAMURA Wataru",
  },
  {
    id: "eco-165",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "田村 彌 / TAMURA Wataru",
  },
  {
    id: "eco-166",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "伊藤 カンナ / ITO Kanna",
  },
  {
    id: "eco-167",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "伊藤 カンナ / ITO Kanna",
  },
  {
    id: "eco-168",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "山口 景子 / YAMAGUCHI Keiko",
  },
  {
    id: "eco-169",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "山口 景子 / YAMAGUCHI Keiko",
  },
  {
    id: "eco-170",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "ZHOU Yu",
  },
  {
    id: "eco-171",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "ZHOU Yu",
  },
  {
    id: "eco-172",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "篠田 和彦 / SHINODA Kazuhiko",
  },
  {
    id: "eco-173",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "篠田 和彦 / SHINODA Kazuhiko",
  },
  {
    id: "eco-174",
    title: "経済学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "御子柴 みなも / MIKOSHIBA Minamo",
  },
  {
    id: "eco-175",
    title: "経営学卒論研究I",
    section: "専門",
    department: "経済",
    semester: "春集中",
    teacher: "御子柴 みなも / MIKOSHIBA Minamo",
  },
  {
    id: "eco-176",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "木村 彰吾 / KIMURA Shogo",
  },
  {
    id: "eco-177",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "木村 彰吾 / KIMURA Shogo",
  },
  {
    id: "eco-178",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "鍋島 直樹 / NABESHIMA Naoki",
  },
  {
    id: "eco-179",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "鍋島 直樹 / NABESHIMA Naoki",
  },
  {
    id: "eco-180",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "福澤 直樹 / FUKUZAWA Naoki",
  },
  {
    id: "eco-181",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "福澤 直樹 / FUKUZAWA Naoki",
  },
  {
    id: "eco-182",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "立石 寛 / TATEISHI Hiroshi",
  },
  {
    id: "eco-183",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "立石 寛 / TATEISHI Hiroshi",
  },
  {
    id: "eco-184",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "中屋 信彦 / NAKAYA Nobuhiko",
  },
  {
    id: "eco-185",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "中屋 信彦 / NAKAYA Nobuhiko",
  },
  {
    id: "eco-186",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "園田 正 / SONODA Tadashi",
  },
  {
    id: "eco-187",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "園田 正 / SONODA Tadashi",
  },
  {
    id: "eco-188",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "宮﨑 正也 / MIYAZAKI Masaya",
  },
  {
    id: "eco-189",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "宮﨑 正也 / MIYAZAKI Masaya",
  },
  {
    id: "eco-190",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "柳原 光芳 / YANAGIHARA Mitsuyoshi",
  },
  {
    id: "eco-191",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "柳原 光芳 / YANAGIHARA Mitsuyoshi",
  },
  {
    id: "eco-192",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "清水 克俊 / SHIMIZU Katsutoshi",
  },
  {
    id: "eco-193",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "清水 克俊 / SHIMIZU Katsutoshi",
  },
  {
    id: "eco-194",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "小沢 浩 / OZAWA Hiroshi",
  },
  {
    id: "eco-195",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "小沢 浩 / OZAWA Hiroshi",
  },
  {
    id: "eco-196",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "仙場 胡丹 / SEMBA Hu Dan",
  },
  {
    id: "eco-197",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "仙場 胡丹 / SEMBA Hu Dan",
  },
  {
    id: "eco-198",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "花薗 誠 / HANAZONO Makoto",
  },
  {
    id: "eco-199",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "花薗 誠 / HANAZONO Makoto",
  },
  {
    id: "eco-200",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "中島 英喜 / NAKASHIMA Hideki",
  },
  {
    id: "eco-201",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "中島 英喜 / NAKASHIMA Hideki",
  },
  {
    id: "eco-202",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "藤田 真哉 / FUJITA Shinya",
  },
  {
    id: "eco-203",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "藤田 真哉 / FUJITA Shinya",
  },
  {
    id: "eco-204",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "柳瀬 明彦 / YANASE Akihiko",
  },
  {
    id: "eco-205",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "柳瀬 明彦 / YANASE Akihiko",
  },
  {
    id: "eco-206",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "犬塚 篤 / INUZUKA Atsushi",
  },
  {
    id: "eco-207",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "犬塚 篤 / INUZUKA Atsushi",
  },
  {
    id: "eco-208",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "土井 康裕 / DOI Yasuhiro",
  },
  {
    id: "eco-209",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "土井 康裕 / DOI Yasuhiro",
  },
  {
    id: "eco-210",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "木越 義則 / KIGOSHI Yoshinori",
  },
  {
    id: "eco-211",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "木越 義則 / KIGOSHI Yoshinori",
  },
  {
    id: "eco-212",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "工藤 教孝 / KUDOH Noritaka",
  },
  {
    id: "eco-213",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "工藤 教孝 / KUDOH Noritaka",
  },
  {
    id: "eco-214",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "樋野 励 / HINO Rei",
  },
  {
    id: "eco-215",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "樋野 励 / HINO Rei",
  },
  {
    id: "eco-216",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "玉井 寿樹 / TAMAI Toshiki",
  },
  {
    id: "eco-217",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "玉井 寿樹 / TAMAI Toshiki",
  },
  {
    id: "eco-218",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "田村 彌 / TAMURA Wataru",
  },
  {
    id: "eco-219",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "田村 彌 / TAMURA Wataru",
  },
  {
    id: "eco-220",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "伊藤 カンナ / ITO Kanna",
  },
  {
    id: "eco-221",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "伊藤 カンナ / ITO Kanna",
  },
  {
    id: "eco-222",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "山口 景子 / YAMAGUCHI Keiko",
  },
  {
    id: "eco-223",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "山口 景子 / YAMAGUCHI Keiko",
  },
  {
    id: "eco-224",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "ZHOU Yu",
  },
  {
    id: "eco-225",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "ZHOU Yu",
  },
  {
    id: "eco-226",
    title: "経済学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "篠田 和彦 / SHINODA Kazuhiko",
  },
  {
    id: "eco-227",
    title: "経営学演習II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "篠田 和彦 / SHINODA Kazuhiko",
  },
  {
    id: "eco-228",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "木村 彰吾 / KIMURA Shogo",
  },
  {
    id: "eco-229",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "木村 彰吾 / KIMURA Shogo",
  },
  {
    id: "eco-230",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "鍋島 直樹 / NABESHIMA Naoki",
  },
  {
    id: "eco-231",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "鍋島 直樹 / NABESHIMA Naoki",
  },
  {
    id: "eco-232",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "福澤 直樹 / FUKUZAWA Naoki",
  },
  {
    id: "eco-233",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "福澤 直樹 / FUKUZAWA Naoki",
  },
  {
    id: "eco-234",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "立石 寛 / TATEISHI Hiroshi",
  },
  {
    id: "eco-235",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "立石 寛 / TATEISHI Hiroshi",
  },
  {
    id: "eco-236",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "中屋 信彦 / NAKAYA Nobuhiko",
  },
  {
    id: "eco-237",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "中屋 信彦 / NAKAYA Nobuhiko",
  },
  {
    id: "eco-238",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "園田 正 / SONODA Tadashi",
  },
  {
    id: "eco-239",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "園田 正 / SONODA Tadashi",
  },
  {
    id: "eco-240",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "宮﨑 正也 / MIYAZAKI Masaya",
  },
  {
    id: "eco-241",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "宮﨑 正也 / MIYAZAKI Masaya",
  },
  {
    id: "eco-242",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "柳原 光芳 / YANAGIHARA Mitsuyoshi",
  },
  {
    id: "eco-243",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "柳原 光芳 / YANAGIHARA Mitsuyoshi",
  },
  {
    id: "eco-244",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "清水 克俊 / SHIMIZU Katsutoshi",
  },
  {
    id: "eco-245",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "清水 克俊 / SHIMIZU Katsutoshi",
  },
  {
    id: "eco-246",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "小沢 浩 / OZAWA Hiroshi",
  },
  {
    id: "eco-247",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "小沢 浩 / OZAWA Hiroshi",
  },
  {
    id: "eco-248",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "仙場 胡丹 / SEMBA Hu Dan",
  },
  {
    id: "eco-249",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "仙場 胡丹 / SEMBA Hu Dan",
  },
  {
    id: "eco-250",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "花薗 誠 / HANAZONO Makoto",
  },
  {
    id: "eco-251",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "花薗 誠 / HANAZONO Makoto",
  },
  {
    id: "eco-252",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "中島 英喜 / NAKASHIMA Hideki",
  },
  {
    id: "eco-253",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "中島 英喜 / NAKASHIMA Hideki",
  },
  {
    id: "eco-254",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "藤田 真哉 / FUJITA Shinya",
  },
  {
    id: "eco-255",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "藤田 真哉 / FUJITA Shinya",
  },
  {
    id: "eco-256",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "柳瀬 明彦 / YANASE Akihiko",
  },
  {
    id: "eco-257",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "柳瀬 明彦 / YANASE Akihiko",
  },
  {
    id: "eco-258",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "犬塚 篤 / INUZUKA Atsushi",
  },
  {
    id: "eco-259",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "犬塚 篤 / INUZUKA Atsushi",
  },
  {
    id: "eco-260",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "土井 康裕 / DOI Yasuhiro",
  },
  {
    id: "eco-261",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "土井 康裕 / DOI Yasuhiro",
  },
  {
    id: "eco-262",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "木越 義則 / KIGOSHI Yoshinori",
  },
  {
    id: "eco-263",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "木越 義則 / KIGOSHI Yoshinori",
  },
  {
    id: "eco-264",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "工藤 教孝 / KUDOH Noritaka",
  },
  {
    id: "eco-265",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "工藤 教孝 / KUDOH Noritaka",
  },
  {
    id: "eco-266",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "樋野 励 / HINO Rei",
  },
  {
    id: "eco-267",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "樋野 励 / HINO Rei",
  },
  {
    id: "eco-268",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "玉井 寿樹 / TAMAI Toshiki",
  },
  {
    id: "eco-269",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "玉井 寿樹 / TAMAI Toshiki",
  },
  {
    id: "eco-270",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "田村 彌 / TAMURA Wataru",
  },
  {
    id: "eco-271",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "田村 彌 / TAMURA Wataru",
  },
  {
    id: "eco-272",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "伊藤 カンナ / ITO Kanna",
  },
  {
    id: "eco-273",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "伊藤 カンナ / ITO Kanna",
  },
  {
    id: "eco-274",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "山口 景子 / YAMAGUCHI Keiko",
  },
  {
    id: "eco-275",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "山口 景子 / YAMAGUCHI Keiko",
  },
  {
    id: "eco-276",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "ZHOU Yu",
  },
  {
    id: "eco-277",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "ZHOU Yu",
  },
  {
    id: "eco-278",
    title: "経済学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "篠田 和彦 / SHINODA Kazuhiko",
  },
  {
    id: "eco-279",
    title: "経営学卒論研究II",
    section: "専門",
    department: "経済",
    semester: "秋集中",
    teacher: "篠田 和彦 / SHINODA Kazuhiko",
  },
];
