import { Course } from "../courses";
export const INFO_B_COURSES: Course[] = [
  {
    id: "info_b-1",
    title: "心の科学",
    section: "専門基礎",
    department: "情報",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "石井 敬子 平井 真洋 髙野 了太 川合 伸幸 三輪 和久 宮本 健史 孟 憲巍 北神 慎司 / ISHII Keiko HIRAI Masahiro TAKANO Ryota KAWAI Nobuyuki MIWA Kazuhisa MIYAMOTO Takeshi MENG Xianwei KITAGAMI Shinji",
  },
  {
    id: "info_b-2",
    title: "離散数学及び演習(2021年度以前入学生)",
    section: "専門基礎",
    department: "情報",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "外山 勝彦 / TOYAMA Katsuhiko",
  },
  {
    id: "info_b-3",
    title: "情報と国際社会",
    section: "専門基礎",
    department: "情報",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "山本 竜大 中村 登志哉 後藤 明史 井原 伸浩 / YAMAMOTO Tatsuhiro NAKAMURA Toshiya GOTO Akifumi IHARA Nobuhiro",
  },
  {
    id: "info_b-4",
    title: "情報創造",
    section: "専門基礎",
    department: "情報",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "秋庭 史典 久木田 水生 / AKIBA Fuminori KUKITA Minao",
  },
  {
    id: "info_b-5",
    title: "社会調査",
    section: "専門基礎",
    department: "情報",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "河村 則行 吉村 真衣 立川 雅司 丸山 康司 / KAWAMURA Noriyuki YOSHIMURA Mai TACHIKAWA Masashi MARUYAMA Yasushi",
  },
  {
    id: "info_b-6",
    title: "データマイニング入門(自然・人社)",
    section: "専門基礎",
    department: "情報",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "北 栄輔 / KITA Eisuke",
  },
  {
    id: "info_b-7",
    title: "データマイニング入門(CS)",
    section: "専門基礎",
    department: "情報",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "石川 佳治 / ISHIKAWA Yoshiharu",
  },
  {
    id: "info_b-8",
    title: "複雑系科学の基礎",
    section: "専門基礎",
    department: "情報",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "鈴木 麗璽 / SUZUKI Reiji",
  },
  {
    id: "info_b-9",
    title: "クリエイティブ・ネットワーキング",
    section: "専門基礎",
    department: "情報",
    semester: "春1",
    cellKey: "Wed-3",
    teacher: "鈴木 麗璽 遠藤 守 / SUZUKI Reiji ENDO Mamoru",
  },
  {
    id: "info_b-10",
    title: "情報の挑戦者・開拓者たち",
    section: "専門基礎",
    department: "情報",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "北 栄輔 / KITA Eisuke",
  },
  {
    id: "info_b-11",
    title: "インフォマティックス2",
    section: "専門基礎",
    department: "情報",
    semester: "春2",
    cellKey: "Fri-4",
    teacher:
      "秋庭 史典 石井 敬子 山本 竜大 久木田 水生 北 栄輔 浦田 真由 中村 登志哉 笠木 雅史 井原 伸浩 / AKIBA Fuminori ISHII Keiko YAMAMOTO Tatsuhiro KUKITA Minao KITA Eisuke URATA Mayu NAKAMURA Toshiya KASAKI Masashi IHARA Nobuhiro",
  },
  {
    id: "info_b-12",
    title: "情報理論(自然・人社)",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "東中 竜一郎 / HIGASHINAKA Ryuichiro",
  },
  {
    id: "info_b-13",
    title: "情報理論(CS)",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "楫 勇一 / KAJI Yuichi",
  },
  {
    id: "info_b-14",
    title: "論理学1(自然・CS)",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher:
      "中澤 巧爾 木原 貴行 結縁 祥治 / NAKAZAWA Koji KIHARA Takayuki YUEN Shoji",
  },
  {
    id: "info_b-15",
    title: "論理学1(人社)",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "久木田 水生 / KUKITA Minao",
  },
  {
    id: "info_b-16",
    title: "確率統計及び演習",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "小田 昌宏 / ODA Masahiro",
  },
  {
    id: "info_b-17",
    title: "人間の知・機械の知",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "三輪 和久 / MIWA Kazuhisa",
  },
  {
    id: "info_b-18",
    title: "アルゴリズム1(自然・人社)",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "山西 芳裕 / YAMANISHI Yoshihiro",
  },
  {
    id: "info_b-19",
    title: "アルゴリズム1(CS)",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "西田 直樹 / NISHIDA Naoki",
  },
  {
    id: "info_b-20",
    title: "情報システムとしての自然1:生きる",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher:
      "太田 元規 北 栄輔 永峰 康一郎 青木 摂之 山西 芳裕 / OTA Motonori KITA Eisuke NAGAMINE Koichiro AOKI Setsuyuki YAMANISHI Yoshihiro",
  },
  {
    id: "info_b-21",
    title: "システム数学及び演習1",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "藤井 慶輔 武田 一哉 / FUJII Keisuke TAKEDA Kazuya",
  },
  {
    id: "info_b-22",
    title: "システム数学及び演習2",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "藤井 慶輔 武田 一哉 / FUJII Keisuke TAKEDA Kazuya",
  },
  {
    id: "info_b-23",
    title: "問題解決・課題解決の科学",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "長尾 征洋 北 栄輔 / NAGAO Masahiro KITA Eisuke",
  },
  {
    id: "info_b-24",
    title: "線形代数学の発展1",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "西村 治道 / NISHIMURA Harumichi",
  },
  {
    id: "info_b-25",
    title: "シミュレーション・サイエンス1",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher:
      "時田 恵一郎 松田 圭悟 内山 知実 中村 泰之 / TOKITA Keiichiro MATSUDA Keigo UCHIYAMA Tomomi NAKAMURA Yasuyuki",
  },
  {
    id: "info_b-26",
    title: "プログラミング1(CS)",
    section: "専門基礎",
    department: "情報",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "笹野 遼平 / SASANO Ryohei",
  },
  {
    id: "info_b-27",
    title: "論理学2a",
    section: "専門基礎",
    department: "情報",
    semester: "秋2",
    cellKey: "Mon-2",
    teacher: "木原 貴行 吉信 康夫 / KIHARA Takayuki YOSHINOBU Yasuo",
  },
  {
    id: "info_b-28",
    title: "論理学2b",
    section: "専門基礎",
    department: "情報",
    semester: "秋2",
    cellKey: "Mon-2",
    teacher: "久木田 水生 / KUKITA Minao",
  },
  {
    id: "info_b-29",
    title: "論理学2c",
    section: "専門基礎",
    department: "情報",
    semester: "秋2",
    cellKey: "Mon-2",
    teacher: "結縁 祥治 中澤 巧爾 / YUEN Shoji NAKAZAWA Koji",
  },
  {
    id: "info_b-30",
    title: "アルゴリズム2(自然・人社)",
    section: "専門基礎",
    department: "情報",
    semester: "秋2",
    cellKey: "Tue-3",
    teacher: "松田 圭悟 / MATSUDA Keigo",
  },
  {
    id: "info_b-31",
    title: "アルゴリズム2(CS)",
    section: "専門基礎",
    department: "情報",
    semester: "秋2",
    cellKey: "Tue-3",
    teacher: "西田 直樹 / NISHIDA Naoki",
  },
  {
    id: "info_b-32",
    title: "情報システムとしての自然2:流れる",
    section: "専門基礎",
    department: "情報",
    semester: "秋2",
    cellKey: "Tue-4",
    teacher:
      "東 雅大 吉田 紀生 鈴木 泰博 北 栄輔 張 賀東 内山 知実 / HIGASHI Masahiro YOSHIDA Norio SUZUKI Yasuhiro KITA Eisuke ZHANG Hedong UCHIYAMA Tomomi",
  },
  {
    id: "info_b-33",
    title: "意思決定",
    section: "専門基礎",
    department: "情報",
    semester: "秋2",
    cellKey: "Thu-1",
    teacher: "中村 泰之 / NAKAMURA Yasuyuki",
  },
  {
    id: "info_b-34",
    title: "線形代数学の発展2",
    section: "専門基礎",
    department: "情報",
    semester: "秋2",
    cellKey: "Thu-3",
    teacher: "西村 治道 / NISHIMURA Harumichi",
  },
  {
    id: "info_b-35",
    title: "シミュレーション・サイエンス2",
    section: "専門基礎",
    department: "情報",
    semester: "秋2",
    cellKey: "Thu-4",
    teacher:
      "吉田 紀生 太田 元規 東 雅大 張 賀東 松本 健太郎 安田 耕二 / YOSHIDA Norio OTA Motonori HIGASHI Masahiro ZHANG Hedong MATSUMOTO Kentaro YASUDA Koji",
  },
  {
    id: "info_b-36",
    title: "インフォマティックス4",
    section: "専門基礎",
    department: "情報",
    semester: "秋2",
    cellKey: "Fri-2",
    teacher:
      "東 雅大 太田 元規 鈴木 泰博 BUSCEMI Francesco / HIGASHI Masahiro OTA Motonori SUZUKI Yasuhiro BUSCEMI Francesco",
  },
  {
    id: "info_b-37",
    title: "プログラミング2(CS)",
    section: "専門基礎",
    department: "情報",
    semester: "秋2",
    cellKey: "Fri-3",
    teacher: "星野 哲也 / HOSHINO Tetsuya",
  },
  {
    id: "info_b-38",
    title: "[遠隔]インフォマティックス1",
    section: "専門基礎",
    department: "情報",
    semester: "春集中",
    teacher:
      "枝廣 正人 石川 佳治 高田 広章 石原 亨 村瀬 勉 酒井 正彦 結縁 祥治 / EDAHIRO Masato ISHIKAWA Yoshiharu TAKADA Hiroaki ISHIHARA Tohru MURASE Tutomu SAKAI Masahiko YUEN Shoji",
  },
  {
    id: "info_b-39",
    title: "[遠隔]インフォマティックス3",
    section: "専門基礎",
    department: "情報",
    semester: "秋集中",
    teacher:
      "出口 大輔 井手 一郎 武田 一哉 森 健策 長尾 確 小田 昌宏 東中 竜一郎 松原 茂樹 / DEGUCHI Daisuke IDE Ichiro TAKEDA Kazuya MORI Kensaku NAGAO Katashi ODA Masahiro HIGASHINAKA Ryuichiro MATSUBARA Shigeki",
  },
];
