import { Course } from "../courses";
export const NATU_COURSES: Course[] = [
  {
    id: "natu-1",
    title: "[G30]生物学実験",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "小嶋 誠司 清水 貴史 / KOJIMA Seiji SHIMIZU Takashi",
  },
  {
    id: "natu-2",
    title: "[G30]化学実験",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-3",
    teacher:
      "SAMJESKE Gabor Arwed PHUNG Quan manh 珠玖 良昭 / SAMJESKE Gabor Arwed PHUNG Quan manh SHUKU Yoshiaki",
  },
  {
    id: "natu-3",
    title: "[G30]物理学実験",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher:
      "石橋 和紀 GELLOZ Bernard Jacques 井村 敬一郎 中村 友祐 横井 達矢 / ISHIBASHI Kazunori GELLOZ Bernard Jacques IMURA Keiichiro NAKAMURA Yusuke YOKOI Tatsuya",
  },
  {
    id: "natu-4",
    title: "[G30]リメディアル数学",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "RICHARD Serge charles",
  },
  {
    id: "natu-5",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "青木 弾 福島 和彦 / AOKI Dan FUKUSHIMA Kazuhiko",
  },
  {
    id: "natu-6",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "北 将樹 青井 啓悟 / KITA Masaki AOI Keigo",
  },
  {
    id: "natu-7",
    title: "生物学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "荒木 聡彦 井原 邦夫 成田 哲博 / ARAKI Satohiko IHARA Kunio NARITA Akihiro",
  },
  {
    id: "natu-8",
    title: "数学通論I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "白水 徹也 / SHIROMIZU Tetsuya",
  },
  {
    id: "natu-9",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "吉田 紀生 東 雅大 / YOSHIDA Norio HIGASHI Masahiro",
  },
  {
    id: "natu-10",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "伏谷 瑞穂 / FUSHITANI Mizuho",
  },
  {
    id: "natu-11",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "松下 未知雄 / MATSUSHITA Michio",
  },
  {
    id: "natu-12",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "邨次 智 / MURATSUGU Satoshi",
  },
  {
    id: "natu-13",
    title: "力学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "加藤 博和 / KATO Hirokazu",
  },
  {
    id: "natu-14",
    title: "力学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "川口 由紀 / KAWAGUCHI Yuki",
  },
  {
    id: "natu-15",
    title: "力学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "髙嶋 圭史 大戸 達彦 / TAKASHIMA Yoshifumi OHTO Tatsuhiko",
  },
  {
    id: "natu-16",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "須田 淳 / SUDA Jun",
  },
  {
    id: "natu-17",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "南 和彦 / MINAMI Kazuhiko",
  },
  {
    id: "natu-18",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "喜多 奈々緒 / KITA Nanao",
  },
  {
    id: "natu-19",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "小林 亮一 / KOBAYASHI Ryoichi",
  },
  {
    id: "natu-20",
    title: "力学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "富田 英生 / TOMITA Hideki",
  },
  {
    id: "natu-21",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "宇澤 達 / UZAWA Tohru",
  },
  {
    id: "natu-22",
    title: "地球科学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "永峰 康一郎 / NAGAMINE Koichiro",
  },
  {
    id: "natu-23",
    title: "生物学実験",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "石川 明 / ISHIKAWA Akira",
  },
  {
    id: "natu-24",
    title: "化学実験",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-4",
    teacher:
      "桒原 真人 菊田 浩一 鈴木 一正 / KUWAHARA Makoto KIKUTA Koichi SUZUKI Kazumasa",
  },
  {
    id: "natu-25",
    title: "生物学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Mon-5",
    teacher:
      "亀髙 諭 荒井 律子 玉腰 浩司 李 佐知子 / KAMETAKA Satoshi ARAI Ritsuko TAMAKOSHI Koji LEE Sachiko",
  },
  {
    id: "natu-26",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "JAERISCH Johannes Klaus B / JAERISCH Johannes Klaus Bernhard",
  },
  {
    id: "natu-27",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "菱田 俊明 / HISHIDA Toshiaki",
  },
  {
    id: "natu-28",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "大久保 俊 / OHKUBO Shun",
  },
  {
    id: "natu-29",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "森本 宏 / MORIMOTO Hiroshi",
  },
  {
    id: "natu-30",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "濱中 真志 / HAMANAKA Masashi",
  },
  {
    id: "natu-31",
    title: "物理学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "下志万 貴博 / SHIMOJIMA Takahiro",
  },
  {
    id: "natu-32",
    title: "数学通論I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "小林 亮一 / KOBAYASHI Ryoichi",
  },
  {
    id: "natu-33",
    title: "数学通論I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "久保 明達 / KUBO Akisato",
  },
  {
    id: "natu-34",
    title: "数学通論I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "森本 宏 / MORIMOTO Hiroshi",
  },
  {
    id: "natu-35",
    title: "生物学実験",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "清水 貴史 / SHIMIZU Takashi",
  },
  {
    id: "natu-36",
    title: "物理学実験",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-3",
    teacher:
      "居波 賢二 槇 亙介 谷口 博基 中野 敏行 佐藤 修 三石 郁之 國生 拓摩 大山 伸一郎 / INAMI Kenji MAKI Kosuke TANIGUCHI Hiroki NAKANO Toshiyuki SATO Osamu MITSUISHI Ikuyuki KOKUSHO Takuma OYAMA Shin-ichiro",
  },
  {
    id: "natu-37",
    title: "生物学実験",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "清水 貴史 小嶋 誠司 / SHIMIZU Takashi KOJIMA Seiji",
  },
  {
    id: "natu-38",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "谷川 好男 / TANIGAWA Yoshio",
  },
  {
    id: "natu-39",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "川瀬 晃道 / KAWASE Kodo",
  },
  {
    id: "natu-40",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "白水 徹也 / SHIROMIZU Tetsuya",
  },
  {
    id: "natu-41",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "田地 宏一 / TAJI Kouichi",
  },
  {
    id: "natu-42",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "永尾 太郎 / NAGAO Taro",
  },
  {
    id: "natu-43",
    title: "化学実験",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "井改 知幸 武藤 慶 清水 一憲 / IKAI Tomoyuki MUTO Kei SHIMIZU Kazunori",
  },
  {
    id: "natu-44",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "柳浦 睦憲 / YAGIURA Mutsunori",
  },
  {
    id: "natu-45",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "加納 成男 / KANOU Naruo",
  },
  {
    id: "natu-46",
    title: "物理学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "寺崎 一郎 / TERASAKI Ichiro",
  },
  {
    id: "natu-47",
    title: "物理学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "河野 浩 / KOHNO Hiroshi",
  },
  {
    id: "natu-48",
    title: "物理学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "小林 浩 / KOBAYASHI Hiroshi",
  },
  {
    id: "natu-49",
    title: "物理学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "久野 純治 / HISANO Junji",
  },
  {
    id: "natu-50",
    title: "生物学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher:
      "阿部 秀樹 戸丸 信弘 山本 直之 芦苅 基行 / ABE Hideki TOMARU Nobuhiro YAMAMOTO Naoyuki ASHIKARI Motoyuki",
  },
  {
    id: "natu-51",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "宮町 俊生 旭 良司 / MIYAMACHI Toshio ASAHI Ryoji",
  },
  {
    id: "natu-52",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "川村 友美 / KAWAMURA Tomomi",
  },
  {
    id: "natu-53",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "中西 知樹 / NAKANISHI Tomoki",
  },
  {
    id: "natu-54",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "齋藤 晃 / SAITOH Koh",
  },
  {
    id: "natu-55",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "寺澤 祐高 / TERASAWA Yutaka",
  },
  {
    id: "natu-56",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "畑野 敬史 / HATANO Takafumi",
  },
  {
    id: "natu-57",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "沢邊 恭一 / SAWABE Kyoichi",
  },
  {
    id: "natu-58",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "菊田 浩一 / KIKUTA Koichi",
  },
  {
    id: "natu-59",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "鈴木 淳巨 / SUZUKI Atsuo",
  },
  {
    id: "natu-60",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "樫田 啓 / KASHIDA Hiromu",
  },
  {
    id: "natu-61",
    title: "物理学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "時田 恵一郎 / TOKITA Keiichiro",
  },
  {
    id: "natu-62",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "太田 啓史 / OHTA Hiroshi",
  },
  {
    id: "natu-63",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "荒野 悠輝 / ARANO Yuki",
  },
  {
    id: "natu-64",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "粟田 英資 / AWATA Hidetoshi",
  },
  {
    id: "natu-65",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "中島 誠 / NAKASHIMA Makoto",
  },
  {
    id: "natu-66",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "大舘 陽太 / OTACHI Yota",
  },
  {
    id: "natu-67",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "真島 一成 / MASIMA Kazusige",
  },
  {
    id: "natu-68",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "平尾 将剛 / HIRAO Masatake",
  },
  {
    id: "natu-69",
    title: "地球科学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-3",
    teacher: "渡邊 誠一郎 中川 書子 / WATANABE Sei-ichiro NAKAGAWA Fumiko",
  },
  {
    id: "natu-70",
    title: "地球科学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-3",
    teacher: "藤田 耕史 並木 敦子 / FUJITA Koji NAMIKI Atsuko",
  },
  {
    id: "natu-71",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-3",
    teacher: "中野 正樹 / NAKANO Masaki",
  },
  {
    id: "natu-72",
    title: "物理学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Wed-4",
    teacher:
      "稲垣 哲也 吉田 正人 山﨑 真理子 / INAGAKI Tetsuya YOSHIDA Masato YAMASAKI Mariko",
  },
  {
    id: "natu-73",
    title: "力学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "辻 義之 / TSUJI Yoshiyuki",
  },
  {
    id: "natu-74",
    title: "力学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "五十嵐 豪 / IGARASHI Go",
  },
  {
    id: "natu-75",
    title: "力学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "稲守 孝哉 / INAMORI Takaya",
  },
  {
    id: "natu-76",
    title: "力学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "松本 健郎 / MATSUMOTO Takeo",
  },
  {
    id: "natu-77",
    title: "生物学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-3",
    teacher:
      "岩見 真吾 松林 嘉克 五島 剛太 / IWAMI Shingo MATSUBAYASHI Yoshikatsu GOSHIMA Gohta",
  },
  {
    id: "natu-78",
    title: "生物学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-3",
    teacher:
      "木下 俊則 上川内 あづさ 多田 安臣 / KINOSHITA Toshinori KAMIKOUCHI Azusa TADA Yasuomi",
  },
  {
    id: "natu-79",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "岩松 将一 / IWAMATSU Sho-ichi",
  },
  {
    id: "natu-80",
    title: "物理学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "伊藤 正行 / ITOH Masayuki",
  },
  {
    id: "natu-81",
    title: "物理学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "市來 淨與 / ICHIKI Kiyotomo",
  },
  {
    id: "natu-82",
    title: "力学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "長江 拓也 / NAGAE Takuya",
  },
  {
    id: "natu-83",
    title: "物理学実験",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-3",
    teacher:
      "安田 淳一郎 渡邉 真隆 井村 敬一郎 / YASUDA Junichiro WATANABE Masataka IMURA Keiichiro",
  },
  {
    id: "natu-84",
    title: "生物学実験",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "石川 明 / ISHIKAWA Akira",
  },
  {
    id: "natu-85",
    title: "化学実験",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-3",
    teacher:
      "安田 啓司 吉本 将隆 珠玖 良昭 / YASUDA Keiji YOSHIMOTO Masataka SHUKU Yoshiaki",
  },
  {
    id: "natu-86",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "平井 広志 / HIRAI Hiroshi",
  },
  {
    id: "natu-87",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "藤原 一宏 / FUJIWARA Kazuhiro",
  },
  {
    id: "natu-88",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "林 孝宏 / HAYASHI Takahiro",
  },
  {
    id: "natu-89",
    title: "線形代数学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "谷川 好男 / TANIGAWA Yoshio",
  },
  {
    id: "natu-90",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "日比野 高士 / HIBINO Takashi",
  },
  {
    id: "natu-91",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "ジンチェンコ アナトーリ / ZINCHENKO Anatoly",
  },
  {
    id: "natu-92",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "小林 善司 / KOBAYASHI Zenji",
  },
  {
    id: "natu-93",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "ウヤヌク ムハメット / UYANIK Muhammet",
  },
  {
    id: "natu-94",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "片山 尚幸 / KATAYAMA Naoyuki",
  },
  {
    id: "natu-95",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "入山 恭寿 / IRIYAMA Yasutoshi",
  },
  {
    id: "natu-96",
    title: "化学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "尾上 順 / ONOE Jun",
  },
  {
    id: "natu-97",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "BUSCEMI Francesco",
  },
  {
    id: "natu-98",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "小野 廣隆 / ONO Hirotaka",
  },
  {
    id: "natu-99",
    title: "微分積分学I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "大橋 あすか / OHASHI Asuka",
  },
  {
    id: "natu-100",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "中野 秀雄 伊藤 智和 / NAKANO Hideo ITO Tomokazu",
  },
  {
    id: "natu-101",
    title: "生物学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "島田 緑 / SHIMADA Midori",
  },
  {
    id: "natu-102",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Fri-4",
    teacher: "野村 信嘉 横島 聡 / NOMURA Nobuyoshi YOKOSHIMA Satoshi",
  },
  {
    id: "natu-103",
    title: "化学実験",
    section: "自然教養",
    department: "全学",
    semester: "春1",
    cellKey: "Fri-4",
    teacher:
      "澤田 康之 珠玖 良昭 佐藤 勝俊 / SAWADA Yasuyuki SHUKU Yoshiaki SATO Katsutoshi",
  },
  {
    id: "natu-104",
    title: "地球科学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-1",
    teacher:
      "持田 陸宏 高橋 聡 道林 克禎 / MOCHIDA Michihiro TAKAHASHI Satoshi MICHIBAYASHI Katsuyoshi",
  },
  {
    id: "natu-105",
    title: "生物学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-1",
    teacher:
      "多田 安臣 上川内 あづさ 廣明 秀一 / TADA Yasuomi KAMIKOUCHI Azusa HIROAKI Hidekazu",
  },
  {
    id: "natu-106",
    title: "生物学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-1",
    teacher:
      "久本 直毅 大澤 志津江 嘉村 巧 / HISAMOTO Naoki OHSAWA Shizue KAMURA Takumi",
  },
  {
    id: "natu-107",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-1",
    teacher: "大舘 陽太 / OTACHI Yota",
  },
  {
    id: "natu-108",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-1",
    teacher: "平尾 将剛 / HIRAO Masatake",
  },
  {
    id: "natu-109",
    title: "生物学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-2",
    teacher:
      "清水 貴史 花房 洋 岩波 翔也 / SHIMIZU Takashi HANAFUSA Hiroshi IWANAMI Shoya",
  },
  {
    id: "natu-110",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "JAERISCH Johannes Klaus B / JAERISCH Johannes Klaus Bernhard",
  },
  {
    id: "natu-111",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "菱田 俊明 / HISHIDA Toshiaki",
  },
  {
    id: "natu-112",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "大久保 俊 / OHKUBO Shun",
  },
  {
    id: "natu-113",
    title: "力学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "松山 智至 / MATSUYAMA Satoshi",
  },
  {
    id: "natu-114",
    title: "力学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "判治 剛 / HANJI Takeshi",
  },
  {
    id: "natu-115",
    title: "力学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "山本 和弘 / YAMAMOTO Kazuhiro",
  },
  {
    id: "natu-116",
    title: "力学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "水野 幸治 / MIZUNO Koji",
  },
  {
    id: "natu-117",
    title: "力学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "日出間 るり 杵淵 紀世志 / HIDEMA Ruri KINEFUCHI Kiyoshi",
  },
  {
    id: "natu-118",
    title: "力学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "森山 貴広 / MORIYAMA Takahiro",
  },
  {
    id: "natu-119",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-2",
    teacher: "張 紹良 / ZHANG Shao-liang",
  },
  {
    id: "natu-120",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-3",
    teacher: "安田 耕二 塚本 眞幸 / YASUDA Koji TSUKAMOTO Masaki",
  },
  {
    id: "natu-121",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-3",
    teacher: "平井 広志 / HIRAI Hiroshi",
  },
  {
    id: "natu-122",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-3",
    teacher: "藤原 一宏 / FUJIWARA Kazuhiro",
  },
  {
    id: "natu-123",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-3",
    teacher: "林 孝宏 / HAYASHI Takahiro",
  },
  {
    id: "natu-124",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-3",
    teacher: "谷川 好男 / TANIGAWA Yoshio",
  },
  {
    id: "natu-125",
    title: "物理学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-4",
    teacher: "谷村 省吾 / TANIMURA Shogo",
  },
  {
    id: "natu-126",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-4",
    teacher: "村井 征史 / MURAI Masahito",
  },
  {
    id: "natu-127",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-4",
    teacher: "山田 泰之 / YAMADA Yasuyuki",
  },
  {
    id: "natu-128",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-4",
    teacher: "八木 亜樹子 / YAGI Akiko",
  },
  {
    id: "natu-129",
    title: "力学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-4",
    teacher: "伊藤 孝寛 原田 俊太 / ITO Takahiro HARADA Shunta",
  },
  {
    id: "natu-130",
    title: "電磁気学I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-4",
    teacher: "高橋 康史 / TAKAHASHI Yasufumi",
  },
  {
    id: "natu-131",
    title: "生物学実験",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-4",
    teacher:
      "寳珠山 稔 永田 浩三 佐藤 光夫 石川 哲也 / HOSHIYAMA Minoru NAGATA Kohzo SATO Mitsuo ISHIKAWA Tetsuya",
  },
  {
    id: "natu-132",
    title: "化学実験",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-4",
    teacher:
      "新美 友章 珠玖 良昭 前尾 健一郎 佐藤 ちひろ 柴田 貴広 渡邉 健史 大島 健司 / NIIMI Tomoaki SHUKU Yoshiaki MAEO Kenichiro SATO Chihiro SHIBATA Takahiro WATANABE Takeshi OSHIMA Kenji",
  },
  {
    id: "natu-133",
    title: "物理学実験",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Mon-4",
    teacher:
      "田中 宏彦 大島 大輝 堀出 朋哉 / TANAKA Hirohiko OSHIMA Daiki HORIDE Tomoya",
  },
  {
    id: "natu-134",
    title: "力学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-1",
    teacher: "田代 むつみ / TASHIRO Mutsumi",
  },
  {
    id: "natu-135",
    title: "電磁気学I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-1",
    teacher: "黒澤 昌志 / KUROSAWA Masashi",
  },
  {
    id: "natu-136",
    title: "電磁気学I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-1",
    teacher: "石川 健治 / ISHIKAWA Kenji",
  },
  {
    id: "natu-137",
    title: "電磁気学I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-1",
    teacher: "五十嵐 信行 / IKARASHI Nobuyuki",
  },
  {
    id: "natu-138",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-1",
    teacher: "宇澤 達 / UZAWA Tohru",
  },
  {
    id: "natu-139",
    title: "数学通論II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-2",
    teacher: "GARRIGUE JACQUES",
  },
  {
    id: "natu-140",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-2",
    teacher: "松宮 弘明 / MATSUMIYA Hiroaki",
  },
  {
    id: "natu-141",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-2",
    teacher: "菊田 浩一 / KIKUTA Koichi",
  },
  {
    id: "natu-142",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-2",
    teacher: "鈴木 淳巨 / SUZUKI Atsuo",
  },
  {
    id: "natu-143",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-2",
    teacher: "吉田 朋子 / YOSHIDA Tomoko",
  },
  {
    id: "natu-144",
    title: "力学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-2",
    teacher: "西口 浩司 / NISHIGUCHI Koji",
  },
  {
    id: "natu-145",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "柳浦 睦憲 / YAGIURA Mutsunori",
  },
  {
    id: "natu-146",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "加納 成男 / KANOU Naruo",
  },
  {
    id: "natu-147",
    title: "物理学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "谷山 智康 / TANIYAMA Tomoyasu",
  },
  {
    id: "natu-148",
    title: "電磁気学I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "石橋 明浩 / ISHIBASHI Akihiro",
  },
  {
    id: "natu-149",
    title: "電磁気学I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "清水 裕彦 / SHIMIZU Hirohiko",
  },
  {
    id: "natu-150",
    title: "電磁気学I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "小林 義明 / KOBAYASHI Yoshiaki",
  },
  {
    id: "natu-151",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "谷川 好男 / TANIGAWA Yoshio",
  },
  {
    id: "natu-152",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "小林 善司 / KOBAYASHI Zenji",
  },
  {
    id: "natu-153",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "菊田 浩一 / KIKUTA Koichi",
  },
  {
    id: "natu-154",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "曽我部 知広 / SOGABE Tomohiro",
  },
  {
    id: "natu-155",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "寺澤 祐高 / TERASAWA Yutaka",
  },
  {
    id: "natu-156",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "布施 新一郎 / FUSE Shinichiro",
  },
  {
    id: "natu-157",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "小林 亮 / KOBAYASHI Makoto",
  },
  {
    id: "natu-158",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "稗田 純子 佐藤 勝俊 / HIEDA Junko SATO Katsutoshi",
  },
  {
    id: "natu-159",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "喜多 奈々緒 / KITA Nanao",
  },
  {
    id: "natu-160",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "小林 亮一 / KOBAYASHI Ryoichi",
  },
  {
    id: "natu-161",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-3",
    teacher: "野呂 篤史 / NORO Atsushi",
  },
  {
    id: "natu-162",
    title: "化学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-4",
    teacher:
      "岩松 将一 長尾 征洋 ジンチェンコ アナトーリ / IWAMATSU Sho-ichi NAGAO Masahiro ZINCHENKO Anatoly",
  },
  {
    id: "natu-163",
    title: "生物学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-4",
    teacher:
      "池田 勝秀 川部 勤 永田 浩三 佐藤 光夫 早川 文彦 石川 哲也 松島 充代子 横井 聡 / IKEDA Katsuhide KAWABE Tsutomu NAGATA Kohzo SATO Mitsuo HAYAKAWA Fumihiko ISHIKAWA Tetsuya Matsushima Miyoko YOKOI Satoshi",
  },
  {
    id: "natu-164",
    title: "[遠隔]生物学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-4",
    teacher: "一柳 健司 吉岡 博文 / ICHIYANAGI Kenji YOSHIOKA Hirofumi",
  },
  {
    id: "natu-165",
    title: "生物学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-4",
    teacher: "山篠 貴史 中道 範人 / YAMASHINO Takafumi NAKAMICHI Norihito",
  },
  {
    id: "natu-166",
    title: "電磁気学I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-4",
    teacher: "川瀬 晃道 / KAWASE Kodo",
  },
  {
    id: "natu-167",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-4",
    teacher: "福塚 友和 / FUKUTSUKA Tomokazu",
  },
  {
    id: "natu-168",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-4",
    teacher: "南 和彦 / MINAMI Kazuhiko",
  },
  {
    id: "natu-169",
    title: "化学実験",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-4",
    teacher:
      "愛場 雄一郎 八木 亜樹子 珠玖 良昭 / AIBA Yuichiro YAGI Akiko SHUKU Yoshiaki",
  },
  {
    id: "natu-170",
    title: "地球科学実験",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-4",
    teacher:
      "林 誠司 高橋 聡 束田 和弘 永峰 康一郎 阿部 理 日高 洋 / HAYASHI Seiji TAKAHASHI Satoshi TSUKADA Kazuhiro NAGAMINE Koichiro ABE Osamu HIDAKA Hiroshi",
  },
  {
    id: "natu-171",
    title: "物理学実験",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-4",
    teacher:
      "尾上 順 平井 大悟郎 井村 敬一郎 富田 孝史 狩野 絵美 / ONOE Jun HIRAI Daigorou IMURA Keiichiro TOMITA Takashi KANO Emi",
  },
  {
    id: "natu-172",
    title: "地球科学基礎I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-5",
    teacher: "三村 耕一 淺原 良浩 / MIMURA Koichi ASAHARA Yoshihiro",
  },
  {
    id: "natu-173",
    title: "電磁気学I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Tue-5",
    teacher: "横水 康伸 / YOKOMIZU Yasunobu",
  },
  {
    id: "natu-174",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-2",
    teacher: "髙見 誠一 宮町 俊生 / TAKAMI Seiichi MIYAMACHI Toshio",
  },
  {
    id: "natu-175",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-2",
    teacher: "川村 友美 / KAWAMURA Tomomi",
  },
  {
    id: "natu-176",
    title: "線形代数学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-2",
    teacher: "中西 知樹 / NAKANISHI Tomoki",
  },
  {
    id: "natu-177",
    title: "電磁気学I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-2",
    teacher: "田中 宏昌 / TANAKA Hiromasa",
  },
  {
    id: "natu-178",
    title: "電磁気学I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-2",
    teacher: "天野 浩 / AMANO Hiroshi",
  },
  {
    id: "natu-179",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-3",
    teacher: "小野 廣隆 / ONO Hirotaka",
  },
  {
    id: "natu-180",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-3",
    teacher: "大橋 あすか / OHASHI Asuka",
  },
  {
    id: "natu-181",
    title: "地球科学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-3",
    teacher:
      "道林 克禎 持田 陸宏 高橋 聡 / MICHIBAYASHI Katsuyoshi MOCHIDA Michihiro TAKAHASHI Satoshi",
  },
  {
    id: "natu-182",
    title: "地球科学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-3",
    teacher:
      "高橋 聡 持田 陸宏 道林 克禎 / TAKAHASHI Satoshi MOCHIDA Michihiro MICHIBAYASHI Katsuyoshi",
  },
  {
    id: "natu-183",
    title: "物理学基礎II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-3",
    teacher: "北口 雅暁 / KITAGUCHI Masaaki",
  },
  {
    id: "natu-184",
    title: "[遠隔]数学通論II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-3",
    teacher: "小林 亮一 / KOBAYASHI Ryoichi",
  },
  {
    id: "natu-185",
    title: "数学通論II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-3",
    teacher: "久保 明達 / KUBO Akisato",
  },
  {
    id: "natu-186",
    title: "数学通論II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-3",
    teacher: "森本 宏 / MORIMOTO Hiroshi",
  },
  {
    id: "natu-187",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-4",
    teacher: "森本 宏 / MORIMOTO Hiroshi",
  },
  {
    id: "natu-188",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-4",
    teacher: "濱中 真志 / HAMANAKA Masashi",
  },
  {
    id: "natu-189",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-4",
    teacher: "高橋 康史 / TAKAHASHI Yasufumi",
  },
  {
    id: "natu-190",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-4",
    teacher: "白水 徹也 / SHIROMIZU Tetsuya",
  },
  {
    id: "natu-191",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-4",
    teacher: "椿野 大輔 / TSUBAKINO Daisuke",
  },
  {
    id: "natu-192",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-4",
    teacher: "永尾 太郎 / NAGAO Taro",
  },
  {
    id: "natu-193",
    title: "電磁気学I",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-4",
    teacher: "内山 剛 / UCHIYAMA Tsuyoshi",
  },
  {
    id: "natu-194",
    title: "化学実験",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-4",
    teacher:
      "松本 健太郎 SONG Yuxi 長尾 征洋 / MATSUMOTO Kentaro SONG Yuxi NAGAO Masahiro",
  },
  {
    id: "natu-195",
    title: "化学実験",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-4",
    teacher:
      "長尾 征洋 SONG Yuxi 松本 健太郎 / NAGAO Masahiro SONG Yuxi MATSUMOTO Kentaro",
  },
  {
    id: "natu-196",
    title: "物理学実験",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Thu-4",
    teacher:
      "舘石 和雄 小川 信之 石垣 範和 竹野 思温 小島 寛樹 / TATEISHI Kazuo OGAWA Nobuyuki ISHIGAKI Norikazu TAKENO Shion KOJIMA Hiroki",
  },
  {
    id: "natu-197",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Fri-1",
    teacher: "太田 啓史 / OHTA Hiroshi",
  },
  {
    id: "natu-198",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Fri-1",
    teacher: "荒野 悠輝 / ARANO Yuki",
  },
  {
    id: "natu-199",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Fri-1",
    teacher: "粟田 英資 / AWATA Hidetoshi",
  },
  {
    id: "natu-200",
    title: "微分積分学II",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Fri-1",
    teacher: "中島 誠 / NAKASHIMA Makoto",
  },
  {
    id: "natu-201",
    title: "物理学実験",
    section: "自然教養",
    department: "全学",
    semester: "春2",
    cellKey: "Fri-4",
    teacher:
      "松岡 健 本村 扇仁 井村 敬一郎 伊東山 登 LEE Kyungki / MATSUOKA Ken MOTOMURA Senni IMURA Keiichiro ITOYAMA Noboru LEE Kyungki",
  },
  {
    id: "natu-202",
    title: "複素関数論",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "佐藤 潤也 / SATOH Junya",
  },
  {
    id: "natu-203",
    title: "複素関数論",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "柳田 伸太郎 / YANAGIDA Shintaro",
  },
  {
    id: "natu-204",
    title: "複素関数論",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "植田 好道 / UEDA Yoshimichi",
  },
  {
    id: "natu-205",
    title: "複素関数論",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "橋本 貴宏 / HASHIMOTO Takahiro",
  },
  {
    id: "natu-206",
    title: "複素関数論",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "岩下 弘一 / IWASHITA Hirokazu",
  },
  {
    id: "natu-207",
    title: "複素関数論",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "久保 仁 / KUBO Masashi",
  },
  {
    id: "natu-208",
    title: "複素関数論",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "吉田 伸生 / YOSHIDA Nobuo",
  },
  {
    id: "natu-209",
    title: "複素関数論",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "中村 勇哉 / NAKAMURA Yusuke",
  },
  {
    id: "natu-210",
    title: "物理学実験",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "國生 拓摩 安藤 幸世 / KOKUSHO Takuma ANDO Kosei",
  },
  {
    id: "natu-211",
    title: "電磁気学II",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "原田 俊太 塚田 祐貴 / HARADA Shunta TSUKADA Yuki",
  },
  {
    id: "natu-212",
    title: "電磁気学II",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "棚橋 誠治 / TANABASHI Masaharu",
  },
  {
    id: "natu-213",
    title: "電磁気学II",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "清水 裕彦 / SHIMIZU Hirohiko",
  },
  {
    id: "natu-214",
    title: "複素関数論",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "中村 豪 / NAKAMURA Go",
  },
  {
    id: "natu-215",
    title: "複素関数論",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "久保 仁 / KUBO Masashi",
  },
  {
    id: "natu-216",
    title: "複素関数論",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "石井 亮 / ISHII Akira",
  },
  {
    id: "natu-217",
    title: "複素関数論",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "Neal Bez",
  },
  {
    id: "natu-218",
    title: "電磁気学II",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "高橋 徹 / TAKAHASHI Toru",
  },
  {
    id: "natu-219",
    title: "電磁気学II",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "梅原 徳次 / UMEHARA Noritsugu",
  },
  {
    id: "natu-220",
    title: "電磁気学II",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "竹延 大志 / TAKENOBU Taishi",
  },
  {
    id: "natu-221",
    title: "電磁気学II",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "長尾 全寛 / NAGAO Masahiro",
  },
  {
    id: "natu-222",
    title: "電磁気学II",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "西澤 典彦 / NISHIZAWA Norihiko",
  },
  {
    id: "natu-223",
    title: "電磁気学II",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "岡本 敦 / OKAMOTO Atsushi",
  },
  {
    id: "natu-224",
    title: "地球科学実験",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "杉谷 健一郎 / SUGITANI Kenichiro",
  },
  {
    id: "natu-225",
    title: "物理学実験",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "井村 敬一郎 / IMURA Keiichiro",
  },
  {
    id: "natu-226",
    title: "地球科学実験",
    section: "自然教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher: "永峰 康一郎 / NAGAMINE Koichiro",
  },
];
