import { Course } from "../courses";
export const NOW_COURSES: Course[] = [
  {
    id: "now-1",
    title: "[遠隔][G30]イノベーション基礎",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "河野 憲嗣 / KONO Kenji",
  },
  {
    id: "now-2",
    title: "[遠隔][岐大連携]連携開設科目(北欧のことばと地域の方言)",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "大宮 康一 / OMIYA Koichi",
  },
  {
    id: "now-3",
    title: "[遠隔][岐大連携]連携開設科目(実践生物化学)",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "竹森 洋 / TAKEMORI Hiroshi",
  },
  {
    id: "now-4",
    title: "[岐大連携]連携開設科目(リトアニア学)",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher: "毛利 哲也 / MOURI Tetsuya",
  },
  {
    id: "now-5",
    title: "[遠隔][岐大連携]連携開設科目(地域と環境SDGs)",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher: "櫻田 修 / SAKURADA Osamu",
  },
  {
    id: "now-6",
    title: "[遠隔][岐大連携]連携開設科目(経営学とは何か)",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "大澤 圭吾 / OSAWA Keigo",
  },
  {
    id: "now-7",
    title: "[遠隔][岐大連携]連携開設科目(まちづくりリーダー入門)",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "髙木 朗義 / TAKAGI Akiyoshi",
  },
  {
    id: "now-8",
    title: "[遠隔][岐大連携]連携開設科目(岐阜にまつわる東洋史)",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Tue-5",
    teacher: "塚本 明日香 / TSUKAMOTO Asuka",
  },
  {
    id: "now-9",
    title: "[遠隔][岐大連携]連携開設科目(実用作曲法)",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "西尾 洋 / NISHIO Yo",
  },
  {
    id: "now-10",
    title: "環境学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher:
      "谷川 東子 原田 一宏 梶村 恒 / TANIKAWA Toko HARADA Kazuhiro KAJIMURA Hisashi",
  },
  {
    id: "now-11",
    title: "文化論・芸術論",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "影山 悦子 / KAGEYAMA Etsuko",
  },
  {
    id: "now-12",
    title: "クリエイティブイノベーション講座",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "河野 廉 矢野 貴大 / KAWANO Yasushi YANO Takahiro",
  },
  {
    id: "now-13",
    title: "科学論・技術論",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "井上 研 久木田 水生 / INOUE Ken KUKITA Minao",
  },
  {
    id: "now-14",
    title: "芸術論A",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "梶田 美香 / KAJITA Mika",
  },
  {
    id: "now-15",
    title: "芸術論B",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "秋庭 史典 / AKIBA Fuminori",
  },
  {
    id: "now-16",
    title: "現代社会と教育",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "河野 明日香 / KAWANO Asuka",
  },
  {
    id: "now-17",
    title: "歴史学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "河西 秀哉 / KAWANISHI Hideya",
  },
  {
    id: "now-18",
    title: "言語学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "李 澤熊 / LEE Tack ung",
  },
  {
    id: "now-19",
    title: "文化・芸術学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "重見 晋也 / SHIGEMI Shinya",
  },
  {
    id: "now-20",
    title: "社会学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "室井 研二 / MUROI Kenji",
  },
  {
    id: "now-21",
    title: "心理学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "江副 文美 / EZOE Ayami",
  },
  {
    id: "now-22",
    title: "心理学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "井関 紗代 / ISEKI Sayo",
  },
  {
    id: "now-23",
    title: "日本国憲法",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "杉原 周治 / SUGIHARA Syuuji",
  },
  {
    id: "now-24",
    title: "法学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "西井 志織 / NISHII Shiori",
  },
  {
    id: "now-25",
    title: "政治学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "大久保 明 / OKUBO Akira",
  },
  {
    id: "now-26",
    title: "経済概論",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "林 亜瓊 清水 克俊 / LIN Yaqiong SHIMIZU Katsutoshi",
  },
  {
    id: "now-27",
    title: "[遠隔]経営・会計入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "中島 英喜 / NAKASHIMA Hideki",
  },
  {
    id: "now-28",
    title: "環境学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "南 雅代 中塚 武 / MINAMI Masayo NAKATSUKA Takeshi",
  },
  {
    id: "now-29",
    title: "博物館概論",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "新美 倫子 / NIIMI Michiko",
  },
  {
    id: "now-30",
    title: "キャリア形成論",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "森 典華 / MORI Norika",
  },
  {
    id: "now-31",
    title: "大学でどう生きるか",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "鈴木 健一 船津 静代 / SUZUKI Kenichi FUNATSU Shizuyo",
  },
  {
    id: "now-32",
    title: "青年期における心の健康",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher:
      "鈴木 健一 船津 静代 土井 康裕 長島 渉 横井 綾 竹本 美穗 古橋 忠晃 森 典華 工藤 晋平 杉岡 正典 / SUZUKI Kenichi FUNATSU Shizuyo DOI Yasuhiro NAGASHIMA Wataru YOKOI Aya TAKEMOTO Miho FURUHASHI Tadaaki MORI Norika KUDO Shimpei SUGIOKA Masanori",
  },
  {
    id: "now-33",
    title: "社会安全学",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "富田 賢吾 / TOMITA Kengo",
  },
  {
    id: "now-34",
    title: "ジェンダー学",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "林 葉子 徐 玉 / HAYASHI Yoko JO Gyoku",
  },
  {
    id: "now-35",
    title: "学問の面白さを知る",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "榊原 均 福田 努 / SAKAKIBARA Hitoshi FUKUDA Tsutomu",
  },
  {
    id: "now-36",
    title: "名古屋大学の歴史",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "堀田 慎一郎 / HOTTA Shin'ichiroh",
  },
  {
    id: "now-37",
    title: "防災減災学",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "鷺谷 威 / SAGIYA Takeshi",
  },
  {
    id: "now-38",
    title: "医療人類学",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "梅村 絢美 宮地 純一郎 / UMEMURA Ayami MIYACHI Junichiro",
  },
  {
    id: "now-39",
    title: "芸術論B",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "日栄 一真 / HIEI Kazumasa",
  },
  {
    id: "now-40",
    title: "[遠隔]社会課題解決とアントレプレナーシップ",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "新村 和大 / SHINMURA Kazuhiro",
  },
  {
    id: "now-41",
    title: "物理学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher:
      "松岡 健 野々村 拓 社本 英二 / MATSUOKA Ken NONOMURA Taku SHAMOTO Eiji",
  },
  {
    id: "now-42",
    title: "材料科学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher:
      "市野 良一 山内 悠輔 稲垣 伸二 / ICHINO Ryoichi YAMAUCHI Yusuke INAGAKI Shinji",
  },
  {
    id: "now-43",
    title: "生命科学入門B",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher:
      "柴田 秀樹 辻 寛之 本道 栄一 / SHIBATA Hideki TSUJI Hiroyuki HONDO Eiichi",
  },
  {
    id: "now-44",
    title: "地球惑星科学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "山中 佳子 / YAMANAKA Yoshiko",
  },
  {
    id: "now-45",
    title: "現代医学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "松下 正 / MATSUSHITA Tadashi",
  },
  {
    id: "now-46",
    title: "現代数学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "谷本 祥 / TANIMOTO Sho",
  },
  {
    id: "now-47",
    title: "放射線と放射能",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher:
      "柴田 理尋 杉田 亮平 加茂前 健 / SHIBATA Michihiro SUGITA Ryohei KAMOMAE Takeshi",
  },
  {
    id: "now-48",
    title: "[岐大連携]連携開設科目(マネジメントシステムと監査)",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    teacher: "櫻田 修 / SAKURADA Osamu",
  },
  {
    id: "now-49",
    title: "[岐大連携]連携開設科目(世界農業遺産入門)",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    teacher: "伊藤 浩二 / ITO Koji",
  },
  {
    id: "now-50",
    title: "[岐大連携]連携開設科目(地域系協学実習(職場体験)I)",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    teacher: "大宮 康一 / OMIYA Koichi",
  },
  {
    id: "now-51",
    title: "[岐大連携]連携開設科目(産業系協学実習(職場体験)I)",
    section: "現代教養",
    department: "全学",
    semester: "秋1",
    teacher: "大宮 康一 / OMIYA Koichi",
  },
  {
    id: "now-52",
    title: "[遠隔][岐大連携]連携開設科目(社会の基盤)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Mon-2",
    teacher: "國枝 稔 / KUNIEDA Minoru",
  },
  {
    id: "now-53",
    title:
      "[遠隔][岐大連携]連携開設科目(Amishのライフスタイルから現代社会を考える)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Mon-2",
    teacher: "大藪 千穂 / OYABU Chiho",
  },
  {
    id: "now-54",
    title: "[遠隔][岐大連携]連携開設科目(岐阜県の環境教育と科学・技術)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Mon-3",
    teacher: "大場 伸也 / OBA Shinya",
  },
  {
    id: "now-55",
    title: "[遠隔][岐大連携]連携開設科目(西洋近現代思想)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Tue-2",
    teacher: "長谷川 暁人 / HASEGAWA Akito",
  },
  {
    id: "now-56",
    title: "[遠隔][岐大連携]連携開設科目(アイスランド語)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Tue-3",
    teacher: "大宮 康一 / OMIYA Koichi",
  },
  {
    id: "now-57",
    title: "[遠隔][岐大連携]連携開設科目(中国史)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Tue-5",
    teacher: "塚本 明日香 / TSUKAMOTO Asuka",
  },
  {
    id: "now-58",
    title: "[岐大連携]連携開設科目(実用例から学ぶプラズマ)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Tue-5",
    teacher: "伊藤 貴司 / ITOH Takashi",
  },
  {
    id: "now-59",
    title: "[遠隔][岐大連携]連携開設科目(メタバース文化論)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Tue-5",
    teacher: "尾関 智恵 / OZEKI Tomoe",
  },
  {
    id: "now-60",
    title: "[遠隔][岐大連携]連携開設科目(実用作曲法)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Wed-1",
    teacher: "西尾 洋 / NISHIO Yo",
  },
  {
    id: "now-61",
    title:
      "[遠隔][岐大連携]連携開設科目(地球史における環境問題:水・土・生命・人)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Wed-1",
    teacher: "大西 健夫 / ONISHI Takeo",
  },
  {
    id: "now-62",
    title: "化学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-1",
    teacher: "中谷 肇 / NAKATANI Hajime",
  },
  {
    id: "now-63",
    title: "生命科学入門A",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-1",
    teacher:
      "成田 哲博 瀧口 金吾 平子 善章 / NARITA Akihiro TAKIGUCHI Kingo HIRAKO Yoshiaki",
  },
  {
    id: "now-64",
    title: "生命科学入門B",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-1",
    teacher:
      "大川 妙子 山内 卓樹 上野山 賀久 / OHKAWA Taeko YAMAUCHI Takaki UENOYAMA Yoshihisa",
  },
  {
    id: "now-65",
    title: "大気水圏科学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-1",
    teacher: "坂井 亜規子 / SAKAI Akiko",
  },
  {
    id: "now-66",
    title: "現代医学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-1",
    teacher: "榎本 篤 / ENOMOTO Atsushi",
  },
  {
    id: "now-67",
    title: "現代社会と教育",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-2",
    teacher: "坂本 將暢 / SAKAMOTO Masanobu",
  },
  {
    id: "now-68",
    title: "哲学・思想入門",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-2",
    teacher: "崔 境眞 / CHOI Kyeong Jin",
  },
  {
    id: "now-69",
    title: "言語学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-2",
    teacher: "長崎 郁 / NAGASAKI Iku",
  },
  {
    id: "now-70",
    title: "政治学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-2",
    teacher: "姜 東局 / KANG Dongkook",
  },
  {
    id: "now-71",
    title: "キャリア形成論",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-2",
    teacher: "森 典華 / MORI Norika",
  },
  {
    id: "now-72",
    title: "環境学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-2",
    teacher: "増田 雄司 / MASUDA Yuji",
  },
  {
    id: "now-73",
    title: "地域医療フィールドワーク入門",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-2",
    teacher: "梅村 絢美 宮地 純一郎 / UMEMURA Ayami MIYACHI Junichiro",
  },
  {
    id: "now-74",
    title: "芸術論A",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-2",
    teacher: "酒井 健宏 / SAKAI Takehiro",
  },
  {
    id: "now-75",
    title: "[遠隔]イノベーション基礎",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-2",
    teacher: "河野 憲嗣 / KONO Kenji",
  },
  {
    id: "now-76",
    title: "シリアル・イノベーション",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-2",
    teacher: "光井 將一 松本 修平 / MITSUSI Shoichi",
  },
  {
    id: "now-77",
    title: "現代社会と教育",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-3",
    teacher: "丸山 和昭 / MARUYAMA Kazuaki",
  },
  {
    id: "now-78",
    title: "言語学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-3",
    teacher: "李 澤熊 / LEE Tack ung",
  },
  {
    id: "now-79",
    title: "文化・芸術学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-3",
    teacher: "伊藤 大輔 / ITO Daisuke",
  },
  {
    id: "now-80",
    title: "心理学入門",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-3",
    teacher: "河野 荘子 / KONO Shoko",
  },
  {
    id: "now-81",
    title: "日本国憲法",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-3",
    teacher: "神山 智美 / KOUYAMA Satomi",
  },
  {
    id: "now-82",
    title: "経済概論",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-3",
    teacher: "福澤 直樹 / FUKUZAWA Naoki",
  },
  {
    id: "now-83",
    title: "メディアリテラシー",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    cellKey: "Fri-5",
    teacher: "後藤 明史 / GOTO Akifumi",
  },
  {
    id: "now-84",
    title: "[岐大連携]連携開設科目(野外活動実習)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    teacher: "後藤 誠一 / GOTO Seiichi",
  },
  {
    id: "now-85",
    title: "[岐大連携]連携開設科目(地域系協学実習(職場体験)II)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    teacher: "大宮 康一 / OMIYA Koichi",
  },
  {
    id: "now-86",
    title: "[岐大連携]連携開設科目(産業系協学実習(職場体験)II)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    teacher: "大宮 康一 / OMIYA Koichi",
  },
  {
    id: "now-87",
    title: "[遠隔][岐大連携]連携開設科目(持続可能な地域と環境リテラシー)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    teacher: "岩澤 淳 / IWASAWA Atsushi",
  },
  {
    id: "now-88",
    title: "[岐大連携]連携開設科目(まちづくりリーダー実践)",
    section: "現代教養",
    department: "全学",
    semester: "秋2",
    teacher: "髙木 朗義 / TAKAGI Akiyoshi",
  },
  {
    id: "now-89",
    title: "科学・技術の倫理",
    section: "現代教養",
    department: "全学",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "笠木 雅史 / V Fri 1 笠木 雅史 / KASAKI Masashi",
  },
  {
    id: "now-90",
    title: "[遠隔]医学と教養",
    section: "現代教養",
    department: "全学",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "錦織 宏 / V Fri 1 錦織 宏 / NISHIGORI Hiroshi",
  },
  {
    id: "now-91",
    title: "科学史・技術史",
    section: "現代教養",
    department: "全学",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "竹下 至 / V Fri 2 竹下 至 / TAKESHITA Itaru",
  },
  {
    id: "now-92",
    title: "芸術論A",
    section: "現代教養",
    department: "全学",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "青山 太郎 / V Fri 2 青山 太郎 / AOYAMA Taro",
  },
  {
    id: "now-93",
    title: "環境学入門",
    section: "現代教養",
    department: "全学",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "小松 尚 / V Fri 2 小松 尚 / KOMATSU Hisashi",
  },
  {
    id: "now-94",
    title: "芸術論B",
    section: "現代教養",
    department: "全学",
    semester: "春2",
    cellKey: "Fri-2",
    teacher: "山田 亘 / VI Fri 2 山田 亘 / YAMADA Ko",
  },
  {
    id: "now-95",
    title: "ライフスキル入門",
    section: "現代教養",
    department: "全学",
    semester: "春2",
    cellKey: "Fri-2",
    teacher:
      "船津 静代 林 陽子 竹本 美穗 森 典華 工藤 晋平 鈴木 健一 杉岡 正典 / VI Fri 2 船津 静代 林 陽子 竹本 美穗 森 典華 工藤 晋平 鈴木 健一 杉岡 正典 / FUNATSU Shizuyo HAYASHI Yoko TAKEMOTO Miho MORI Norika KUDO Shimpei SUZUKI Kenichi SUGIOKA Masanori",
  },
];
