import { Course } from "../courses";
export const TECH_COURSES: Course[] = [
  {
    id: "info-1",
    title: "[G30]無機材料化学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "info-2",
    title: "マテリアル量子化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "塚田 祐貴 宇佐美 徳隆 / TSUKADA Yuki USAMI Noritaka",
  },
  {
    id: "info-3",
    title: "センシングシステム工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "藤井 俊彰 / FUJII Toshiaki",
  },
  {
    id: "info-4",
    title: "エネルギー変換工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "工学部教務 義家 亮 / YOSHIIE Ryo",
  },
  {
    id: "info-5",
    title: "ディジタル回路",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "奥田 裕之 / OKUDA Hiroyuki",
  },
  {
    id: "info-6",
    title: "鉄筋コンクリート構造",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "日比野 陽 / HIBINO Yo",
  },
  {
    id: "info-7",
    title: "生物反応工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "堀 克敏 鈴木 淳巨 中谷 肇 / HORI Katsutoshi SUZUKI Atsuo NAKATANI Hajime",
  },
  {
    id: "info-8",
    title: "材料塑性学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "髙田 尚記 原田 寛 / TAKATA Naoki HARADA Hiroshi",
  },
  {
    id: "info-9",
    title: "真空電子工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "五十嵐 信行 / IKARASHI Nobuyuki",
  },
  {
    id: "info-10",
    title: "[G30]環境とリサイクル",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "吉田 朋子 / YOSHIDA Tomoko",
  },
  {
    id: "info-11",
    title: "材料科学第2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "櫻井 淳平 秦 誠一 / SAKURAI Junpei HATA Seiichi",
  },
  {
    id: "info-12",
    title: "放射線保健物理学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "吉橋 幸子 / YOSHIHASHI Sachiko",
  },
  {
    id: "info-13",
    title: "量子ビーム分析科学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "尾上 順 山田 智明 桒原 真人 中谷 真人 柚原 淳司 吉田 朋子 富田 英生 / ONOE Jun YAMADA Tomoaki KUWAHARA Makoto NAKAYA Masato YUHARA Junji YOSHIDA Tomoko TOMITA Hideki",
  },
  {
    id: "info-14",
    title: "放射線安全工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "吉橋 幸子 / YOSHIHASHI Sachiko",
  },
  {
    id: "info-15",
    title: "沿岸海象力学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "中村 友昭 / NAKAMURA Tomoaki",
  },
  {
    id: "info-16",
    title: "建築史第2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "堀田 典裕 / HOTTA Yoshihiro",
  },
  {
    id: "info-17",
    title: "[G30]流体力学及び演習",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "info-18",
    title: "高分子合成化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "上垣外 正己 井改 知幸 / KAMIGAITO Masami IKAI Tomoyuki",
  },
  {
    id: "info-19",
    title: "物理工学演習5a",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher:
      "寺田 智樹 田仲 由喜夫 池谷 聡 古谷 浩一朗 / TERADA Tomoki TANAKA Yukio IKEGAYA Satoshi FURUTANI Koichiro",
  },
  {
    id: "info-20",
    title: "物理工学演習5b",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "寺田 智樹 竹中 康司 / TERADA Tomoki TAKENAKA Koshi",
  },
  {
    id: "info-21",
    title: "物理化学演習",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher:
      "松宮 弘明 朝倉 裕介 稗田 純子 / MATSUMIYA Hiroaki ASAKURA Yusuke HIEDA Junko",
  },
  {
    id: "info-22",
    title: "[G30]自動車の電子機器",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "栗本 宗明 / KURIMOTO Muneaki",
  },
  {
    id: "info-23",
    title: "動的システム論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "竹内 一郎 / TAKEUCHI Ichiro",
  },
  {
    id: "info-24",
    title: "機械学習",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "竹内 一郎 / TAKEUCHI Ichiro",
  },
  {
    id: "info-25",
    title: "エネルギーシステム工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "西川原 理仁 / NISHIKAWARA Masahito",
  },
  {
    id: "info-26",
    title: "放射線計測学B",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "瓜谷 章 / URITANI Akira",
  },
  {
    id: "info-27",
    title: "材料力学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "桒原 真人 / KUWAHARA Makoto",
  },
  {
    id: "info-28",
    title: "交通論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "中村 英樹 山本 俊行 / NAKAMURA Hideki YAMAMOTO Toshiyuki",
  },
  {
    id: "info-29",
    title: "交通論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "中村 英樹 山本 俊行 / NAKAMURA Hideki YAMAMOTO Toshiyuki",
  },
  {
    id: "info-30",
    title: "電気化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "入山 恭寿 / IRIYAMA Yasutoshi",
  },
  {
    id: "info-31",
    title: "固体電子工学及び演習",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "須田 淳 今井 友貴 / SUDA Jun IMAI Yuki",
  },
  {
    id: "info-32",
    title: "固体電子工学及び演習",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "堀出 朋哉 堀田 昌宏 / HORIDE Tomoya HORITA Masahiro",
  },
  {
    id: "info-33",
    title: "[G30]設計製図1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-5",
    teacher: "野老山 貴行 永島 壮 / TOKOROYAMA Takayuki NAGASHIMA So",
  },
  {
    id: "info-34",
    title: "[G30]自動車ダイナミクスと制御",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "伊藤 章 / ITOU Akira",
  },
  {
    id: "info-35",
    title: "数値解析法",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "竹内 一郎 / TAKEUCHI Ichiro",
  },
  {
    id: "info-36",
    title: "データサイエンス",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "竹内 一郎 / TAKEUCHI Ichiro",
  },
  {
    id: "info-37",
    title: "プロセス設計",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-5",
    teacher: "未定(工)",
  },
  {
    id: "info-38",
    title: "航空宇宙機力学第1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-5",
    teacher: "砂田 茂 / SUNADA Shigeru",
  },
  {
    id: "info-39",
    title: "設計製図第1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-5",
    teacher: "永島 壮 野老山 貴行 / NAGASHIMA So TOKOROYAMA Takayuki",
  },
  {
    id: "info-40",
    title: "設計製図第1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Mon-5",
    teacher: "野老山 貴行 永島 壮 / TOKOROYAMA Takayuki NAGASHIMA So",
  },
  {
    id: "info-41",
    title: "[G30]先端有機・高分子化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "福井 識人 / FUKUI Norihito",
  },
  {
    id: "info-42",
    title: "計算物理学および演習",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "田渕 雅夫 / TABUCHI Masao",
  },
  {
    id: "info-43",
    title: "分離システム",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "未定(工) 向井 康人 / MUKAI Yasuhito",
  },
  {
    id: "info-44",
    title: "機械的分離システム",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "未定(工) 向井 康人 / MUKAI Yasuhito",
  },
  {
    id: "info-45",
    title: "放射線計測学A",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "富田 英生 / TOMITA Hideki",
  },
  {
    id: "info-46",
    title: "放射線計測学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "富田 英生 / TOMITA Hideki",
  },
  {
    id: "info-47",
    title: "土木の力学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "戸田 祐嗣 / TODA Yuji",
  },
  {
    id: "info-48",
    title: "橋梁設計演習",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "三浦 泰人 中村 光 / MIURA Taito NAKAMURA Hikaru",
  },
  {
    id: "info-49",
    title: "耐震工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "護 雅史 / MORI Masafumi",
  },
  {
    id: "info-50",
    title: "結晶力学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "横井 達矢 / YOKOI Tatsuya",
  },
  {
    id: "info-51",
    title: "混相流動",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "工学部教務",
  },
  {
    id: "info-52",
    title: "生物化学工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "井藤 彰 / ITO Akira",
  },
  {
    id: "info-53",
    title: "電磁波工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "三好 由純 / MIYOSHI Yoshizumi",
  },
  {
    id: "info-54",
    title: "原子炉物理学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "遠藤 知弘 / ENDO Tomohiro",
  },
  {
    id: "info-55",
    title: "土質・基礎工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "中野 正樹 / NAKANO Masaki",
  },
  {
    id: "info-56",
    title: "建築法規",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-2",
    teacher:
      "尾﨑 文宣 野田 浩 井上 智 江口 周 護 雅史 / OZAKI Fuminobu NODA Hiroshi INOUE Satoru EGUCHI Syuu MORI Masafumi",
  },
  {
    id: "info-57",
    title: "素材プロセス工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "市野 良一 原田 寛 / ICHINO Ryoichi HARADA Hiroshi",
  },
  {
    id: "info-58",
    title: "[遠隔]電気電子情報工学実験第1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "今岡 淳 / IMAOKA Jun",
  },
  {
    id: "info-59",
    title: "[G30]設計製図3",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "梅原 徳次 / UMEHARA Noritsugu",
  },
  {
    id: "info-60",
    title: "電子回路",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "伊藤 伸太郎 奥田 裕之 / ITOH Shintaro OKUDA Hiroyuki",
  },
  {
    id: "info-61",
    title: "設計製図第4",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "笠原 次郎 秦 誠一 砂田 茂 原 進 / KASAHARA Jiro HATA Seiichi SUNADA Shigeru HARA Susumu",
  },
  {
    id: "info-62",
    title: "土木の統計学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "三輪 富生 / MIWA Tomio",
  },
  {
    id: "info-63",
    title: "地盤材料実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "中井 健太郎 豊田 智大 中野 正樹 野田 利弘 酒井 崇之 / NAKAI Kentaro TOYODA Tomohiro NAKANO Masaki NODA Toshihiro SAKAI Takayuki",
  },
  {
    id: "info-64",
    title: "構造・材料実験法",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "長江 拓也 五十嵐 豪 尾﨑 文宣 AILI Abudushalamu 日比野 陽 / NAGAE Takuya IGARASHI Go OZAKI Fuminobu AILI Abudushalamu HIBINO Yo",
  },
  {
    id: "info-65",
    title: "総合設計及び演習第1(構造)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "長江 拓也 五十嵐 豪 尾﨑 文宣 日比野 陽 / NAGAE Takuya IGARASHI Go OZAKI Fuminobu HIBINO Yo",
  },
  {
    id: "info-66",
    title: "計測基礎論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "佐藤 隆太 / SATO Ryuta",
  },
  {
    id: "info-67",
    title: "工作機械工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-5",
    teacher: "社本 英二 佐藤 隆太 / SHAMOTO Eiji SATO Ryuta",
  },
  {
    id: "info-68",
    title: "テクニカルライティング",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-5",
    teacher:
      "曾 剛 LELEITO Emanuel Langat 李 嘉 / ZENG Gang LELEITO Emanuel Langat LI Jia",
  },
  {
    id: "info-69",
    title: "材料力学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "小橋 眞 鈴木 飛鳥 / KOBASHI Makoto SUZUKI Asuka",
  },
  {
    id: "info-70",
    title: "[G30]自動車のための電子・情報技術",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "大塚 雄一 / OTSUKA Yuichi",
  },
  {
    id: "info-71",
    title: "電力機器工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "横水 康伸 / YOKOMIZU Yasunobu",
  },
  {
    id: "info-72",
    title: "ポテンシャル流れ",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "杵淵 紀世志 / KINEFUCHI Kiyoshi",
  },
  {
    id: "info-73",
    title: "[G30]生物物理学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "Florence Tama",
  },
  {
    id: "info-74",
    title: "有機構造化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "山本 芳彦 内山 峰人 / YAMAMOTO Yoshihiko UCHIYAMA Mineto",
  },
  {
    id: "info-75",
    title: "計算機工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "岩田 哲 / IWATA Tetsu",
  },
  {
    id: "info-76",
    title: "エネルギー材料学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "中谷 真人 / NAKAYA Masato",
  },
  {
    id: "info-77",
    title: "建築計画第1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "小松 尚 / KOMATSU Hisashi",
  },
  {
    id: "info-78",
    title: "物理工学実験第2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher:
      "丹羽 健 中村 優斗 石田 高史 浦田 隆広 佐々木 拓也 矢野 力三 柴山 茂久 坂下 満男 井上 陽登 草ノ瀬 優香 林 兼輔 齊藤 元貴 / NIWA Ken NAKAMURA Yuto ISHIDA Takafumi URATA Takahiro SASAKI Takuya YANO Rikizo SHIBAYAMA Shigehisa SAKASHITA Mitsuo INOUE Takato KUSANOSE Yuka HAYASHI Kensuke SAITO Genki",
  },
  {
    id: "info-79",
    title: "マテリアル工学演習",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher:
      "松宮 弘明 沓掛 健太朗 矢島 健 / MATSUMIYA Hiroaki KUTSUKAKE Kentaro YAJIMA Takeshi",
  },
  {
    id: "info-80",
    title: "[G30]情報通信技術と自動車交通",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-3",
    teacher:
      "三輪 富生 中村 英樹 山本 俊行 / MIWA Tomio NAKAMURA Hideki YAMAMOTO Toshiyuki",
  },
  {
    id: "info-81",
    title: "機械・航空宇宙工学実験第1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "丸山 央峰 / MARUYAMA Hisataka",
  },
  {
    id: "info-82",
    title: "水理学実験",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher:
      "中村 友昭 趙 容桓 周 月霞 / NAKAMURA Tomoaki CHO Yonghwan ZHOU Yuexia",
  },
  {
    id: "info-83",
    title: "情報処理演習",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-3",
    teacher: "平山 修久 / HIRAYAMA Nagahisa",
  },
  {
    id: "info-84",
    title: "建築設計及び演習第1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher:
      "堀田 典裕 安藤 寿孝 平野 勝雅 恒川 和久 李 燕 斉藤 孝治 / HOTTA Yoshihiro ANDOU Toshitaka HIRANO Katsumasa TSUNEKAWA Kazuhisa LI Yan SAITO Koji",
  },
  {
    id: "info-85",
    title: "総合設計及び演習第1(計画)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "西澤 泰彦 / NISHIZAWA Yasuhiko",
  },
  {
    id: "info-86",
    title: "総合設計及び演習第1(環境設備)",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "鵜飼 真貴子 / UKAI Makiko",
  },
  {
    id: "info-87",
    title: "航空宇宙機システム",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-5",
    teacher: "稲守 孝哉 非常勤講師 / INAMORI Takaya",
  },
  {
    id: "info-88",
    title: "[遠隔][G30]計算機ソフトウェア2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Wed-4",
    teacher:
      "大塚 雄一 飯島 陽久 米澤 拓郎 小川 浩平 / OTSUKA Yuichi IIJIMA Haruhisa YONEZAWA Takuro OGAWA Kohei",
  },
  {
    id: "info-89",
    title: "化学生命工学演習1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "菊田 浩一 / KIKUTA Koichi",
  },
  {
    id: "info-90",
    title: "[G30]有機化学4",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "info-91",
    title: "ロボット工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "長谷川 泰久 / HASEGAWA Yasuhisa",
  },
  {
    id: "info-92",
    title: "[G30]生化学4",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher:
      "灘野 大太 石黒 澄衞 山篠 貴史 / NADANO Daita ISHIGURO Sumie YAMASHINO Takafumi",
  },
  {
    id: "info-93",
    title: "統計力学B",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "竹中 康司 / TAKENAKA Koshi",
  },
  {
    id: "info-94",
    title: "ソフトマター物理学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "畝山 多加志 / UNEYAMA Takashi",
  },
  {
    id: "info-95",
    title: "化学エネルギーシステム",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "小林 敬幸 小島 義弘 / KOBAYASHI Noriyuki KOJIMA Yoshihiro",
  },
  {
    id: "info-96",
    title: "熱エネルギー工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "小林 敬幸 小島 義弘 / KOBAYASHI Noriyuki KOJIMA Yoshihiro",
  },
  {
    id: "info-97",
    title: "ディジタル信号処理",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "髙橋 桂太 / TAKAHASHI Keita",
  },
  {
    id: "info-98",
    title: "[G30]伝熱工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "info-99",
    title: "自動車工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "水野 幸治 / MIZUNO Koji",
  },
  {
    id: "info-100",
    title: "応用構造力学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "加藤 準治 / KATO Junji",
  },
  {
    id: "info-101",
    title: "環境システム工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "田中 英紀 / TANAKA Hideki",
  },
  {
    id: "info-102",
    title: "物性物理学第2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "森山 貴広 長谷川 正 / MORIYAMA Takahiro HASEGAWA Masashi",
  },
  {
    id: "info-103",
    title: "量子材料化学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "伊東 裕 / ITO Hiroshi",
  },
  {
    id: "info-104",
    title: "先端マテリアル工学概論2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher:
      "沓掛 健太朗 矢島 健 松宮 弘明 / KUTSUKAKE Kentaro YAJIMA Takeshi MATSUMIYA Hiroaki",
  },
  {
    id: "info-105",
    title: "[G30]自動車工学実験2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "LU Shan 野老山 貴行 / LU Shan TOKOROYAMA Takayuki",
  },
  {
    id: "info-106",
    title: "機械・航空宇宙工学実験第1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "丸山 央峰 / MARUYAMA Hisataka",
  },
  {
    id: "info-107",
    title: "物性物理学B",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "中谷 真人 柚原 淳司 / NAKAYA Masato YUHARA Junji",
  },
  {
    id: "info-108",
    title: "材料物理化学第2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "柚原 淳司 中谷 真人 / YUHARA Junji NAKAYA Masato",
  },
  {
    id: "info-109",
    title: "化学物理学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "松永 克志 / MATSUNAGA Katsuyuki",
  },
  {
    id: "info-110",
    title: "電気エネルギー伝送工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "早川 直樹 / HAYAKAWA Naoki",
  },
  {
    id: "info-111",
    title: "原子力燃料サイクル工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "吉田 朋子 / YOSHIDA Tomoko",
  },
  {
    id: "info-112",
    title: "エネルギー資源リサイクル工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "吉田 朋子 / YOSHIDA Tomoko",
  },
  {
    id: "info-113",
    title: "[G30]数学演習2a",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "BOURNE Christopher jack",
  },
  {
    id: "info-114",
    title: "[G30]数学演習2b",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "BACHMANN Henrik lennart",
  },
  {
    id: "info-115",
    title: "電気エネルギー変換工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-5",
    teacher: "岩田 幹正",
  },
  {
    id: "info-116",
    title: "[遠隔]航空宇宙推進工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-5",
    teacher: "杵淵 紀世志 / KINEFUCHI Kiyoshi",
  },
  {
    id: "info-117",
    title: "[遠隔]宇宙推進工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Thu-5",
    teacher: "杵淵 紀世志 / KINEFUCHI Kiyoshi",
  },
  {
    id: "info-118",
    title: "アルゴリズムとデータ構造",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "佐藤 理史 / SATO Satoshi",
  },
  {
    id: "info-119",
    title: "都市環境システム工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-1",
    teacher:
      "林 希一郎 白木 裕斗 白川 博章 谷川 寛樹 / HAYASHI Kiichiro SHIRAKI Hiroto SHIRAKAWA Hiroaki TANIKAWA Hiroki",
  },
  {
    id: "info-120",
    title: "化学生命工学序論",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "鈴木 淳巨 長田 実 浅沼 浩之 村上 裕 堀 克敏 本多 裕之 石原 一彰 山本 芳彦 井改 知幸 大槻 主税 上垣外 正己 忍久保 洋 清中 茂樹 鳥本 司 酒田 陽子 松田 亮太郎 / SUZUKI Atsuo OSADA Minoru ASANUMA Hiroyuki MURAKAMI Hiroshi HORI Katsutoshi HONDA Hiroyuki ISHIHARA Kazuaki YAMAMOTO Yoshihiko IKAI Tomoyuki OHTSUKI Chikara KAMIGAITO Masami SHINOKUBO Hiroshi KIYONAKA Shigeki TORIMOTO Tsukasa SAKATA Yoko MATSUDA Ryotaro",
  },
  {
    id: "info-121",
    title: "無機化学3",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "松田 亮太郎 長田 実 鈴木 一正 長谷川 丈二 / MATSUDA Ryotaro OSADA Minoru SUZUKI Kazumasa HASEGAWA Joji",
  },
  {
    id: "info-122",
    title: "[G30]細胞学4",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "柴田 秀樹 / SHIBATA Hideki",
  },
  {
    id: "info-123",
    title: "連続体の力学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "丹羽 健 / NIWA Ken",
  },
  {
    id: "info-124",
    title: "先端プロセス工学2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "中村 崇司 矢島 健 齋藤 永宏 / NAKAMURA Takashi YAJIMA Takeshi SAITO Nagahiro",
  },
  {
    id: "info-125",
    title: "制御工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "道木 慎二 / DOKI Shinji",
  },
  {
    id: "info-126",
    title: "[G30]自動車化学システム2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "則永 行庸 MIKSIK Frantisek / NORINAGA Koyo MIKSIK Frantisek",
  },
  {
    id: "info-127",
    title: "プラズマ理工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "藤田 隆明 / FUJITA Takaaki",
  },
  {
    id: "info-128",
    title: "人間環境工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "齋藤 輝幸 鵜飼 真貴子 / SAITO Teruyuki UKAI Makiko",
  },
  {
    id: "info-129",
    title: "化学生命工学特別講義",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-4",
    teacher:
      "鈴木 淳巨 堀 克敏 本多 裕之 薩摩 篤 石原 一彰 熊谷 純 井改 知幸 / SUZUKI Atsuo HORI Katsutoshi HONDA Hiroyuki SATSUMA Atsushi ISHIHARA Kazuaki KUMAGAI Jun IKAI Tomoyuki",
  },
  {
    id: "info-130",
    title: "粒子・粉体工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "山本 徹也 / YAMAMOTO Tetsuya",
  },
  {
    id: "info-131",
    title: "粉体工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "山本 徹也 / YAMAMOTO Tetsuya",
  },
  {
    id: "info-132",
    title: "プラズマ工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "豊田 浩孝 / TOYODA Hirotaka",
  },
  {
    id: "info-133",
    title: "固体力学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "吉村 彰記 / YOSHIMURA Akinori",
  },
  {
    id: "info-134",
    title: "コンクリート構造第1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "中村 光 / NAKAMURA Hikaru",
  },
  {
    id: "info-135",
    title: "応用物性",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-4",
    teacher: "黒澤 昌志 小山 剛史 / KUROSAWA Masashi KOYAMA Takeshi",
  },
  {
    id: "info-136",
    title: "反応工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-4",
    teacher: "髙見 誠一 / TAKAMI Seiichi",
  },
  {
    id: "info-137",
    title: "設計製図第2",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-5",
    teacher:
      "青山 忠義 竹内 大 後藤 圭太 / AOYAMA Tadayoshi TAKEUCHI Masaru GOTO Keita",
  },
  {
    id: "info-138",
    title: "技術英語1",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Fri-4",
    teacher: "LELEITO Emanuel Langat",
  },
  {
    id: "info-139",
    title: "物理光学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "岸田 英夫 / KISHIDA Hideo",
  },
  {
    id: "info-140",
    title: "材料機能物性学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "水口 将輝 宮町 俊生 / MIZUGUCHI Masaki MIYAMACHI Toshio",
  },
  {
    id: "info-141",
    title: "半導体工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "天野 浩 / AMANO Hiroshi",
  },
  {
    id: "info-142",
    title: "航空原動機システム",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "笠原 次郎 / KASAHARA Jiro",
  },
  {
    id: "info-143",
    title: "航空推進工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "笠原 次郎 / KASAHARA Jiro",
  },
  {
    id: "info-144",
    title: "コンクリート構造第2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "中村 光 / NAKAMURA Hikaru",
  },
  {
    id: "info-145",
    title: "生物情報工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "加藤 竜司 / KATO Ryuji",
  },
  {
    id: "info-146",
    title: "物性物理学第3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "生田 博志 / IKUTA Hiroshi",
  },
  {
    id: "info-147",
    title: "金属材料学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "足立 吉隆 原田 寛 / ADACHI Yoshitaka HARADA Hiroshi",
  },
  {
    id: "info-148",
    title: "セラミック材料学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "工学部教務",
  },
  {
    id: "info-149",
    title: "先端金属材料学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "足立 吉隆 原田 寛 / ADACHI Yoshitaka HARADA Hiroshi",
  },
  {
    id: "info-150",
    title: "誘電体工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "石川 健治 / ISHIKAWA Kenji",
  },
  {
    id: "info-151",
    title: "生体工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "松本 健郎 / MATSUMOTO Takeo",
  },
  {
    id: "info-152",
    title: "創造設計製作",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "丸山 央峰 / MARUYAMA Hisataka",
  },
  {
    id: "info-153",
    title: "核融合エネルギー基礎工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher:
      "渡邊 清政 田中 照也 中野 治久 / WATANABE Kiyomasa TANAKA Teruya NAKANO Haruhisa",
  },
  {
    id: "info-154",
    title: "核融合エネルギー基礎工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher:
      "渡邊 清政 田中 照也 中野 治久 / WATANABE Kiyomasa TANAKA Teruya NAKANO Haruhisa",
  },
  {
    id: "info-155",
    title: "地盤工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "中野 正樹 / NAKANO Masaki",
  },
  {
    id: "info-156",
    title: "建築史第3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "西澤 泰彦 堀田 典裕 / NISHIZAWA Yasuhiko HOTTA Yoshihiro",
  },
  {
    id: "info-157",
    title: "物理化学6",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher:
      "薩摩 篤 浅沼 浩之 鳥本 司 酒田 陽子 / SATSUMA Atsushi ASANUMA Hiroyuki TORIMOTO Tsukasa SAKATA Yoko",
  },
  {
    id: "info-158",
    title: "物理化学・エネルギー化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher:
      "薩摩 篤 浅沼 浩之 鳥本 司 酒田 陽子 / SATSUMA Atsushi ASANUMA Hiroyuki TORIMOTO Tsukasa SAKATA Yoko",
  },
  {
    id: "info-159",
    title: "[G30]特別演習A",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "菊田 浩一 / KIKUTA Koichi",
  },
  {
    id: "info-160",
    title: "化学反応システム",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "則永 行庸 永岡 勝俊 / NORINAGA Koyo NAGAOKA Katsutoshi",
  },
  {
    id: "info-161",
    title: "触媒反応システム工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "則永 行庸 永岡 勝俊 / NORINAGA Koyo NAGAOKA Katsutoshi",
  },
  {
    id: "info-162",
    title: "オートマトンと形式言語",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "佐藤 理史 / SATO Satoshi",
  },
  {
    id: "info-163",
    title: "パワーエレクトロニクス",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "山本 真義 / YAMAMOTO Masayoshi",
  },
  {
    id: "info-164",
    title: "航空宇宙機力学第2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "稲守 孝哉 / INAMORI Takaya",
  },
  {
    id: "info-165",
    title: "固体化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "山田 智明 / YAMADA Tomoaki",
  },
  {
    id: "info-166",
    title: "材料物理化学第1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "山田 智明 / YAMADA Tomoaki",
  },
  {
    id: "info-167",
    title: "環境情報演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher:
      "白木 裕斗 白川 博章 谷川 寛樹 / SHIRAKI Hiroto SHIRAKAWA Hiroaki TANIKAWA Hiroki",
  },
  {
    id: "info-168",
    title: "建築構造解析及び演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "長江 拓也 / NAGAE Takuya",
  },
  {
    id: "info-169",
    title: "構造材料学及び演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "未定(工) 小橋 眞 / KOBASHI Makoto",
  },
  {
    id: "info-170",
    title: "計算機アーキテクチャ",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "工学部教務",
  },
  {
    id: "info-171",
    title: "開水路水理学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "溝口 裕太 / MIZOGUCHI Yuta",
  },
  {
    id: "info-172",
    title: "計算機プログラミング",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher: "横井 達矢 畝山 多加志 / YOKOI Tatsuya UNEYAMA Takashi",
  },
  {
    id: "info-173",
    title: "機械・航空宇宙システム研修",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher: "高橋 徹 / TAKAHASHI Toru",
  },
  {
    id: "info-174",
    title: "都市・国土計画",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher: "宮脇 勝 中村 晋一郎 / MIYAWAKI Masaru NAKAMURA Shinichiro",
  },
  {
    id: "info-175",
    title: "有機化学5",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "石原 一彰 / ISHIHARA Kazuaki",
  },
  {
    id: "info-176",
    title: "計算アルゴリズム",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "曽我部 知広 / SOGABE Tomohiro",
  },
  {
    id: "info-177",
    title: "磁性体工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "加藤 剛志 / KATO Takeshi",
  },
  {
    id: "info-178",
    title: "情報基礎論",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "伊藤 伸太郎 / ITOH Shintaro",
  },
  {
    id: "info-179",
    title: "情報基礎論",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "福澤 健二 / FUKUZAWA Kenji",
  },
  {
    id: "info-180",
    title: "材料工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "三浦 泰人 / MIURA Taito",
  },
  {
    id: "info-181",
    title: "物理環境工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "飯塚 悟 / IIZUKA Satoru",
  },
  {
    id: "info-182",
    title: "[G30]流体力学2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "info-183",
    title: "無機化学4",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "大槻 主税 長田 実 / OHTSUKI Chikara OSADA Minoru",
  },
  {
    id: "info-184",
    title: "流体物理学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "芳松 克則 / YOSHIMATSU Katsunori",
  },
  {
    id: "info-185",
    title: "拡散システム",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "川尻 喜章 小林 敬幸 / KAWAJIRI Yoshiaki KOBAYASHI Noriyuki",
  },
  {
    id: "info-186",
    title: "情報ネットワーク",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "河口 信夫 / KAWAGUCHI Nobuo",
  },
  {
    id: "info-187",
    title: "[G30]車両計画と車体設計",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "CUI Yi",
  },
  {
    id: "info-188",
    title: "航空宇宙構造工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "吉村 彰記 / YOSHIMURA Akinori",
  },
  {
    id: "info-189",
    title: "設備工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "齋藤 輝幸 鵜飼 真貴子 田中 英紀 / SAITO Teruyuki UKAI Makiko TANAKA Hideki",
  },
  {
    id: "info-190",
    title: "化学生命工学実験3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher:
      "熊谷 純 堂浦 智裕 林 剛介 村山 恵司 荒巻 吉孝 安井 猛 福井 識人 吉本 将悟 ウヤヌク ムハメット 中谷 肇 大村 修平 NAKASHIMA Tsubasa 秋山 裕和 田中 健二郎 八塚 研治 武藤 慶 髙野 秀明 / KUMAGAI Jun DOURA Tomohiro HAYASHI Gosuke MURAYAMA Keiji ARAMAKI Yoshitaka YASUI Takeshi FUKUI Norihito YOSHIMOTO Shogo UYANIK Muhammet NAKATANI Hajime OHMURA Shuhei NAKASHIMA Tsubasa AKIYAMA Hirokazu TANAKA Kenjiro YATSUZUKA Kenji MUTO Kei TAKANO Hideaki",
  },
  {
    id: "info-191",
    title: "[G30]化学生命工学実験3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher:
      "熊谷 純 堂浦 智裕 藤野 公茂 村山 恵司 荒巻 吉孝 安井 猛 福井 識人 吉本 将悟 ウヤヌク ムハメット 中谷 肇 大村 修平 NAKASHIMA Tsubasa 秋山 裕和 田中 健二郎 八塚 研治 武藤 慶 髙野 秀明 / KUMAGAI Jun DOURA Tomohiro FUJINO Tomoshige MURAYAMA Keiji ARAMAKI Yoshitaka YASUI Takeshi FUKUI Norihito YOSHIMOTO Shogo UYANIK Muhammet NAKATANI Hajime OHMURA Shuhei NAKASHIMA Tsubasa AKIYAMA Hirokazu TANAKA Kenjiro YATSUZUKA Kenji MUTO Kei TAKANO Hideaki",
  },
  {
    id: "info-192",
    title: "物性物理学第1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "柴田 基洋 / SHIBATA Kiyou",
  },
  {
    id: "info-193",
    title: "システム制御",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "川尻 喜章 / KAWAJIRI Yoshiaki",
  },
  {
    id: "info-194",
    title: "電気磁気学及び演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "豊田 浩孝 大島 大輝 / TOYODA Hirotaka OSHIMA Daiki",
  },
  {
    id: "info-195",
    title: "電気磁気学及び演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "加藤 丈佳 鈴木 陽香 / KATO Takeyoshi SUZUKI Haruka",
  },
  {
    id: "info-196",
    title: "[G30]自動車工学実験1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "野老山 貴行 LU Shan / TOKOROYAMA Takayuki LU Shan",
  },
  {
    id: "info-197",
    title: "燃焼工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "山本 和弘 / YAMAMOTO Kazuhiro",
  },
  {
    id: "info-198",
    title: "量子線理工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "瓜谷 章 / URITANI Akira",
  },
  {
    id: "info-199",
    title: "建築材料工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "五十嵐 豪 今井 雄介 / IGARASHI Go IMAI Yuusuke",
  },
  {
    id: "info-200",
    title: "[G30]数学演習1a",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "RICHARD Serge charles",
  },
  {
    id: "info-201",
    title: "[G30]数学演習1b",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "BACHMANN Henrik lennart",
  },
  {
    id: "info-202",
    title: "建築史第1",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "西澤 泰彦 / NISHIZAWA Yasuhiko",
  },
  {
    id: "info-203",
    title: "コンクリート工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Tue-5",
    teacher: "五十嵐 豪 日比野 陽 / IGARASHI Go HIBINO Yo",
  },
  {
    id: "info-204",
    title: "分析化学3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher:
      "村上 裕 林 剛介 菊田 浩一 熊谷 純 / MURAKAMI Hiroshi HAYASHI Gosuke KIKUTA Koichi KUMAGAI Jun",
  },
  {
    id: "info-205",
    title: "振動と波動",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "小山 剛史 / KOYAMA Takeshi",
  },
  {
    id: "info-206",
    title: "材料強度学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "髙田 尚記 / TAKATA Naoki",
  },
  {
    id: "info-207",
    title: "電気エネルギー基礎論及び演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "吉田 隆 / YOSHIDA Yutaka",
  },
  {
    id: "info-208",
    title: "電気エネルギー基礎論及び演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "小島 寛樹 / KOJIMA Hiroki",
  },
  {
    id: "info-209",
    title: "無線通信方式",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "水谷 圭一 / MIZUTANI Keiichi",
  },
  {
    id: "info-210",
    title: "設計基礎論",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "秦 誠一 / HATA Seiichi",
  },
  {
    id: "info-211",
    title: "建築基礎構造",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "護 雅史 / MORI Masafumi",
  },
  {
    id: "info-212",
    title: "[G30]化学物理学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "内橋 貴之 / UCHIHASHI Takayuki",
  },
  {
    id: "info-213",
    title: "応用分析化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "村上 裕 林 剛介 菊田 浩一 熊谷 純 / MURAKAMI Hiroshi HAYASHI Gosuke KIKUTA Koichi KUMAGAI Jun",
  },
  {
    id: "info-214",
    title: "生物物理学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "CHAVAS Leonard 千見寺 浄慈 寺田 智樹 / CHAVAS Leonard CHIKENJI George TERADA Tomoki",
  },
  {
    id: "info-215",
    title: "電子デバイス工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "大野 雄高 牧原 克典 / OHNO Yutaka MAKIHARA Katsunori",
  },
  {
    id: "info-216",
    title: "[遠隔][G30]分析化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "王 謙 / WANG Qian",
  },
  {
    id: "info-217",
    title: "材料強度学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "後藤 圭太 / GOTO Keita",
  },
  {
    id: "info-218",
    title: "海岸・海洋工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "趙 容桓 水谷 法美 中村 友昭 / CHO Yonghwan MIZUTANI Norimi NAKAMURA Tomoaki",
  },
  {
    id: "info-219",
    title: "建築計画第2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "恒川 和久 / TSUNEKAWA Kazuhisa",
  },
  {
    id: "info-220",
    title: "総合設計及び演習第2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "西澤 泰彦 / NISHIZAWA Yasuhiko",
  },
  {
    id: "info-221",
    title: "物理工学実験第3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher:
      "丹羽 健 中村 優斗 石田 高史 佐々木 拓也 矢野 力三 柴山 茂久 坂下 満男 小椋 優 井上 陽登 草ノ瀬 優香 林 兼輔 齊藤 元貴 / NIWA Ken NAKAMURA Yuto ISHIDA Takafumi SASAKI Takuya YANO Rikizo SHIBAYAMA Shigehisa SAKASHITA Mitsuo OGURA Yu INOUE Takato KUSANOSE Yuka HAYASHI Kensuke SAITO Genki",
  },
  {
    id: "info-222",
    title: "学生実験2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "安田 啓司 黒川 康良 / YASUDA Keiji KUROKAWA Yasuyoshi",
  },
  {
    id: "info-223",
    title: "マテリアル工学実験応用",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "安田 啓司 黒川 康良 / YASUDA Keiji KUROKAWA Yasuyoshi",
  },
  {
    id: "info-224",
    title: "高電圧工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "早川 直樹 / HAYAKAWA Naoki",
  },
  {
    id: "info-225",
    title: "機械・航空宇宙工学実験第2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "丸山 央峰 / MARUYAMA Hisataka",
  },
  {
    id: "info-226",
    title: "構造材料実験II",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher:
      "判治 剛 加藤 準治 舘石 和雄 中村 光 三浦 泰人 清水 優 西口 浩司 藤島 実里 / HANJI Takeshi KATO Junji TATEISHI Kazuo NAKAMURA Hikaru MIURA Taito SHIMIZU Masaru NISHIGUCHI Koji FUJISHIMA Misato",
  },
  {
    id: "info-227",
    title: "数値解析学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "中井 健太郎 / NAKAI Kentaro",
  },
  {
    id: "info-228",
    title: "建築設計及び演習第2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher:
      "小松 尚 宮脇 勝 三橋 啓史 / KOMATSU Hisashi MIYAWAKI Masaru MIHASHI Hiroshi",
  },
  {
    id: "info-229",
    title: "物性物理学A",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Wed-5",
    teacher: "柚原 淳司 / YUHARA Junji",
  },
  {
    id: "info-230",
    title: "化学生命工学演習2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "菊田 浩一 / KIKUTA Koichi",
  },
  {
    id: "info-231",
    title: "[G30]自動車安全工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "水野 幸治 鈴木 達也 / MIZUNO Koji SUZUKI Tatsuya",
  },
  {
    id: "info-232",
    title: "加工学第2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "秦 誠一 / HATA Seiichi",
  },
  {
    id: "info-233",
    title: "原子力環境安全工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "吉橋 幸子 / YOSHIHASHI Sachiko",
  },
  {
    id: "info-234",
    title: "水文・河川工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "戸田 祐嗣 / TODA Yuji",
  },
  {
    id: "info-235",
    title: "[遠隔][G30]計算化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "柳井 毅 / YANAI Takeshi",
  },
  {
    id: "info-236",
    title: "[G30]高分子化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher:
      "上垣外 正己 浅沼 浩之 竹岡 敬和 野呂 篤史 井改 知幸 / KAMIGAITO Masami ASANUMA Hiroyuki TAKEOKA Yukikazu NORO Atsushi IKAI Tomoyuki",
  },
  {
    id: "info-237",
    title: "物理数学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "飯浜 賢志 / IIHAMA Satoshi",
  },
  {
    id: "info-238",
    title: "光エレクトロニクス",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "西澤 典彦 / NISHIZAWA Norihiko",
  },
  {
    id: "info-239",
    title: "[G30]有機材料",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher:
      "上垣外 正己 浅沼 浩之 竹岡 敬和 野呂 篤史 井改 知幸 / KAMIGAITO Masami ASANUMA Hiroyuki TAKEOKA Yukikazu NORO Atsushi IKAI Tomoyuki",
  },
  {
    id: "info-240",
    title: "[G30]自動車エンジンと新動力システム",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "瀧本 藤夫 / TAKIMOTO Fujio",
  },
  {
    id: "info-241",
    title: "有限要素法",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "永島 壮 / NAGASHIMA So",
  },
  {
    id: "info-242",
    title: "鋼構造工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "舘石 和雄 / TATEISHI Kazuo",
  },
  {
    id: "info-243",
    title: "構造設計工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "尾﨑 文宣 / OZAKI Fuminobu",
  },
  {
    id: "info-244",
    title: "化学生命工学実験4",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher:
      "日下 心平 髙野 敦志 竹岡 敬和 内山 峰人 山本 瑛祐 織田 晃 野呂 篤史 秋吉 一孝 齋藤 卓穂 井改 知幸 長谷川 丈二 松川 祐子 / KUSAKA Shinpei TAKANO Atsushi TAKEOKA Yukikazu UCHIYAMA Mineto YAMAMOTO Eisuke ODA Akira NORO Atsushi AKIYOSHI Kazutaka SAITO Takuho IKAI Tomoyuki HASEGAWA Joji MATSUKAWA Yuko",
  },
  {
    id: "info-245",
    title: "[G30]化学生命工学実験4",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher:
      "日下 心平 髙野 敦志 竹岡 敬和 内山 峰人 山本 瑛祐 織田 晃 野呂 篤史 秋吉 一孝 齋藤 卓穂 井改 知幸 長谷川 丈二 松川 祐子 / KUSAKA Shinpei TAKANO Atsushi TAKEOKA Yukikazu UCHIYAMA Mineto YAMAMOTO Eisuke ODA Akira NORO Atsushi AKIYOSHI Kazutaka SAITO Takuho IKAI Tomoyuki HASEGAWA Joji MATSUKAWA Yuko",
  },
  {
    id: "info-246",
    title: "化学熱力学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "長谷川 正 松永 克志 / HASEGAWA Masashi MATSUNAGA Katsuyuki",
  },
  {
    id: "info-247",
    title: "固体物理演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher:
      "塚田 祐貴 伊藤 孝寛 山本 剛久 勝部 涼司 / TSUKADA Yuki ITO Takahiro YAMAMOTO Takahisa KATSUBE Ryoji",
  },
  {
    id: "info-248",
    title: "電気電子情報工学実験第2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "米澤 拓郎 / YONEZAWA Takuro",
  },
  {
    id: "info-249",
    title: "機械・航空宇宙工学実験第2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "丸山 央峰 / MARUYAMA Hisataka",
  },
  {
    id: "info-250",
    title: "構造材料実験I",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher:
      "三浦 泰人 加藤 準治 舘石 和雄 判治 剛 中村 光 清水 優 西口 浩司 藤島 実里 / MIURA Taito KATO Junji TATEISHI Kazuo HANJI Takeshi NAKAMURA Hikaru SHIMIZU Masaru NISHIGUCHI Koji FUJISHIMA Misato",
  },
  {
    id: "info-251",
    title: "建築生産システム",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "日比野 陽 野中 知秀 / HIBINO Yo NONAKA Tomohide",
  },
  {
    id: "info-252",
    title: "量子力学C",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "川口 由紀 / KAWAGUCHI Yuki",
  },
  {
    id: "info-253",
    title: "[G30]自動車工学概論",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Thu-5",
    teacher: "CUI Yi",
  },
  {
    id: "info-254",
    title: "物理化学4",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "町田 洋 勝部 涼司 / MACHIDA Hiroshi KATSUBE Ryoji",
  },
  {
    id: "info-255",
    title: "[G30]パワーエレクトロニクス",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "栗本 宗明 / KURIMOTO Muneaki",
  },
  {
    id: "info-256",
    title: "圧縮性流体力学及び演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "佐宗 章弘 杵淵 紀世志 / SASOH Akihiro KINEFUCHI Kiyoshi",
  },
  {
    id: "info-257",
    title: "極限強度学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "加藤 準治 / KATO Junji",
  },
  {
    id: "info-258",
    title: "計算力学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "加藤 準治 / KATO Junji",
  },
  {
    id: "info-259",
    title: "環境システム設計及び演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher:
      "鵜飼 真貴子 山崎 潤也 齋藤 輝幸 飯塚 悟 / UKAI Makiko YAMASAKI Junya SAITO Teruyuki IIZUKA Satoru",
  },
  {
    id: "info-260",
    title: "[G30]有機化学5",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "info-261",
    title: "理論計算材料学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "君塚 肇 / KIMIZUKA Hajime",
  },
  {
    id: "info-262",
    title: "[G30]都市と交通",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher:
      "飯塚 悟 堀田 典裕 加藤 博和 井料 美帆 / IIZUKA Satoru HOTTA Yoshihiro KATO Hirokazu IRYO Miho",
  },
  {
    id: "info-263",
    title: "量子材料化学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "尾上 順 桒原 真人 / ONOE Jun KUWAHARA Makoto",
  },
  {
    id: "info-264",
    title: "材料物理化学第3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "尾上 順 桒原 真人 / ONOE Jun KUWAHARA Makoto",
  },
  {
    id: "info-265",
    title: "物性物理学第4",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "中塚 理 平井 大悟郎 / NAKATSUKA Osamu HIRAI Daigorou",
  },
  {
    id: "info-266",
    title: "[G30]数値解析法",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "info-267",
    title: "メカトロニクス工学",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "鈴木 達也 奥田 裕之 / SUZUKI Tatsuya OKUDA Hiroyuki",
  },
  {
    id: "info-268",
    title: "技術英語2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-3",
    teacher: "LELEITO Emanuel Langat",
  },
  {
    id: "info-269",
    title: "物理工学セミナー",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-5",
    teacher: "畑野 敬史 平井 大悟郎 / HATANO Takafumi HIRAI Daigorou",
  },
  {
    id: "info-270",
    title: "[G30]設計製図2",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-5",
    teacher: "前田 英次郎 / MAEDA Eijiro",
  },
  {
    id: "info-271",
    title: "設計製図第3",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-5",
    teacher:
      "秦 誠一 前田 英次郎 原 進 星野 隆行 / HATA Seiichi MAEDA Eijiro HARA Susumu HOSHINO Takayuki",
  },
  {
    id: "info-272",
    title: "社会資本・空間計画学演習",
    department: "情報",
    section: "専門",
    semester: "秋1",
    cellKey: "Fri-5",
    teacher:
      "三輪 富生 張 馨 中村 英樹 加藤 博和 山本 俊行 / MIWA Tomio ZHANG Xin NAKAMURA Hideki KATO Hirokazu YAMAMOTO Toshiyuki",
  },
  {
    id: "info-273",
    title: "卒業研究A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 菊田 浩一 / KIKUTA Koichi",
  },
  {
    id: "info-274",
    title: "工場見学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 井口 弘章 鈴木 淳巨 野呂 篤史 / IGUCHI Hiroaki SUZUKI Atsuo NORO Atsushi",
  },
  {
    id: "info-275",
    title: "[G30]特別演習B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 菊田 浩一 / KIKUTA Koichi",
  },
  {
    id: "info-276",
    title: "[G30]卒業研究B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 菊田 浩一 / KIKUTA Koichi",
  },
  {
    id: "info-277",
    title: "卒業研究A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 齋藤 晃 森山 貴広 / SAITOH Koh MORIYAMA Takahiro",
  },
  {
    id: "info-278",
    title: "材料組織学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 非常勤講師 小山 敏幸 / KOYAMA Toshiyuki",
  },
  {
    id: "info-279",
    title: "化学工学概論",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 足立 吉隆 / ADACHI Yoshitaka",
  },
  {
    id: "info-280",
    title: "材料工学概論",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 足立 吉隆 / ADACHI Yoshitaka",
  },
  {
    id: "info-281",
    title: "卒業研究A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 足立 吉隆 / ADACHI Yoshitaka",
  },
  {
    id: "info-282",
    title: "生産マテリアル工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 未定(工)",
  },
  {
    id: "info-283",
    title: "[G30]卒業研究B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 五十嵐 信行 / IKARASHI Nobuyuki",
  },
  {
    id: "info-284",
    title: "卒業研究A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 福塚 友和 / FUKUTSUKA Tomokazu",
  },
  {
    id: "info-285",
    title: "[G30]自動車構造",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 栗本 宗明 / KURIMOTO Muneaki",
  },
  {
    id: "info-286",
    title: "[G30]工場見学A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 野老山 貴行 上野 藍 / TOKOROYAMA Takayuki UENO Ai",
  },
  {
    id: "info-287",
    title: "[G30]工場実習",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "info-288",
    title: "[G30]卒業研究B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 五十嵐 信行 / IKARASHI Nobuyuki",
  },
  {
    id: "info-289",
    title: "卒業研究A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 原 進 / HARA Susumu",
  },
  {
    id: "info-290",
    title: "原子力工学設計演習",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 山本 章夫 / YAMAMOTO Akio",
  },
  {
    id: "info-291",
    title: "原子力関係法規",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 山本 章夫 / YAMAMOTO Akio",
  },
  {
    id: "info-292",
    title: "原子炉実習",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 瓜谷 章 吉橋 幸子 / URITANI Akira YOSHIHASHI Sachiko",
  },
  {
    id: "info-293",
    title: "卒業研究A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 山田 智明 / YAMADA Tomoaki",
  },
  {
    id: "info-294",
    title: "エネルギー理工学輪講A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 山田 智明 / YAMADA Tomoaki",
  },
  {
    id: "info-295",
    title: "[遠隔]エネルギー理工学特別講義第1",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 富田 英生 / TOMITA Hideki",
  },
  {
    id: "info-296",
    title: "卒業研究A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 中村 光 中村 友昭 / NAKAMURA Hikaru NAKAMURA Tomoaki",
  },
  {
    id: "info-297",
    title: "卒業研究A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Spring) Other Other 齋藤 輝幸 / SAITO Teruyuki",
  },
  {
    id: "info-298",
    title: "[遠隔]土木地質学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 中野 正樹 福田 徹也 / NAKANO Masaki FUKUDA Tetsuya",
  },
  {
    id: "info-299",
    title: "防災安全",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Spring) Other Other 尾﨑 文宣 護 雅史 / OZAKI Fuminobu MORI Masafumi",
  },
  {
    id: "info-300",
    title: "卒業研究B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 菊田 浩一 / KIKUTA Koichi",
  },
  {
    id: "info-301",
    title: "[G30]卒業研究A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 菊田 浩一 / KIKUTA Koichi",
  },
  {
    id: "info-302",
    title: "卒業研究B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other 齋藤 晃 森山 貴広 / SAITOH Koh MORIYAMA Takahiro",
  },
  {
    id: "info-303",
    title: "環境システム工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 町田 洋 / MACHIDA Hiroshi",
  },
  {
    id: "info-304",
    title: "卒業研究B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 足立 吉隆 / ADACHI Yoshitaka",
  },
  {
    id: "info-305",
    title: "サステイナブル工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 町田 洋 / MACHIDA Hiroshi",
  },
  {
    id: "info-306",
    title: "[G30]卒業研究A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 水野 幸治 / MIZUNO Koji",
  },
  {
    id: "info-307",
    title: "卒業研究B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 福塚 友和 / FUKUTSUKA Tomokazu",
  },
  {
    id: "info-308",
    title: "[G30]工場見学B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 小川 浩平 / OGAWA Kohei",
  },
  {
    id: "info-309",
    title: "[G30]卒業研究A",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 水野 幸治 / MIZUNO Koji",
  },
  {
    id: "info-310",
    title: "熱流体機械システム",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other 長野 方星 成瀬 一郎 伊藤 靖仁 / NAGANO Hosei NARUSE Ichiro ITO Yasumasa",
  },
  {
    id: "info-311",
    title: "卒業研究B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 原 進 / HARA Susumu",
  },
  {
    id: "info-312",
    title: "放射線生物学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 尾上 順 / ONOE Jun",
  },
  {
    id: "info-313",
    title: "加速器工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 瓜谷 章 / URITANI Akira",
  },
  {
    id: "info-314",
    title: "卒業研究B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 山田 智明 / YAMADA Tomoaki",
  },
  {
    id: "info-315",
    title: "エネルギー理工学輪講B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 山田 智明 / YAMADA Tomoaki",
  },
  {
    id: "info-316",
    title: "エネルギー理工学特別講義第2",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 辻 義之 / TSUJI Yoshiyuki",
  },
  {
    id: "info-317",
    title: "エネルギー理工学特別講義第3",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 山田 智明 / YAMADA Tomoaki",
  },
  {
    id: "info-318",
    title: "卒業研究B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Intensive(Fall) Other Other 中村 光 中村 友昭 / NAKAMURA Hikaru NAKAMURA Tomoaki",
  },
  {
    id: "info-319",
    title: "卒業研究B",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher: "Intensive(Fall) Other Other 齋藤 輝幸 / SAITO Teruyuki",
  },
  {
    id: "info-320",
    title: "物理工学特別講義1a",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 齋藤 晃 森山 貴広 / SAITOH Koh MORIYAMA Takahiro",
  },
  {
    id: "info-321",
    title: "物理工学特別講義1b",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 齋藤 晃 森山 貴広 / SAITOH Koh MORIYAMA Takahiro",
  },
  {
    id: "info-322",
    title: "物理工学特別講義1c",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 齋藤 晃 森山 貴広 / SAITOH Koh MORIYAMA Takahiro",
  },
  {
    id: "info-323",
    title: "物理工学特別講義1d",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 齋藤 晃 森山 貴広 / SAITOH Koh MORIYAMA Takahiro",
  },
  {
    id: "info-324",
    title: "工場見学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 畑野 敬史 平井 大悟郎 / HATANO Takafumi HIRAI Daigorou",
  },
  {
    id: "info-325",
    title: "工場見学",
    department: "情報",
    section: "専門",
    semester: "春1",
    teacher:
      "Full-year course Intensive(Sp-Fa) Other Other 杵淵 紀世志 / KINEFUCHI Kiyoshi",
  },
  {
    id: "info-326",
    title: "電子計測工学",
    department: "情報",
    section: "専門",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "岸田 英夫 / KISHIDA Hideo",
  },
];
