import { Course } from "../courses";
export const TECH_B_COURSES: Course[] = [
  {
    id: "natu-1",
    title: "有機化学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-1",
    teacher:
      "ウヤヌク ムハメット 福井 識人 大村 修平 / UYANIK Muhammet FUKUI Norihito OHMURA Shuhei",
  },
  {
    id: "natu-2",
    title: "物理工学演習2a",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "寺田 智樹 武藤 俊介 / TERADA Tomoki MUTO Shunsuke",
  },
  {
    id: "natu-3",
    title: "物理工学演習2b",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "寺田 智樹 竹延 大志 洗平 昌晃 / TERADA Tomoki TAKENOBU Taishi ARAIDAI Masaaki",
  },
  {
    id: "natu-4",
    title: "熱力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "長野 方星 山本 和弘 上野 藍 / NAGANO Hosei YAMAMOTO Kazuhiro UENO Ai",
  },
  {
    id: "natu-5",
    title: "熱力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "山本 和弘 上野 藍 長野 方星 / YAMAMOTO Kazuhiro UENO Ai NAGANO Hosei",
  },
  {
    id: "natu-6",
    title: "エネルギー理工学セミナーA",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "桒原 真人 / KUWAHARA Makoto",
  },
  {
    id: "natu-7",
    title: "流れの力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "趙 容桓 水谷 法美 田代 喬 周 月霞 / CHO Yonghwan MIZUTANI Norimi TASHIRO Takashi ZHOU Yuexia",
  },
  {
    id: "natu-8",
    title: "流れの力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "趙 容桓 水谷 法美 田代 喬 周 月霞 / CHO Yonghwan MIZUTANI Norimi TASHIRO Takashi ZHOU Yuexia",
  },
  {
    id: "natu-9",
    title: "[G30]量子化学1",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-1",
    teacher: "PHUNG Quan manh",
  },
  {
    id: "natu-10",
    title: "[G30]流体力学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "natu-11",
    title: "数学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "髙嶋 圭史 伊藤 孝至 / TAKASHIMA Yoshifumi ITOH Takashi",
  },
  {
    id: "natu-12",
    title: "数学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "山本 章夫 / YAMAMOTO Akio",
  },
  {
    id: "natu-13",
    title: "物理化学3及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-2",
    teacher:
      "大槻 主税 鈴木 一正 鳥本 司 松川 祐子 / OHTSUKI Chikara SUZUKI Kazumasa TORIMOTO Tsukasa MATSUKAWA Yuko",
  },
  {
    id: "natu-14",
    title: "[G30]生化学2",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "natu-15",
    title: "[G30]量子化学3",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-2",
    teacher: "藤本 和宏 / FUJIMOTO Kazuhiro",
  },
  {
    id: "natu-16",
    title: "生命化学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-3",
    teacher:
      "鈴木 淳巨 堀 克敏 中谷 肇 / SUZUKI Atsuo HORI Katsutoshi NAKATANI Hajime",
  },
  {
    id: "natu-17",
    title: "電子回路工学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "加藤 剛志 堤 隆嘉 / KATO Takeshi TSUTSUMI Takayoshi",
  },
  {
    id: "natu-18",
    title: "電子回路工学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-3",
    teacher: "大野 哲靖 田中 宏彦 / OHNO Noriyasu TANAKA Hirohiko",
  },
  {
    id: "natu-19",
    title: "材料力学第1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "荒井 政大 橋本 樹慶 / ARAI Masahiro HASHIMOTO Mikiyasu",
  },
  {
    id: "natu-20",
    title: "材料力学第1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "徳 悠葵 / TOKU Yuhki",
  },
  {
    id: "natu-21",
    title: "空間設計論",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "李 燕 / LI Yan",
  },
  {
    id: "natu-22",
    title: "空間設計論",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-3",
    teacher: "李 燕 / LI Yan",
  },
  {
    id: "natu-23",
    title: "数学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "生田 博志 芳松 克則 / IKUTA Hiroshi YOSHIMATSU Katsunori",
  },
  {
    id: "natu-24",
    title: "マテリアル量子工学",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-4",
    teacher: "田川 美穂 勝部 涼司 / TAGAWA Miho KATSUBE Ryoji",
  },
  {
    id: "natu-25",
    title: "電気回路論及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "加藤 丈佳 今岡 淳 / KATO Takeyoshi IMAOKA Jun",
  },
  {
    id: "natu-26",
    title: "電気回路論及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "田中 雅光 李 峰 / TANAKA Masamitsu LI Feng",
  },
  {
    id: "natu-27",
    title: "流体力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Mon-5",
    teacher: "辻 義之 / TSUJI Yoshiyuki",
  },
  {
    id: "natu-28",
    title: "[G30]無機化学1",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "natu-29",
    title: "解析力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "谷口 晴香 / TANIGUCHI Haruka",
  },
  {
    id: "natu-30",
    title: "マテリアル固体物理1",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "伊藤 孝寛 黒川 康良 / ITO Takahiro KUROKAWA Yasuyoshi",
  },
  {
    id: "natu-31",
    title: "情報理論",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "武田 一哉 / TAKEDA Kazuya",
  },
  {
    id: "natu-32",
    title: "情報理論",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "長谷川 浩 / HASEGAWA Hiroshi",
  },
  {
    id: "natu-33",
    title: "[遠隔][G30]金属材料とセラミックス",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "小橋 眞 王 謙 / KOBASHI Makoto WANG Qian",
  },
  {
    id: "natu-34",
    title: "振動工学第2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "井上 剛志 部矢 明 / INOUE Tsuyoshi HEYA Akira",
  },
  {
    id: "natu-35",
    title: "振動工学第2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "井上 剛志 部矢 明 / INOUE Tsuyoshi HEYA Akira",
  },
  {
    id: "natu-36",
    title: "機械学習及びデータ分析演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "竹内 一郎 竹野 思温 / TAKEUCHI Ichiro TAKENO Shion",
  },
  {
    id: "natu-37",
    title: "原子核物理概論",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-1",
    teacher: "柴田 理尋 / SHIBATA Michihiro",
  },
  {
    id: "natu-38",
    title: "建築構造力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "飛田 潤 / TOBITA Jun",
  },
  {
    id: "natu-39",
    title: "数学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "吉田 隆 井田 大貴 / YOSHIDA Yutaka IDA Hiroki",
  },
  {
    id: "natu-40",
    title: "数学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "舟洞 佑記 / FUNABORA Yuki",
  },
  {
    id: "natu-41",
    title: "化学工学基礎",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "本多 裕之 清水 一憲 / HONDA Hiroyuki SHIMIZU Kazunori",
  },
  {
    id: "natu-42",
    title: "生命化学4及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "清中 茂樹 / KIYONAKA Shigeki",
  },
  {
    id: "natu-43",
    title: "化学工学基礎1",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "本多 裕之 清水 一憲 / HONDA Hiroyuki SHIMIZU Kazunori",
  },
  {
    id: "natu-44",
    title: "化学プロセス工学",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "小島 義弘 / KOJIMA Yoshihiro",
  },
  {
    id: "natu-45",
    title: "化学工学概論",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "小島 義弘 / KOJIMA Yoshihiro",
  },
  {
    id: "natu-46",
    title: "[G30]固体力学",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "CUI Yi",
  },
  {
    id: "natu-47",
    title: "プログラミング法および数値計算演習B",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "吉橋 幸子 / YOSHIHASHI Sachiko",
  },
  {
    id: "natu-48",
    title: "社会資本計画学",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "三輪 富生 林 希一郎 / MIWA Tomio HAYASHI Kiichiro",
  },
  {
    id: "natu-49",
    title: "社会資本計画学",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "三輪 富生 林 希一郎 / MIWA Tomio HAYASHI Kiichiro",
  },
  {
    id: "natu-50",
    title: "[G30]電磁気学",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "natu-51",
    title: "数学1及び演習B",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "道木 慎二 / DOKI Shinji",
  },
  {
    id: "natu-52",
    title: "数学1及び演習B",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-2",
    teacher: "塩川 和夫 片倉 誠士 / SHIOKAWA Kazuo KATAKURA Seiji",
  },
  {
    id: "natu-53",
    title: "化学生命工学実験1",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "熊谷 純 林 剛介 山本 瑛祐 長谷川 丈二 / KUMAGAI Jun HAYASHI Gosuke YAMAMOTO Eisuke HASEGAWA Joji",
  },
  {
    id: "natu-54",
    title: "物理化学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-3",
    teacher:
      "酒田 陽子 浅沼 浩之 村山 恵司 / SAKATA Yoko ASANUMA Hiroyuki MURAYAMA Keiji",
  },
  {
    id: "natu-55",
    title: "[G30]化学生命工学実験1",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "熊谷 純 林 剛介 山本 瑛祐 長谷川 丈二 / KUMAGAI Jun HAYASHI Gosuke YAMAMOTO Eisuke HASEGAWA Joji",
  },
  {
    id: "natu-56",
    title: "物理工学実験第1",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "畑野 敬史 中村 優斗 石田 高史 浦田 隆広 佐々木 拓也 矢野 力三 柴山 茂久 坂下 満男 井上 陽登 草ノ瀬 優香 石田 崇人 林 兼輔 齊藤 元貴 / HATANO Takafumi NAKAMURA Yuto ISHIDA Takafumi URATA Takahiro SASAKI Takuya YANO Rikizo SHIBAYAMA Shigehisa SAKASHITA Mitsuo INOUE Takato KUSANOSE Yuka ISHIDA Takato HAYASHI Kensuke SAITO Genki",
  },
  {
    id: "natu-57",
    title: "物理化学2",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "松宮 弘明 / MATSUMIYA Hiroaki",
  },
  {
    id: "natu-58",
    title: "[G30]振動学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "工学部教務",
  },
  {
    id: "natu-59",
    title: "[G30]振動学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "CUI Yi",
  },
  {
    id: "natu-60",
    title: "流体力学基礎及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "山口 浩樹 日出間 るり / YAMAGUCHI Hiroki HIDEMA Ruri",
  },
  {
    id: "natu-61",
    title: "流体力学基礎及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-4",
    teacher: "山口 浩樹 日出間 るり / YAMAGUCHI Hiroki HIDEMA Ruri",
  },
  {
    id: "natu-62",
    title: "熱力学演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-3",
    teacher: "西川原 理仁 / NISHIKAWARA Masahito",
  },
  {
    id: "natu-63",
    title: "空間設計工学及び演習第1",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "恒川 和久 西澤 泰彦 小松 尚 李 燕 項 一朗 三森 弘 / TSUNEKAWA Kazuhisa NISHIZAWA Yasuhiko KOMATSU Hisashi LI Yan XIANG Yilang MITSUMORI Hiroshi",
  },
  {
    id: "natu-64",
    title: "コンピュータ・リテラシー及びプログラミング",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "旭 良司 足立 吉隆 松岡 辰郎 塚田 祐貴 沓掛 健太朗 / ASAHI Ryoji ADACHI Yoshitaka MATSUOKA Tatsuro TSUKADA Yuki KUTSUKAKE Kentaro",
  },
  {
    id: "natu-65",
    title: "応用データサイエンス",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-4",
    teacher:
      "旭 良司 足立 吉隆 松岡 辰郎 塚田 祐貴 沓掛 健太朗 / ASAHI Ryoji ADACHI Yoshitaka MATSUOKA Tatsuro TSUKADA Yuki KUTSUKAKE Kentaro",
  },
  {
    id: "natu-66",
    title: "無機化学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-1",
    teacher:
      "井口 弘章 長田 実 日下 心平 山本 瑛祐 松田 亮太郎 / IGUCHI Hiroaki OSADA Minoru KUSAKA Shinpei YAMAMOTO Eisuke MATSUDA Ryotaro",
  },
  {
    id: "natu-67",
    title: "熱力学",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "武藤 俊介 / MUTO Shunsuke",
  },
  {
    id: "natu-68",
    title: "プログラミング及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "小川 浩平 / OGAWA Kohei",
  },
  {
    id: "natu-69",
    title: "プログラミング及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "米澤 拓郎 / YONEZAWA Takuro",
  },
  {
    id: "natu-70",
    title: "応用力学演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-1",
    teacher: "柴田 理尋 / SHIBATA Michihiro",
  },
  {
    id: "natu-71",
    title: "数学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "福澤 健二 東 直輝 / FUKUZAWA Kenji AZUMA Naoki",
  },
  {
    id: "natu-72",
    title: "数学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "田地 宏一 竹野 思温 / TAJI Kouichi TAKENO Shion",
  },
  {
    id: "natu-73",
    title: "分析化学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-2",
    teacher:
      "村上 裕 林 剛介 菊田 浩一 熊谷 純 / MURAKAMI Hiroshi HAYASHI Gosuke KIKUTA Koichi KUMAGAI Jun",
  },
  {
    id: "natu-74",
    title: "基礎分析化学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-2",
    teacher:
      "村上 裕 林 剛介 菊田 浩一 熊谷 純 / MURAKAMI Hiroshi HAYASHI Gosuke KIKUTA Koichi KUMAGAI Jun",
  },
  {
    id: "natu-75",
    title: "[G30]有機化学2",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "natu-76",
    title: "[G30]無機化学3",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "natu-77",
    title: "生物科学",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "寺田 智樹 / TERADA Tomoki",
  },
  {
    id: "natu-78",
    title: "量子力学B",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "田仲 由喜夫 矢田 圭司 / TANAKA Yukio YADA Keiji",
  },
  {
    id: "natu-79",
    title: "機器分析概論",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-2",
    teacher:
      "松宮 弘明 山内 悠輔 伊藤 孝寛 山本 剛久 田川 美穂 布施 新一郎 / MATSUMIYA Hiroaki YAMAUCHI Yusuke ITO Takahiro YAMAMOTO Takahisa TAGAWA Miho FUSE Shinichiro",
  },
  {
    id: "natu-80",
    title: "[G30]電子回路工学",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-2",
    teacher: "大野 哲靖 栗本 宗明 / OHNO Noriyasu KURIMOTO Muneaki",
  },
  {
    id: "natu-81",
    title: "学生実験1",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "澤田 康之 安田 啓司 / SAWADA Yasuyuki YASUDA Keiji",
  },
  {
    id: "natu-82",
    title: "マテリアル工学実験基礎",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "澤田 康之 安田 啓司 / SAWADA Yasuyuki YASUDA Keiji",
  },
  {
    id: "natu-83",
    title: "電気磁気学基礎演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-3",
    teacher: "長尾 全寛 井上 健一 / NAGAO Masahiro INOUE Kenichi",
  },
  {
    id: "natu-84",
    title: "電気磁気学基礎演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-3",
    teacher: "西澤 典彦 兒玉 直人 / NISHIZAWA Norihiko KODAMA Naoto",
  },
  {
    id: "natu-85",
    title: "エネルギー理工学実験第2A",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "辻 義之 山﨑 淳 / TSUJI Yoshiyuki YAMAZAKI Atsushi",
  },
  {
    id: "natu-86",
    title: "数学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-4",
    teacher: "熊谷 純 野呂 篤史 / KUMAGAI Jun NORO Atsushi",
  },
  {
    id: "natu-87",
    title: "解析力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Wed-5",
    teacher: "野田 利弘 中井 健太郎 / NODA Toshihiro NAKAI Kentaro",
  },
  {
    id: "natu-88",
    title: "加工学第1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "社本 英二 LEE Kyungki / SHAMOTO Eiji LEE Kyungki",
  },
  {
    id: "natu-89",
    title: "加工学第1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "梅原 徳次 張 鋭璽 / UMEHARA Noritsugu ZHANG Ruixi",
  },
  {
    id: "natu-90",
    title: "数学3及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "中谷 真人 / NAKAYA Masato",
  },
  {
    id: "natu-91",
    title: "都市と文明の歴史",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-1",
    teacher: "恒川 和久 中村 晋一郎 / TSUNEKAWA Kazuhisa NAKAMURA Shinichiro",
  },
  {
    id: "natu-92",
    title: "有機化学4及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-2",
    teacher:
      "大井 貴史 安井 猛 渡邉 大展 / OOI Takashi YASUI Takeshi WATANABE Hironobu",
  },
  {
    id: "natu-93",
    title: "[G30]物理化学2",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-2",
    teacher: "PHUNG Quan manh",
  },
  {
    id: "natu-94",
    title: "化学生命工学実験2",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-4",
    teacher:
      "内山 峰人 堂浦 智裕 村山 恵司 荒巻 吉孝 安井 猛 福井 識人 鈴木 淳巨 樫田 啓 ウヤヌク ムハメット 中谷 肇 大村 修平 渡邉 大展 NAKASHIMA Tsubasa 秋山 裕和 八塚 研治 武藤 慶 井改 知幸 加藤 竜司 清水 一憲 髙野 秀明 / UCHIYAMA Mineto DOURA Tomohiro MURAYAMA Keiji ARAMAKI Yoshitaka YASUI Takeshi FUKUI Norihito SUZUKI Atsuo KASHIDA Hiromu UYANIK Muhammet NAKATANI Hajime OHMURA Shuhei WATANABE Hironobu NAKASHIMA Tsubasa AKIYAMA Hirokazu YATSUZUKA Kenji MUTO Kei IKAI Tomoyuki KATO Ryuji SHIMIZU Kazunori TAKANO Hideaki",
  },
  {
    id: "natu-95",
    title: "[G30]化学生命工学実験2",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-4",
    teacher:
      "内山 峰人 堂浦 智裕 村山 恵司 荒巻 吉孝 安井 猛 福井 識人 鈴木 淳巨 樫田 啓 ウヤヌク ムハメット 中谷 肇 大村 修平 渡邉 大展 NAKASHIMA Tsubasa 秋山 裕和 八塚 研治 武藤 慶 井改 知幸 加藤 竜司 清水 一憲 髙野 秀明 / UCHIYAMA Mineto DOURA Tomohiro MURAYAMA Keiji ARAMAKI Yoshitaka YASUI Takeshi FUKUI Norihito SUZUKI Atsuo KASHIDA Hiromu UYANIK Muhammet NAKATANI Hajime OHMURA Shuhei WATANABE Hironobu NAKASHIMA Tsubasa AKIYAMA Hirokazu YATSUZUKA Kenji MUTO Kei IKAI Tomoyuki KATO Ryuji SHIMIZU Kazunori TAKANO Hideaki",
  },
  {
    id: "natu-96",
    title: "構造解析の基礎及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-4",
    teacher: "舘石 和雄 清水 優 / TATEISHI Kazuo SHIMIZU Masaru",
  },
  {
    id: "natu-97",
    title: "[G30]物理学基礎演習1b",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Thu-5",
    teacher: "梅畑 豪紀 / UMEHATA Hideki",
  },
  {
    id: "natu-98",
    title: "物理化学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "薩摩 篤 織田 晃 / SATSUMA Atsushi ODA Akira",
  },
  {
    id: "natu-99",
    title: "[G30]地球環境科学",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "HUMBLET Marc Andre",
  },
  {
    id: "natu-100",
    title: "離散数学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "岩田 哲 都竹 千尋 / IWATA Tetsu TSUTAKE Chihiro",
  },
  {
    id: "natu-101",
    title: "離散数学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "水谷 圭一 久野 拓真 / MIZUTANI Keiichi KUNO Takuma",
  },
  {
    id: "natu-102",
    title: "制御工学第2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "椿野 大輔 原 進 / TSUBAKINO Daisuke HARA Susumu",
  },
  {
    id: "natu-103",
    title: "制御工学第2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-2",
    teacher: "椿野 大輔 原 進 / TSUBAKINO Daisuke HARA Susumu",
  },
  {
    id: "natu-104",
    title: "エネルギー理工学序論",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "吉田 朋子 西川原 理仁 / YOSHIDA Tomoko NISHIKAWARA Masahito",
  },
  {
    id: "natu-105",
    title: "図学",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-1",
    teacher: "西澤 泰彦 / NISHIZAWA Yasuhiko",
  },
  {
    id: "natu-106",
    title: "構造物と技術の発展",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-2",
    teacher:
      "中野 正樹 飛田 潤 五十嵐 豪 中村 光 尾﨑 文宣 水谷 法美 / NAKANO Masaki TOBITA Jun IGARASHI Go NAKAMURA Hikaru OZAKI Fuminobu MIZUTANI Norimi",
  },
  {
    id: "natu-107",
    title: "物理工学序論",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "飯浜 賢志 小山 剛史 / IIHAMA Satoshi KOYAMA Takeshi",
  },
  {
    id: "natu-108",
    title: "情報処理序説",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-3",
    teacher: "山本 俊行 / YAMAMOTO Toshiyuki",
  },
  {
    id: "natu-109",
    title: "電気電子情報工学序論",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-4",
    teacher: "福塚 友和 / FUKUTSUKA Tomokazu",
  },
  {
    id: "natu-110",
    title: "[G30]物理学基礎演習2a",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "natu-111",
    title: "[G30]物理学基礎演習2",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Fri-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "natu-112",
    title: "[G30]生化学1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "小嶋 誠司 / KOJIMA Seiji",
  },
  {
    id: "natu-113",
    title: "マテリアル固体物理2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "黒川 康良 宇佐美 徳隆 / KUROKAWA Yasuyoshi USAMI Noritaka",
  },
  {
    id: "natu-114",
    title: "[G30]材料力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "松本 敏郎 / MATSUMOTO Toshirou",
  },
  {
    id: "natu-115",
    title: "機構学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "長谷川 泰久 / HASEGAWA Yasuhisa",
  },
  {
    id: "natu-116",
    title: "量子力学B",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "柚原 淳司 / YUHARA Junji",
  },
  {
    id: "natu-117",
    title: "土質力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher:
      "野田 利弘 豊田 智大 中井 健太郎 酒井 崇之 / NODA Toshihiro TOYODA Tomohiro NAKAI Kentaro SAKAI Takayuki",
  },
  {
    id: "natu-118",
    title: "土質力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher:
      "野田 利弘 豊田 智大 中井 健太郎 酒井 崇之 / NODA Toshihiro TOYODA Tomohiro NAKAI Kentaro SAKAI Takayuki",
  },
  {
    id: "natu-119",
    title: "[G30]量子化学2",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-1",
    teacher: "PHUNG Quan manh",
  },
  {
    id: "natu-120",
    title: "[G30]無機化学2",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "natu-121",
    title: "量子力学演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-2",
    teacher: "柚原 淳司 / YUHARA Junji",
  },
  {
    id: "natu-122",
    title: "化学工学基礎2",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "本多 裕之 清水 一憲 / HONDA Hiroyuki SHIMIZU Kazunori",
  },
  {
    id: "natu-123",
    title: "[G30]細胞学2",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "野間 健太郎 / NOMA Kentaro",
  },
  {
    id: "natu-124",
    title: "流動及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "井藤 彰 大戸 達彦 / ITO Akira OHTO Tatsuhiko",
  },
  {
    id: "natu-125",
    title: "流動",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "井藤 彰 大戸 達彦 / ITO Akira OHTO Tatsuhiko",
  },
  {
    id: "natu-126",
    title: "[G30]機構学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "山田 陽滋 伊藤 靖仁 / YAMADA Yoji ITO Yasumasa",
  },
  {
    id: "natu-127",
    title: "[G30]制御工学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "CUI Yi",
  },
  {
    id: "natu-128",
    title: "伝熱工学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "成瀬 一郎 / NARUSE Ichiro",
  },
  {
    id: "natu-129",
    title: "伝熱工学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "長野 方星 上野 藍 / NAGANO Hosei UENO Ai",
  },
  {
    id: "natu-130",
    title: "エネルギー理工学セミナーB",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-3",
    teacher: "桒原 真人 / KUWAHARA Makoto",
  },
  {
    id: "natu-131",
    title: "統計力学A",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "増渕 雄一 / MASUBUCHI Yuichi",
  },
  {
    id: "natu-132",
    title: "物理化学3及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher:
      "市野 良一 松尾 豊 齋藤 永宏 稗田 純子 / ICHINO Ryoichi MATSUO Yutaka SAITO Nagahiro HIEDA Junko",
  },
  {
    id: "natu-133",
    title: "[G30]熱力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "natu-134",
    title: "移動現象論及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher: "杉山 貴彦 / SUGIYAMA Takahiko",
  },
  {
    id: "natu-135",
    title: "[G30]統計物理学1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-4",
    teacher: "伊藤 靖仁 / ITO Yasumasa",
  },
  {
    id: "natu-136",
    title: "[G30]分析化学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "natu-137",
    title: "[G30]有機化学3",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "natu-138",
    title: "設計製図",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "原田 寛 伊藤 孝至 / HARADA Hiroshi ITOH Takashi",
  },
  {
    id: "natu-139",
    title: "機械工学基礎及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-1",
    teacher: "原田 寛 伊藤 孝至 / HARADA Hiroshi ITOH Takashi",
  },
  {
    id: "natu-140",
    title: "ディジタル回路及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "久志本 真希 浦野 健太 / KUSHIMOTO Maki URANO Kenta",
  },
  {
    id: "natu-141",
    title: "ディジタル回路及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "山里 敬也 / YAMAZATO Takaya",
  },
  {
    id: "natu-142",
    title: "数学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "竹岡 敬和 沢邊 恭一 / TAKEOKA Yukikazu SAWABE Kyoichi",
  },
  {
    id: "natu-143",
    title: "数学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "張 紹良 / ZHANG Shao-liang",
  },
  {
    id: "natu-144",
    title: "数学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "岡本 敦 吉橋 幸子 / OKAMOTO Atsushi YOSHIHASHI Sachiko",
  },
  {
    id: "natu-145",
    title: "[G30]無機材料化学1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "SAMJESKE Gabor Arwed",
  },
  {
    id: "natu-146",
    title: "応用数学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher:
      "髙嶋 圭史 原田 俊太 旭 良司 / TAKASHIMA Yoshifumi HARADA Shunta ASAHI Ryoji",
  },
  {
    id: "natu-147",
    title: "振動工学第1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "部矢 明 井上 剛志 / HEYA Akira INOUE Tsuyoshi",
  },
  {
    id: "natu-148",
    title: "振動工学第1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "井上 剛志 部矢 明 / INOUE Tsuyoshi HEYA Akira",
  },
  {
    id: "natu-149",
    title: "空間計画論",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "加藤 博和 / KATO Hirokazu",
  },
  {
    id: "natu-150",
    title: "[G30]計測工学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-2",
    teacher: "栗本 宗明 / KURIMOTO Muneaki",
  },
  {
    id: "natu-151",
    title: "物理化学5及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "鳥本 司 秋吉 一孝 / TORIMOTO Tsukasa AKIYOSHI Kazutaka",
  },
  {
    id: "natu-152",
    title: "[G30]電気回路工学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "栗本 宗明 / KURIMOTO Muneaki",
  },
  {
    id: "natu-153",
    title: "電気回路工学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "鈴木 達也 本田 康平 / SUZUKI Tatsuya HONDA Kohei",
  },
  {
    id: "natu-154",
    title: "電気回路工学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "鈴木 達也 岡 智絵美 / SUZUKI Tatsuya OKA Chiemi",
  },
  {
    id: "natu-155",
    title: "エネルギー理工学設計及び製作",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "辻 義之 / TSUJI Yoshiyuki",
  },
  {
    id: "natu-156",
    title: "環境土木工学実習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher:
      "田代 むつみ 中村 晋一郎 清水 優 張 馨 豊田 智大 酒井 崇之 西口 浩司 周 月霞 長谷川 正利 藤島 実里 / TASHIRO Mutsumi NAKAMURA Shinichiro SHIMIZU Masaru ZHANG Xin TOYODA Tomohiro SAKAI Takayuki NISHIGUCHI Koji ZHOU Yuexia HASEGAWA Masatoshi FUJISHIMA Misato",
  },
  {
    id: "natu-157",
    title: "鉄骨構造",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-3",
    teacher: "尾﨑 文宣 / OZAKI Fuminobu",
  },
  {
    id: "natu-158",
    title: "[G30]数理物理学演習1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-4",
    teacher: "WOJDYLO John Andrew 井黒 就平 / WOJDYLO John Andrew IGURO Shuhei",
  },
  {
    id: "natu-159",
    title: "物理工学演習4a",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-5",
    teacher:
      "寺田 智樹 飯浜 賢志 千見寺 浄慈 / TERADA Tomoki IIHAMA Satoshi CHIKENJI George",
  },
  {
    id: "natu-160",
    title: "物理工学演習4b",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-5",
    teacher:
      "寺田 智樹 齋藤 晃 石田 崇人 / TERADA Tomoki SAITOH Koh ISHIDA Takato",
  },
  {
    id: "natu-161",
    title: "[G30]数学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-5",
    teacher: "WOJDYLO John Andrew 井黒 就平 / WOJDYLO John Andrew IGURO Shuhei",
  },
  {
    id: "natu-162",
    title: "[G30]数理物理学1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-5",
    teacher: "WOJDYLO John Andrew",
  },
  {
    id: "natu-163",
    title: "材料力学第2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-5",
    teacher: "奥村 大 / OKUMURA Dai",
  },
  {
    id: "natu-164",
    title: "材料力学第2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Tue-5",
    teacher: "松本 健郎 / MATSUMOTO Takeo",
  },
  {
    id: "natu-165",
    title: "有機化学3及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher:
      "忍久保 洋 NAKASHIMA Tsubasa 髙野 秀明 / SHINOKUBO Hiroshi NAKASHIMA Tsubasa TAKANO Hideaki",
  },
  {
    id: "natu-166",
    title: "原子物理学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "中塚 理 / NAKATSUKA Osamu",
  },
  {
    id: "natu-167",
    title: "物理化学1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher:
      "朝倉 裕介 山内 悠輔 小山 敏幸 / ASAKURA Yusuke YAMAUCHI Yusuke KOYAMA Toshiyuki",
  },
  {
    id: "natu-168",
    title: "[G30]自動車化学システム1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "永岡 勝俊 松尾 豊 / NAGAOKA Katsutoshi MATSUO Yutaka",
  },
  {
    id: "natu-169",
    title: "計算機ソフトウエア第2",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "荒井 政大 / ARAI Masahiro",
  },
  {
    id: "natu-170",
    title: "計算機ソフトウエア第2",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "奥田 裕之 / OKUDA Hiroyuki",
  },
  {
    id: "natu-171",
    title: "データ統計解析A",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "岡本 敦 / OKAMOTO Atsushi",
  },
  {
    id: "natu-172",
    title: "統計力学演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "山田 智明 / YAMADA Tomoaki",
  },
  {
    id: "natu-173",
    title: "形と力",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-1",
    teacher: "加藤 準治 長江 拓也 / KATO Junji NAGAE Takuya",
  },
  {
    id: "natu-174",
    title: "数学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "藤井 慶輔 狩野 絵美 / FUJII Keisuke KANO Emi",
  },
  {
    id: "natu-175",
    title: "無機化学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "小林 亮 日下 心平 山本 瑛祐 中西 和樹 / KOBAYASHI Makoto KUSAKA Shinpei YAMAMOTO Eisuke NAKANISHI Kazuki",
  },
  {
    id: "natu-176",
    title: "高分子基礎化学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "上垣外 正己 野呂 篤史 井改 知幸 / KAMIGAITO Masami NORO Atsushi IKAI Tomoyuki",
  },
  {
    id: "natu-177",
    title: "分析化学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "村上 裕 林 剛介 菊田 浩一 熊谷 純 / MURAKAMI Hiroshi HAYASHI Gosuke KIKUTA Koichi KUMAGAI Jun",
  },
  {
    id: "natu-178",
    title: "量子力学A",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "柏谷 聡 / KASHIWAYA Satoshi",
  },
  {
    id: "natu-179",
    title: "結晶物理学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "山本 剛久 / YAMAMOTO Takahisa",
  },
  {
    id: "natu-180",
    title: "先端プロセス工学1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "髙田 尚記 足立 吉隆 水口 将輝 / TAKATA Naoki ADACHI Yoshitaka MIZUGUCHI Masaki",
  },
  {
    id: "natu-181",
    title: "材料科学第1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "奥村 大 / OKUMURA Dai",
  },
  {
    id: "natu-182",
    title: "材料科学第1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "奥村 大 / OKUMURA Dai",
  },
  {
    id: "natu-183",
    title: "物理化学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "小川 智史 / OGAWA Satoshi",
  },
  {
    id: "natu-184",
    title: "統計力学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "山田 智明 / YAMADA Tomoaki",
  },
  {
    id: "natu-185",
    title: "人間活動と環境",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher:
      "谷川 寛樹 中村 晋一郎 齋藤 輝幸 飯塚 悟 / TANIKAWA Hiroki NAKAMURA Shinichiro SAITO Teruyuki IIZUKA Satoru",
  },
  {
    id: "natu-186",
    title: "数学1及び演習A",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "道木 慎二 / DOKI Shinji",
  },
  {
    id: "natu-187",
    title: "数学1及び演習A",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-2",
    teacher: "塩川 和夫 片倉 誠士 / SHIOKAWA Kazuo KATAKURA Seiji",
  },
  {
    id: "natu-188",
    title: "線形回路論及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "本田 善央 大塚 雄一 / HONDA Yoshio OTSUKA Yuichi",
  },
  {
    id: "natu-189",
    title: "線形回路論及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "牧原 克典 / MAKIHARA Katsunori",
  },
  {
    id: "natu-190",
    title: "量子力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "田中 雅光 内山 晴貴 / TANAKA Masamitsu UCHIYAMA Haruki",
  },
  {
    id: "natu-191",
    title: "量子力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "大野 雄高 北島 将太朗 / OHNO Yutaka KITAJIMA Shotaro",
  },
  {
    id: "natu-192",
    title: "エネルギー理工学概論",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "吉橋 幸子 岡本 敦 / YOSHIHASHI Sachiko OKAMOTO Atsushi",
  },
  {
    id: "natu-193",
    title: "エネルギー理工学実験第2B",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-4",
    teacher: "辻 義之 小川 智史 / TSUJI Yoshiyuki OGAWA Satoshi",
  },
  {
    id: "natu-194",
    title: "確率と統計",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Wed-3",
    teacher: "齋藤 輝幸 白木 裕斗 / SAITO Teruyuki SHIRAKI Hiroto",
  },
  {
    id: "natu-195",
    title: "生命化学3及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "清水 一憲 本多 裕之 / SHIMIZU Kazunori HONDA Hiroyuki",
  },
  {
    id: "natu-196",
    title: "電磁気学III",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "齋藤 晃 / SAITOH Koh",
  },
  {
    id: "natu-197",
    title: "熱移動と拡散",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "伊藤 孝至 町田 洋 / ITOH Takashi MACHIDA Hiroshi",
  },
  {
    id: "natu-198",
    title: "確率論・数値解析及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "藤井 俊彰 / FUJII Toshiaki",
  },
  {
    id: "natu-199",
    title: "確率論・数値解析及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "西谷 望 飯島 陽久 / NISHITANI Nozomu IIJIMA Haruhisa",
  },
  {
    id: "natu-200",
    title: "粘性流体力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "野々村 拓 / NONOMURA Taku",
  },
  {
    id: "natu-201",
    title: "粘性流体力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "工学部教務 野々村 拓 / NONOMURA Taku",
  },
  {
    id: "natu-202",
    title: "応用電磁気学演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "藤田 隆明 / FUJITA Takaaki",
  },
  {
    id: "natu-203",
    title: "構造力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "判治 剛 / HANJI Takeshi",
  },
  {
    id: "natu-204",
    title: "応用構造力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "飛田 潤 / TOBITA Jun",
  },
  {
    id: "natu-205",
    title: "[G30]物理化学1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-1",
    teacher: "PHUNG Quan manh",
  },
  {
    id: "natu-206",
    title: "物理化学4及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher:
      "鳥本 司 浅沼 浩之 秋吉 一孝 / TORIMOTO Tsukasa ASANUMA Hiroyuki AKIYOSHI Kazutaka",
  },
  {
    id: "natu-207",
    title: "先端マテリアル工学概論1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher:
      "矢島 健 沓掛 健太朗 松宮 弘明 / YAJIMA Takeshi KUTSUKAKE Kentaro MATSUMIYA Hiroaki",
  },
  {
    id: "natu-208",
    title: "電気電子工学通論",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "瓜谷 章 / URITANI Akira",
  },
  {
    id: "natu-209",
    title: "結晶物理学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-2",
    teacher: "山田 智明 / YAMADA Tomoaki",
  },
  {
    id: "natu-210",
    title: "実験安全学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher:
      "林 剛介 井口 弘章 内山 峰人 樫田 啓 ウヤヌク ムハメット / HAYASHI Gosuke IGUCHI Hiroaki UCHIYAMA Mineto KASHIDA Hiromu UYANIK Muhammet",
  },
  {
    id: "natu-211",
    title: "[G30]細胞学1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "野間 健太郎 / NOMA Kentaro",
  },
  {
    id: "natu-212",
    title: "物理工学演習3a",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher:
      "寺田 智樹 柏谷 聡 矢田 圭司 / TERADA Tomoki KASHIWAYA Satoshi YADA Keiji",
  },
  {
    id: "natu-213",
    title: "物理工学演習3b",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher:
      "寺田 智樹 増渕 雄一 千見寺 浄慈 / TERADA Tomoki MASUBUCHI Yuichi CHIKENJI George",
  },
  {
    id: "natu-214",
    title: "相平衡論",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "宇治原 徹 / UJIHARA Toru",
  },
  {
    id: "natu-215",
    title: "エネルギー理工学実験第1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "辻 義之 小川 智史 / TSUJI Yoshiyuki OGAWA Satoshi",
  },
  {
    id: "natu-216",
    title: "空間設計工学及び演習第2",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher:
      "堀田 典裕 宮脇 勝 臼井 直之 山上 健 斉藤 孝治 / HOTTA Yoshihiro MIYAWAKI Masaru USUI Naoyuki YAMAGAMI Takeshi SAITO Koji",
  },
  {
    id: "natu-217",
    title: "[G30]数学2及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "藤田 隆明 遠藤 知弘 / FUJITA Takaaki ENDO Tomohiro",
  },
  {
    id: "natu-218",
    title: "[G30]物理学基礎演習1a",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-3",
    teacher: "ESCRIVA MANAS Alberto",
  },
  {
    id: "natu-219",
    title: "[G30]有機化学1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "SHIN Jiyoung",
  },
  {
    id: "natu-220",
    title: "[G30]材料加工学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "梅原 徳次 西山 聖久 / UMEHARA Noritsugu NISHIYAMA Kiyohisa",
  },
  {
    id: "natu-221",
    title: "[G30]計算機ソフトウェア1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-4",
    teacher: "長谷川 浩 LU Shan / HASEGAWA Hiroshi LU Shan",
  },
  {
    id: "natu-222",
    title: "[G30]解析力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-5",
    teacher: "重森 正樹 洗平 昌晃 / SHIGEMORI Masaki ARAIDAI Masaaki",
  },
  {
    id: "natu-223",
    title: "[G30]解析力学1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Thu-5",
    teacher: "重森 正樹 / SHIGEMORI Masaki",
  },
  {
    id: "natu-224",
    title: "有機化学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher:
      "井改 知幸 荒巻 吉孝 武藤 慶 吉田 真也 / IKAI Tomoyuki ARAMAKI Yoshitaka MUTO Kei YOSHIDA Masaya",
  },
  {
    id: "natu-225",
    title: "[G30]地球惑星科学",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "HUMBLET Marc Andre",
  },
  {
    id: "natu-226",
    title: "物理工学演習1",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher:
      "寺田 智樹 矢田 圭司 松山 智至 / TERADA Tomoki YADA Keiji MATSUYAMA Satoshi",
  },
  {
    id: "natu-227",
    title: "計算機プログラミング基礎及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "河口 信夫 窪田 智徳 / KAWAGUCHI Nobuo KUBOTA Tomonori",
  },
  {
    id: "natu-228",
    title: "計算機プログラミング基礎及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "長谷川 浩 村手 宏輔 / HASEGAWA Hiroshi MURATE Kosuke",
  },
  {
    id: "natu-229",
    title: "プログラミング法および数値計算演習A",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Fri-1",
    teacher: "富田 英生 / TOMITA Hideki",
  },
  {
    id: "natu-230",
    title: "数学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "中村 崇司 小林 敬幸 / NAKAMURA Takashi KOBAYASHI Noriyuki",
  },
  {
    id: "natu-231",
    title: "数学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher:
      "砂田 茂 中村 友祐 伊東山 登 / SUNADA Shigeru NAKAMURA Yusuke ITOYAMA Noboru",
  },
  {
    id: "natu-232",
    title: "数学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "伊藤 伸太郎 本田 康平 / ITOH Shintaro HONDA Kohei",
  },
  {
    id: "natu-233",
    title: "生命化学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher:
      "樫田 啓 堀 克敏 本多 裕之 中谷 肇 清水 一憲 清中 茂樹 / KASHIDA Hiromu HORI Katsutoshi HONDA Hiroyuki NAKATANI Hajime SHIMIZU Kazunori KIYONAKA Shigeki",
  },
  {
    id: "natu-234",
    title: "量子力学A",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Fri-2",
    teacher: "柴田 理尋 / SHIBATA Michihiro",
  },
  {
    id: "natu-235",
    title: "数学1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Fri-4",
    teacher:
      "中村 友昭 趙 容桓 水谷 法美 / NAKAMURA Tomoaki CHO Yonghwan MIZUTANI Norimi",
  },
  {
    id: "natu-236",
    title: "解析力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-5",
    teacher: "星野 隆行 / HOSHINO Takayuki",
  },
  {
    id: "natu-237",
    title: "解析力学及び演習",
    department: "工",
    section: "専門基礎",
    semester: "春1",
    cellKey: "Tue-5",
    teacher: "丸山 央峰 / MARUYAMA Hisataka",
  },
  {
    id: "natu-238",
    title: "制御工学第1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher: "青山 忠義 竹内 大 / AOYAMA Tadayoshi TAKEUCHI Masaru",
  },
  {
    id: "natu-239",
    title: "制御工学第1及び演習",
    department: "工",
    section: "専門基礎",
    semester: "秋1",
    cellKey: "Mon-5",
    teacher: "早坂 健宏 / HAYASAKA Takehiro",
  },
];
